packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnParameters.ts

ref https://github.com/aws-amplify/amplify-cli/pull/10318
n/a

fix: set searchable streaming lambda debug env var default to 0

---

.circleci/config.base.yml
package.json

We needed to use a tagged release of CLI for testing purposes, and were refreshing during the release period. Once >8.1.0 is released, we should flip back to using `latest` for our test purposes.
N/A
N/A - will validate in CI

[DO NOT MERGE] chore: use latest amplify-cli and amplify-app packages for testing

---

.circleci/config.base.yml
.circleci/config.yml

We were using the wrong contexts for our setup job for e2e cleanup. Updating those, and removing the interim branches we were using during migration.

fix: update cleanup circle contexts, remove unnecessary branches

---

packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts

Function now uses node14, need to update our tests accordingly.

chore: update function test to point to node 14

---

package.json
packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2ExhaustiveT1B.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2ExhaustiveT1D.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2ExhaustiveT2B.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2ExhaustiveT2D.test.ts
packages/graphql-transformers-e2e-tests/src/authExhaustiveTestUtils.ts

- fixes auth tests for delete with partial access

test (graphql-transformers-e2e-tests): fix @auth delete with partial access test

---

packages/amplify-graphql-transformer-core/src/__tests__/transformation/transform.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts

Update the behavior where we look at the old CreateAPIKey flag from transformer v1. We had implemented this in v1 to just look for truthy behavior, which isn't consistent with the previous implementation. Explicitly updating this to only disable for value 0.
https://github.com/aws-amplify/amplify-category-api/issues/80
Ran in my local CLI to verify the 0/1 behavior a few times, and added unit tests for this behavior to ensure we have consistency in how we're handling these parameters.

fix: correct behavior for CreateApiKey config

---

.circleci/config.base.yml
packages/graphql-transformer-core/package.json

manually clean graphql-transformer-core on each build to avoid type override issues, this is a mitigation, not a solution.
I'll create an item in the backlog to dig into this later, but for now this unblocks happy-case development paths without needing to manually rebuild the env on each change.
N/A
Ran build a great many times in a row, ran setup-dev a few times, and ran unit tests.

chore: manually clean graphql-transformer-core on each build to avoid type override issues

---

packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Parallelize cleanup both across all accounts simultaneously, and across all resources of a given type at once. This requires configuring all AWS clients with an explicit account and region (except s3, which is global), so there's a bit of a refactor to pass account and regional info all the way down to client construction.
Because logs are all jumbled up now, I've added an `accountIndex` to each output per-account. Accounts were already opaque, but this way we can at least correlate errors, etc. within an account.
E.g.
```
[ACCOUNT 5] Deleting S3 Bucket amplify-e02de3f283b84aa5ab02-integtest-210400-deployment
[ACCOUNT 1] Deleting S3 Bucket amplify-iterativetest1-integtest-210353-deployment
[ACCOUNT 5] Deleting CloudFormation stack amplify-auth22dc3507d274a102-integtest-211220
[ACCOUNT 1] …
```

chore: parallelize account and resource cleanup for e2e testing

---

.circleci/config.base.yml

chore: remove dependency on integration-test for migration tests v5 and v6, I see no good reason for this dep, so removing it so that a failing 'integration test' doesn't block me from getting signal on these additional tests.
N/A
N/A, will verify in CircleCI

chore: remove dependency on integration-test for migration tests v5 and v6

---

.circleci/config.base.yml
.vscode/settings.json
packages/amplify-e2e-tests/src/__tests__/api_1.test.ts
packages/amplify-e2e-tests/src/__tests__/api_10.test.ts
packages/amplify-e2e-tests/src/__tests__/api_2.test.ts
packages/amplify-e2e-tests/src/__tests__/api_9.test.ts
packages/amplify-e2e-tests/src/__tests__/auth_2.test.ts
scripts/split-e2e-tests.ts

split api e2e tests to get runtimes under control, and move out of parent account, this is intended to help some of the consistent failures we're seeing for these two test suites.
N/A
Running e2e suite here https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/207/workflows/db988901-742e-4be0-9ce4-de2b3afe4609

chore: split api e2e tests to get runtimes under control, and move out of parent account

---

packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/amplify-e2e-tests/src/init-special-cases/index.ts

Duplicate the test changes required to core per https://github.com/aws-amplify/amplify-cli/pull/10383.
N/A, e2e tests failing on timeout due to not expecting that row.
Running e2e suite here https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/263/workflows/6a5b39d2-e8c6-4ed2-aae3-d27714319cde

chore: make test updates per https://github.com/aws-amplify/amplify-cli/pull/10383/files

---

packages/amplify-category-api/package.json
packages/amplify-dynamodb-simulator/package.json
packages/amplify-e2e-core/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-migrator/package.json
packages/amplify-util-mock/package.json
packages/graphql-transformer-core/package.json
yarn.lock

flip common deps in CLI to peer instead of regular dependencies
this should protect us from some of the 'Feature Flags is not initialized' type errors we've seen, by ensuring the CLI uses it's own local version of the FeatureFlags lib.
N/A
`yarn setup-dev` and then ran a few test commands w/ `amplify-dev api gql-compile`

chore: flip common deps in CLI to peer instead of regular dependencies

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/owner-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithAuthV2WithFF.e2e.test.ts

Updates the list query when querying by primary key to use the `<sub>::<username>` identity claim for the sort key (and not have a set of sort keys as the other query types work).

fix: use concatenated identity claim for primary key queries

---

packages/amplify-category-api/package.json
packages/amplify-dynamodb-simulator/package.json
packages/amplify-e2e-core/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-migrator/package.json
packages/amplify-util-mock/package.json
packages/graphql-transformer-core/package.json
yarn.lock

Moves the dependencies on CLI core and other packages to peer dependencies to avoid problems with initializing FF by having consistent version of CLI core.
Changes already reviewed in #520 

chore: flip common deps in CLI to peer instead of regular dependencies (#520)

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/owner-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts

Bug fix: when operations don't include `read` operation with the `sub::username` identity claim, the sub prefix does not get stripped out from the return value, so clients would see `sub::username`.

fix: create owner field resolvers for all operations

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/graphql-transformers-e2e-tests/src/__tests__/IndexTransformer.e2e.test.ts

Handle begin and end VTL keywords in the index name. Currently the index name is wrapped with double quotes which doesn't handle the vtl keywords. Changing it to single quote to handle begin and end keyword in vtl.
Fixes https://github.com/aws-amplify/amplify-category-api/issues/40
- yarn test
- manual test
- new unit and e2e tests added

fix(graphql): handle begin and end vtl keywords in index name

---

packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-index-transformer/src/__tests__/utils.test.ts
packages/amplify-graphql-index-transformer/src/graphql-index-transformer.ts
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-index-transformer/src/types.ts
packages/amplify-graphql-index-transformer/src/utils.ts
packages/graphql-transformer-common/src/util.ts
packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithAutoQueryField.e2e.test.ts
yarn.lock

Add support for default generation of query and gsi names for @index directive behind a feature flag.
For customers with the feature flag disabled the following behavior will exist:
* The `name` field on the `@index` directive will now be optional, and default to generating a GSI with name like `by{FieldName}{forEach SortKeyField}And{sortKeyField}{/forEach}.
* query will not be generated unless a `queryField` field is provided on the directive by the user.
For customers with the feature flag enabled:
* The `name` field on the `@index` directive will now be optional, and default to generating a GSI with name like `by{FieldName}{forEach SortKeyField}And{SortKeyField}{/forEach}.
* query will be generated unless a `queryField` field is provided on the directive by the user, either as a string …

feature: add support for default generation of query and gsi names for @index directive behind a feature flag

---

packages/amplify-category-api/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-setup.ts

Fix failing datastore modelgen e2e tests.
- datastore-modelgen.test.ts
- amplify-app.test.ts

test(graphql): fix failing datastore modelgen tests

---

projectdata/README.md
projectdata/aggregate-poc/package.json
projectdata/aggregate-poc/resources/lambda/aggregateSearch/index.js
projectdata/aggregate-poc/resources/lambda/benchmarkQueries/index.js
projectdata/aggregate-poc/resources/lambda/eventBusDemo/index.js
projectdata/aggregate-poc/resources/resolver/movieAggregateSearch.req.vtl
projectdata/aggregate-poc/resources/resolver/movieAggregateSearch.res.vtl
projectdata/aggregate-poc/resources/schema/schema.graphql
projectdata/aggregate-poc/src/stacks/aggregate-stack.ts

Adding a new lambda which can perform more generalized queries against a table, and produce aggregates for min/max/sum/count/avg
A few example queries made through appsync
```graphql
query SimpleQuery {
movieAggregateSearch(
aggregateField: "info.running_time_secs"
partitionKeyComparison: {comparedValue: 2040, fieldName: "year"}
filterComparisons: {comparedValue: 5400, comparisonType: GT, fieldName: "info.running_time_secs"}
) {
count
max
min
sum
average
}
}
query MidRatedMovies {
movieAggregateSearch(
aggregateField: "info.running_time_secs"
partitionKeyComparison: {
comparedValue: 2040
fieldName: "year"
}
filterComparisons: [
{
comparedValue: 5400
comparisonType: GT
fieldName: "info.running_time_secs"
}
{
rangeStart: 5
rangeEnd: 7
comparisonType: BETWEEN
fieldName: "info.rating"
}
]
) { …
```

Feature/data stream add aggregateSearch functionality, and tease out possible api a bit

---

packages/amplify-graphql-auth-transformer/src/__tests__/relations-auth.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-relations-with-custom-primary-key.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/test-helpers.ts
packages/amplify-graphql-relational-transformer/src/schema.ts
packages/amplify-graphql-relational-transformer/src/utils.ts
packages/amplify-util-mock/src/__e2e_v2__/model-relational-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e_v2__/model-relational-with-key-transformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/BelongsToTransformerV2.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MapsToTransformer.e2e.test.ts

- changing feature flag as it's controlling more than just the PK connection field name
- CLI related PR: https://github.com/aws-amplify/amplify-cli/pull/10617/files

chore: change flag name for PK properties

---

packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-index-transformer/src/schema.ts

We have a bunch of bare `assert`s in our code, which can lead to poor UX for errors. This addresses one which we'd identified, but there are more, and we should instead be writing custom validation/error logic since assert doesn't play nicely once you have tests for failure, and they don't default to user-friendly messaging. I've created a backlog item to fix the rest of these occurrences.
https://github.com/aws-amplify/amplify-category-api/issues/498
Validated that I get a more readable error given the repro from Josef, and added a unit test to cover this case.

chore: improve error messaging if an invalid boolean sort key is provided to @index

---

packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts
packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
packages/amplify-graphql-auth-transformer/src/utils/definitions.ts
packages/amplify-graphql-auth-transformer/src/utils/schema.ts
packages/amplify-graphql-default-value-transformer/src/__tests__/__snapshots__/amplify-grapphql-default-value-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/definitions.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/graphql-types/common.ts
packages/amplify-graphql-model-transformer/src/graphql-types/query.ts
packages/amplify-graphql-model-transformer/src/resolvers/subscriptions.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/graphql-transformer-common/src/ModelResourceIDs.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsRuntimeFiltering.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2WithFF.e2e.test.ts

This PR adds support for subscriptions runtime filtering. 
List of changes:
- Adds new filter subscription input type for each model type.
- Adds a new argument `filter` for the generated subscriptions.
- Uses AppSync enhanced filtering to support server side runtime filtering.
- Adds @auth subscriptions support for multiple owners field (`owners: [String]`)
Fixes https://github.com/aws-amplify/amplify-category-api/issues/372
- Manual test
- Unit test
- e2e test

feat(graphql): add runtime filtering support for subscriptions

---

packages/amplify-category-api/src/provider-utils/awscloudformation/utils/dynamic-imports.ts

The supported-datasources file was linted [here](https://github.com/aws-amplify/amplify-category-api/commit/b72f9e7870640fc11897ef7e1b60e24e97f9052f) which renamed `supportedDatasources` to `supportedDataSources`. One reference to the old capitalization was not renamed.

fix: update object reference to match cap change

---

packages/amplify-category-api/resources/schemas/aPIGateway/APIGatewayCLIInputs.schema.json
packages/amplify-category-api/resources/schemas/appsync/AppSyncCLIInputs.schema.json
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/api-input-manager/appsync-api-input-state.test.ts
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cfn-api-artifact-handler.test.ts
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/get-appsync-auth-config.test.ts
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/migrate-api-override-resource.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthrough-types/appsync-user-input-types.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/migrate-api-override-resource.ts

Since `gqlSchemaPath` doesn't be actually used for gql-compilation, we remove it entirely and use the path computed on-the-fly.
fix #123
- Unit Testing (`yarn test`)
- Manual Testing
- `amplify-dev api add`
- `amplify-dev api update`

fix: remove `gqlSchemaPath` in cli-inputs.json

---

packages/amplify-category-api/src/__tests__/graphql-transformer/api-key-helpers.test.ts

mock object (`ApiCategoryFacade`) in `api-key-helpers.test.ts` is incorrect. `CloudformationProviderFacade` is correct.
```console
yarn test
```
The following error occurred when I ran the test
```console
TypeError: Cannot read properties of undefined (reading 'getProviderPlugins')
at /Users/m-murakami/git/amplify-category-api/node_modules/amplify-cli-core/src/plugin-facade/cloudformation-provider-facade.ts:45:57
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at Function.getApiKeyConfig (/Users/m-murakami/git/amplify-category-api/node_modules/amplify-cli-core/src/plugin-facade/cloudformation-provider-facade.ts:45:28)
at hasApiKey (/Users/m-murakami/git/amplify-category-api/packages/amplify-category-api/src/graphql-transformer/api-key-helpers.ts:261:29)
FAIL …
```

test: change to correct mock object for `getApiKeyConfig` method

---

packages/graphql-elasticsearch-transformer/scripts/ddb_to_es.py

Support credentials for lambda client on backfill script `ddb_to_es.py`
Without this changes, the script fails when locally executing it with the arguments:
```bash
python3 ddb_to_es.py \
--rn 'us-west-2' \
--tn 'Post-XXXX-dev' \
--lf 'arn:aws:lambda:us-west-2:123456789xxx:function:DdbToEsFn-<api__id>-dev' \
--esarn 'arn:aws:dynamodb:us-west-2:123456789xxx:table/Post-<api__id>-dev/stream/2019-20-03T00:00:00.350' \
--ak 'XXX' \
--sk 'XXX' \
--st 'XXX'
```
Running the script against a dev environment (wasn't able to run `yarn test` since the dev setup `yarn setup-dev` was failing)
####NOTES
This code has been moved from a different repository, here the link to the original PR …

Support credentials for lambda client

---

package.json
yarn.lock

- Fixes https://github.com/aws-amplify/amplify-category-api/security/dependabot/16
- Referesh yarn.lock file

chore: fix dependabot alert by bumping parse-path version

---

packages/amplify-graphql-maps-to-transformer/src/__tests__/__integ__/with-many-to-many.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-relations-with-custom-primary-key.test.ts
packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

- uses PK name in connection field in the many to many middle object
- manual testing and `yarn test`

fix: use PK name in many to many link object

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/resolvers/query.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/graphql-transformers-e2e-tests/src/__tests__/ModelTransformer.e2e.test.ts

Validate filter expression on model transformer.
- yarn test
- manual test
- e2e tests

fix(graphql): incorrect filter expression on model transformer

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cfn-api-artifact-handler.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
yarn.lock

* When a NEW lambda conflict resolver is set up, we're not appropriately reflecting the generated state of the lambda back to cli-inputs.json, leading to a push failure. This refactor allows us to correctly update state.
* https://github.com/aws-amplify/amplify-category-api/issues/628
Unit test for this use-case, and manually tested with an `amplify-dev update api` .

fix: update api should allow setting NEW lambda conflict resolver

---

packages/amplify-graphql-auth-transformer/src/__tests__/utils/warnings.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/warnings.ts

Show a warning on gql-compile when an `owner` has permissions to `update` their referenced owner field. This will apply to userPools and oidc providers, and should work regardless of whether the user is using a generated owner field, provided one, or list of owners.
As a followup I'll be adding a metric to this as well, so we can determine how many customers are encountering this condition, and whether or not we should consider changing the default behavior of ownership.
N/A
Unit tests, ran `setup-dev` target and verified against a few schemas that I was seeing/not seeing this warning when expected.

chore: add support for warning on owner who can reassign owner field

---

package.json

Add script to selectively test v2 transformers packages. This is helpful to test v2 transformers packages after a resolver change without the need to run test on all packages.

chore(api): add script to test v2 transformers

---

package.json
packages/amplify-category-api/src/category-utils/context-util.ts
packages/amplify-category-api/src/category-utils/schema-reader.ts
packages/amplify-category-api/src/graphql-transformer/constants.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-category-api/src/graphql-transformer/transformer-factory.ts
packages/amplify-category-api/src/graphql-transformer/transformer-options-types.ts
packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
packages/amplify-graphql-transformer-core/src/index.ts

This adds the capability for but does not enable single source reading on GraphQL schemas
This is intended for GraphQL Transformer V2 without support for V1
This also required pulling apart some of the logic in schema transformation so I can actually instantiate the transformer elsewhere
No validation yet, runtime change that hasn't been enabled. Running tests to make sure I haven't broken any existing functionality when refactoring the code

Feat: Single Source Read

---

packages/amplify-e2e-tests/schemas/schema_with_index.graphql
packages/amplify-e2e-tests/src/__tests__/graphql-v2/sync_query_datastore.test.ts
packages/amplify-graphql-index-transformer/package.json
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-index-transformer/src/graphql-index-transformer.ts
packages/amplify-graphql-index-transformer/src/graphql-primary-key-transformer.ts
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts

Adds a check to identify if the current query operation falls outside the delta table TTL window.
Avoids scanning the entire base table but query it when `syncExpression` returns a predicate that maps to a query expression. Relevant [doc](https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#advanced-use-case---query-instead-of-scan).
This improves the performance of the query significantly as called out in the above doc section.
The Delta Sync Table TTL is set to 30 mins by Amplify CLI when conflict detection is enabled by the developer.
Developers however can override this value following the guide [here](https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-model-directive).
If the delta sync table TTL is overridden, we will use the overridden …

Avoid scan on base table when sync expression is specified on index field

---

jest.config.js
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/graphql-v2/lambda-conflict-handler.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-transformer-core/src/__tests__/transformation/sync-utils.test.ts
packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts

- fix: update api should allow setting NEW lambda conflict resolver
- fix: set cfn values correctly when applying lambda-based conflict resolution
https://github.com/aws-amplify/amplify-category-api/issues/628
Unit tests, deployed app locally w/ these changes, and additional e2e tests to cover this use case.

fix: Enable Custom Lambda Conflict Handler support in GQLv2-enabled Applications

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts

Functional changes are in `_setDeploymentResource`. All other changes were auto-fixed by the linter or me trying to make the linter happy while not bloating the PR too much.
This change fixes the flakiness we have seen in `apigw.test.ts` where the default CORS headers are not included in 4xx and 5xx responses. This was caused because the REST API, default responses and REST API deployment are all separate CFN resources. The REST API deployment has an implicit dependency on the REST API, but the default responses must also be provisioned before the REST API deployment is provisioned. There was a race condition where sometimes the default responses would be provisioned in time and sometimes not. This PR adds an explicit dependency between the REST API deployment and the default response …

fix: race condition provisioning default apigw responses

---

packages/amplify-category-api/package.json
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-graphql-schema-test-library/package.json
packages/amplify-util-mock/package.json
packages/graphql-transformers-e2e-tests/package.json

Manually bump the major version for Auth V2 transformer and API plugin. This is because of an [existing bug in lerna](https://github.com/lerna/lerna/issues/2668) that fails to detect the conventional commit for breaking changes.

chore: manually bump major version

---

packages/amplify-graphql-default-value-transformer/src/__tests__/__snapshots__/amplify-grapphql-default-value-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap

Cleanup the type generation added for subscriptions RTF.

chore(graphql): subscription rtf unused filter types cleanup

---

packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts

Add subscription tests with variable syntax.
- Pass owner argument with variable syntax.
- Use variable syntax but do not pass optional argument value.

test(graphql): add subscription tests with variable syntax

---

packages/amplify-graphql-auth-transformer/src/accesscontrol/acm.ts
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-index-transformer/src/schema.ts
packages/amplify-graphql-relational-transformer/src/__tests__/resolvers.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/schema.test.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-relational-transformer/src/schema.ts
packages/amplify-graphql-relational-transformer/src/utils.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-datasource.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
packages/amplify-graphql-searchable-transformer/src/definitions.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/output.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-graphql-transformer-core/src/utils/schema-utils.ts

Today, we have a number of `assert` statements in source which we shouldn't do. This PR replaces those with either `Error`s for faults, or `InvalidDirectiveExceptions` where invalid input is caught, to provide better visibility into operator error vs bugs.
N/A
I would have like to add more unit tests, but given the surface area of the change that was slowing me down, so I'm relying on e2e tests to verify all use-cases here.

chore: remove all asserts in source code, replace with error for internal exceptions, and InvalidDirectiveExceptions for input errors

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-e2e-tests/src/__tests__/apigw.test.ts

This PR will fix the rest api dropping gateway response on update api issue.
With this change, we will assign a new logical id to the gateway response resources on each push so it would be treated as deleting the old one and creating a new one instead of updating the existing one.
Fixes #30 
- manual test
- e2e test

fix(api): gateway response dropping on update api

---

packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/init/amplifyPush.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts

Removed the `All resources are updated in the cloud` wait in amplify push to unblock the e2e tests. The related change in CLI: https://github.com/aws-amplify/amplify-cli/pull/10720

fix(e2e): remove all resources update wait

---

packages/amplify-e2e-tests/schemas/model_with_datatypes.graphql
packages/amplify-e2e-tests/src/__tests__/graphql-v2/invalid-input-arguments.test.ts
packages/amplify-e2e-tests/src/__tests__/graphql-v2/invalid-input-arguments.ts

Add negative test cases for mutations and queries with invalid inputs and arguments.
- Invalid data type check
- Invalid arguments length
- Invalid filter with 'and' and 'or' conditions

test(graphql): add negative test cases for invalid inputs and arguments

---

packages/amplify-e2e-tests/schemas/iterative-push/add-sort-to-primary-key/final-schema.graphql
packages/amplify-e2e-tests/schemas/iterative-push/add-sort-to-primary-key/initial-schema.graphql
packages/amplify-e2e-tests/src/__tests__/schema-iterative-update-5.test.ts
packages/graphql-transformer-core/src/util/sanity-check.ts

We aren't currently detecting and warning users that a GraphQL schema change which adds a sort key to a primary key is a destructive update, or even performing the destructive update.
This adds the sanity check warning, and should go with a amplify-cli PR to actually perform the destructive update when `--allow-destructive-graphql-schema-updates` is provided
N/A
Debugged to see what a sort key addition looks like, ran `amplify-dev` against a project with a sort key change and without the change

Fix: detect when sort key added to primary key

---

packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts
packages/amplify-graphql-searchable-transformer/src/generate-resolver-vtl.ts

These changes refactor a step in the Request Mapping Template that is generated by the Searchable V2 transformer.
The step is responsible for constructing a Map that contains the Aggregate values that will eventually be used in the construction of the Search Query. The current refactor dynamically generates this Map instead of a raw JSON representation. 
This is necessary for the Searchable Mocking to work since the mock VTL compiler does not read raw JSON representations.
The test snapshot updates show the change in the Request Mapping Template.
Added explicit checks as well.

chore(amplify-graphql-searchable-transformer): refactor the expression to construct aggregate values

---

.circleci/config.base.yml
.circleci/local_publish_helpers.sh
client-test-apps/js/api-model-relationship-app/.gitignore
client-test-apps/js/api-model-relationship-app/package.json
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/amplifyCLI.ts
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/execUtils.ts
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/jsonUtilities.ts
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/testHarness.ts

Add a new Circle step to run the first client test app via Circle. Verified in a branch https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/1126/workflows/bd73083d-ceea-4ae7-bf63-760085d38cfc/jobs/32937/steps
N/A
test runs/passes 2/2 for the last few runs

feat: enable running client tests as part of circle ci workflow

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/resolvers.ts

The default value for `lastSync` should be set to `null` if it doesn't exist in the input arguments. However, currently it is set to "null" string because of converting it to JSON twice, which is being wrongly interpreted in the Sync Query request. This change fixes it.
https://github.com/aws-amplify/amplify-category-api/issues/806
Using the customer provided schema in the issue and a sample app.

Set default lastSync correctly

---

package.json
yarn.lock

- Refresh the yarn lock file using `yarn refresh-lockfile`.
- Address the dependabot alert [#17](https://github.com/aws-amplify/amplify-category-api/security/dependabot/17),  [#19](https://github.com/aws-amplify/amplify-category-api/security/dependabot/19) and [#21](https://github.com/aws-amplify/amplify-category-api/security/dependabot/21)
- Update lerna version to match with CLI and Codegen versions. 

chore: fix dependabot alerts

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

Add `indexName` existence check in case of getting into the wrong resolved connected fields
Reported in the CPK bug bash slack channel

fix(relation-transformer): belongsTo resolves to correct connected fields

---

client-test-apps/js/api-model-relationship-app/cypress/e2e/auth-modes.cy.ts
client-test-apps/js/api-model-relationship-app/src/App.tsx
client-test-apps/js/api-model-relationship-app/src/NavBar.tsx
client-test-apps/js/api-model-relationship-app/src/__tests__/api.test.ts
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/amplifyCLI.ts
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/testHarness.ts
client-test-apps/js/api-model-relationship-app/src/components/AuthModePicker.tsx
client-test-apps/js/api-model-relationship-app/src/components/CRUDLComponents.tsx
client-test-apps/js/api-model-relationship-app/src/components/HarnessContext.tsx
client-test-apps/js/api-model-relationship-app/src/components/ModelHarness.tsx
client-test-apps/js/api-model-relationship-app/src/components/OperationStateHandler.tsx
client-test-apps/js/api-model-relationship-app/src/components/Subscriptions.tsx
client-test-apps/js/api-model-relationship-app/src/pages/AuthModes.tsx
client-test-apps/js/api-model-relationship-app/src/pages/index.ts

This verifies the behavior that was witnessed in these a few bugs, has not regressed. I've added an owner-auth enabled model, and verified that I can successfully subscribe and receive subscription data w/ no owner set.
https://github.com/aws-amplify/amplify-category-api/issues/758, https://github.com/aws-amplify/amplify-category-api/issues/134
Tested locally, and ran in CI - https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/1264/workflows/e5a29202-2bc2-4c0c-af0c-c4a4e3ebd388/jobs/37099

chore: adding regression test for apikey+owner auth model to verify that subscriptions where owner is undefined works

---

packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
packages/amplify-graphql-auth-transformer/src/utils/schema.ts
packages/amplify-graphql-default-value-transformer/src/__tests__/__snapshots__/amplify-grapphql-default-value-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/resolvers/subscriptions.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsRuntimeFiltering.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2WithFF.e2e.test.ts

This PR enables subscription runtime filtering.
- Adds filter argument to subscriptions to provide server side filtering.
- Supports subscriptions with multiple owners auth rules.
- yarn test
- manual test
- e2e test

feat(graphql): subscriptions rtf support

---

packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts

E2E fix to resolve Subscription failing tests.
Removing the optional argument test because AppSync fixed this argument style.
Note: There are other tests to validate optional argument syntax.

test(graphql): remove test case added to test appsync bug

---

.circleci/config.base.yml
.circleci/config.yml

add canary to run client e2e tests, these can be triggered either by the schedule (4 times daily), or kicked off manually by setting the `canary` parameter.
__N.B. To support running both scheduled and from a manual kickoff I've had to redeclare the workflow in both `config.yml` and `config.base.yml`, and duplicate a few workflow steps and commands into `config.yml`. I'd rather have this duplication and the ability to trigger manual canary runs, at the cost of possible divergence.__
Publishing metrics to CW will come as a separate PR.
N/A
Verified the manual job in CCI, but still need to verify the scheduling. Because the job is running against main for scheduling, it's not finding the config on that branch, so I'll need to verify once this is merged. I have manually run a canary workflow …

chore: add canary to run client e2e tests

---

.circleci/config.base.yml
.circleci/config.yml
.circleci/local_publish_helpers.sh

Two changes:
* Separate to have simple 'success/fail' bash commands
* Update conditional, which wasn't working in the previous state, now we just publish anytime we're on `main`.
N/A
Explicitly failed the workflow, and tested over here https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/1409/workflows/200c8212-0cbe-4222-a620-20d00ebd7886/jobs/38690

fix: correct canary metric emission logic, remove all injected env variables to simplify calling

---

packages/amplify-graphql-searchable-transformer/package.json
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer-override.test.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnOutput.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnParameters.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-layer-cfnMapping.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-datasource.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
yarn.lock

Migrate `@aws-amplify/graphql-searchable-transformer` to use CDKv2.
Follow ups for later:
- Investigate if `OpenSearchDomain` -> `OpenSearchDomain85D65221` is breaking anything. https://app.asana.com/0/1202389680978480/1203144344852802/f
- Deprecated API usage `Domain from 'aws-cdk-lib/aws-elasticsearch'` and `domain.*` apis. https://app.asana.com/0/1202389680978480/1203144344852804/f
`yarn clean && yarn dev-build && yarn test` passes.
E2E don't compile yet.
- [x ] PR description included

feat: migrate searchable transformer to CDK v2

---

packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-function-transformer/src/__tests__/__snapshots__/amplify-graphql-function-transformer-override.test.ts.snap
packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer.test.ts
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
yarn.lock

This PR migrates `@aws-amplify/graphql-function-transformer` to CDK v2.
Gotchas:
- There seems to be a change in `@aws-cdk/aws-appsync-alpha` that creates more permissive policy. See PR comment below.
`yarn clean && yarn dev-build && yarn test` passes.
E2E don't compile yet.
- [x ] PR description included
- [ x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

feat: migrate function transformer to CDK v2

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/commands/api/add-graphql-datasource.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/api_9.test.ts

This PR fixes the `add-graphql-datasource` command workflow and amplify pull behavior for existing RDS projects.
Fixes #767, #481 
- manual test
(Writing an E2E for this requires a RDS instance, we need to come up with an option to include this on our E2E.)

fix(graphql): add rds datasource v1 fix

---

packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
packages/amplify-graphql-auth-transformer/src/utils/index.ts

If static groups are provided as a single string instead of a list, perform the conversion
https://github.com/aws-amplify/amplify-category-api/issues/760
Unit testing

Fix: Allow single static group as string

---

packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
yarn.lock

This PR migrates `@aws-amplify/graphql-http-transformer` to CDK v2.
`yarn clean && yarn dev-build && yarn test` passes.
E2E don't compile yet.
- [ x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

feat: migrate http transformer to CDK v2

---

packages/amplify-e2e-tests/src/__tests__/transformer-migrations/searchable-migration.test.ts

Set 2 hour for `searchable-migration` test to avoid the timeout error
Run the e2e test locally. The test is passed and takes 3800 seconds (more than 1 hour)

fix(e2e): set longer timeout for searchable migration

---

packages/amplify-graphql-transformer-core/src/cdk-compat/nested-stack.ts

Do not cache nested stack template urls. 
The nested stack processing goes through two stage resolution.
1. it resolves root stack (template urls are "<unresolved"> by this time).
2. for each nested stack it invokes `_prepareTemplateAsset` which populates templateUrl.
3. runs root stack resolution again. it's expected that template urls resolve here (if not cached).
See for reference:
https://github.com/aws/aws-cdk/blob/5a0595edb1c5345552acbacefe2d09ec0bea31c1/packages/%40aws-cdk/core/lib/private/prepare-app.ts#L30-L56
Sample error caused by this.

fix: resolution of nested stack template url

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-graphql-maps-to-transformer/src/__tests__/__integ__/with-many-to-many.test.ts
packages/amplify-graphql-maps-to-transformer/src/__tests__/__integ__/with-model.test.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer-override.test.ts.snap
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer-override.test.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
packages/amplify-graphql-transformer-core/src/cdk-compat/nested-stack.ts

CDK started to add hash at the end of DynamoDB table and SearchDomain logical ids.
This would mean deletion and creation of these resources for existing customers. Which is destructive without data migration.
Therefore we override logical id at L1 construct level to maintain current behavior.
- [x ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

fix: preserve logical id patterns for dynamodb tables and search domain

---

.circleci/config.base.yml

Bump memory setting for `mock_e2e_tests`. It goes over current limit while generating test report.
After applying the change in the release tag build.

chore: bump memory for mock_e2e_tests

---

packages/amplify-graphql-transformer-core/src/cdk-compat/nested-stack.ts
packages/amplify-graphql-transformer-core/src/cdk-compat/schema-asset.ts

Replaced the deprecated methods which are indicated by the upgrade of CDK.
For the `uncachedString`, please refer https://github.com/aws-amplify/amplify-category-api/pull/893 and https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.Lazy.html#static-uncachedwbrstringproducer-options
Not in scope: the deprecated methods/modules for `@searchable`
Running `amplify-dev api gql-compile` and check the console output

fix: replace deprecated cdk methods

---

packages/amplify-category-api/src/index.ts

Disable the CDK deprecation warning msg. This will be removed once the migration to CDK V2 is complete. The msg can still be seen on the CI/debug environment.
Refer https://github.com/aws/aws-cdk-rfcs/blob/master/text/287-cli-deprecation-warnings.md#cdk-cli-deprecation-warnings
`amplify-dev api gql-compile`

fix: suppress CDK deprecation warnings

---

packages/amplify-category-api/src/index.ts
packages/amplify-graphql-transformer-core/src/cdk-compat/nested-stack.ts
packages/amplify-graphql-transformer-core/src/cdk-compat/schema-asset.ts

Suppress CDK migration warnings coming out of API category plugin **until** we migrate to using CDK V2 constructs.
[e2e full pipeline](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/1807/workflows/ff2eb331-94e9-4d29-888d-cd0c9a46f7ba) runs successfully

Release feat: suppress CDK migration warnings

---

packages/graphql-transformers-e2e-tests/resources/jsonServer/yarn.lock
scripts/yarn.lock

Deleting and rebuilding yarn.lock files to address out-of-date deps in some of our CI-related packages.
N/A
CI tests, also running e2e suite here https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/1894/workflows/3be00d6b-c899-47da-a03f-596d6f9013cc

chore: re-materialize yarn.lock files for scripts and test jsonServer packages to mitigate dependabot alerts

---

packages/amplify-e2e-tests/src/__tests__/containers-api-1.test.ts
packages/amplify-e2e-tests/src/__tests__/containers-api-2.test.ts
scripts/split-e2e-tests.ts

This splits two long running tests in order to:
- decrease total load
- increase stability and retryability (they both running in same job compounds chance of failed attempt)
FWIW this has been split in CLI repo for the same reason
See https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-e2e-tests/src/__tests__/containers-api-1.test.ts
and https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-e2e-tests/src/__tests__/containers-api-2.test.ts
E2E tests run https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/1940/workflows/77347e4a-bf0e-4441-83c0-928d111f7fe3
- [ x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
By …

chore: split containers-api tests

---

packages/amplify-graphql-auth-transformer/src/resolvers/field.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-relations-with-custom-primary-key.test.ts.snap
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2.e2e.test.ts

Protect relational fields when field rules are more restrictive than the model auth rules.
NA.
- manual testing
- added new e2e tests

fix(graphql): protect relational fields when fields rules are restrictive

---

packages/amplify-graphql-function-transformer/README.md
packages/amplify-graphql-function-transformer/src/__tests__/__snapshots__/amplify-graphql-function-transformer.test.ts.snap
packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer.test.ts
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
packages/graphql-function-transformer/src/FunctionTransformer.ts
packages/graphql-function-transformer/src/__tests__/FunctionTransformer.test.ts
packages/graphql-function-transformer/src/lambdaArns.ts
packages/graphql-transformer-common/src/FunctionDirectiveConfig.ts
packages/graphql-transformer-common/src/FunctionResourceIDs.ts
packages/graphql-transformer-common/src/index.ts

This change does not come with E2E tests because I don't know whether the
existing CI infra has access to multiple AWS accounts.
However, I tested this in my own two AWS accounts.
Adds support for `accountId: XYZ` attribute on `@function` directive, to allow data sources
to be Lambda functions in a different AWS account than the AppSync instance.
#499 
1. Unit tests
2. Deployed an Amplify application to my AWS account *A* with a function referencing AWS account *B*. Created the function in *B*, issued a GraphQL query against my instance, and verified that the function in *B* gets invoked.

feat(graphql-function-transformer): support cross-account lambda resolvers using @function (#499)

---

packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsRuntimeFiltering.e2e.test.ts

Add support for dynamic groups in subscriptions with enhanced filtering
E2E, unit, manual testing

Dynamic group subscriptions

---

packages/amplify-category-api/src/provider-utils/awscloudformation/utils/migrate-api-override-resource.ts
yarn.lock

chore: refresh yarn.lock file, remove deprecated import for error type

---

.github/workflows/issue-pending-response.yml

adds GitHub Action to automatically remove the `pending-response` label when the author of the issue responds. This will also adjust how we look at issues that have not yet been triaged by further defining an entrypoint:
https://github.com/aws-amplify/amplify-category-api/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+-label%3Abug%2Cfeature-request%2Crfc%2Cregion-support+-label%3Apending-response
n/a
piloted on CLI repository

feat: add github action to automatically remove pending-response label

---

.circleci/config.base.yml
.circleci/config.yml

Currently, jobs are allowed to hang up to 90 minutes (for each retry) if there is no output from the test. Usually, this happens if there are resource limits or other errors that cause the process to hang.
Also, if a test hangs for 90 minutes, it will fail at 90 minutes and re-try; and if it fails again, you've got 3 hours spent waiting on this test. We can at least shave an hour off the worst case scenario by doing this.
The longest running test during a successful run completes in about 1 hour as shown [here](https://app.circleci.com/pipelines/gh/aws-amplify/amplify-category-api/1784/workflows/c2720418-7aa6-4412-9d79-811c9dd57c91). So 60 minutes is a reasonable timeout.

chore: reduce timeouts on circleci tasks

---

.circleci/config.base.yml
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

This change ensures that we are cleaning up correctly after each test run, even if a test fails.
For example, in this run you can see that the cleanup script does not run because of some tests failing:
Solution: use a job awaiter task
As you can see below, some tests failed, but the cleanup script is still able to run, thanks to its dependency on the wait_for_all task that doesn't rely on passing tests.

fix: cleanup script does not run if tests fail

---

.circleci/config.base.yml
.circleci/validate_cdk_version.ts

This PR adds validation that checks for presence of @aws-cdk/core which indicates presence of V1 CDK somewhere in dependency tree. This is to make sure we don't regress to V1 during merges from dev.
Similar change in CLI repo:
https://github.com/aws-amplify/amplify-cli/pull/11434

chore: validate cdk version

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/rds-secrets/ssmClient.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-secrets/ssmClient.ts

Adds utility methods to be used to store DB connection secrets in AWS SSM managed parameter store.
Added unit tests

feat: add utils for parameter store interactions

---

packages/amplify-graphql-auth-transformer/src/__tests__/utils/warnings.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/warnings.ts

Added a warning to prevent additional ownerFields to be created in case of a case mismatch
✅ Closes: #957
Added a warning when ownerField in lower case is the same as a schema field in lower case to prevent case mismatch.
Closes #957
`yarn test` and custom app with the following schema:
```graphql
type Invoice
@model
@auth(
rules: [
{ allow: owner, ownerField: "storeID", operations: [create, read] }
{ allow: owner, ownerField: "customerID", operations: [create, read] }
]
) {
id: ID!
items: [String]
storeId: ID!
customerId: ID!
}
```
The following warnings are raised:

feat: 🎸 Added warning when  ownerField similar to schema field

---

packages/amplify-e2e-core/src/nexpect-reporter.js

Often, when tests fail we are unable to playback the artifacts, and must scan through a bunch of .cast files to figure out the error trail. This process is very manual and slow, often there are ten files or more, and they currently don't print in-order, so you have to look through each one to find the error.
Instead, we can use labels that use timestamps, & and order indicator, so that it is easier to find the file that contains the error, usually the first file that occurs before the "amplify delete" teardown step.
So, what does it look like now?
Take this example.. using this change, I can quickly scan the files to see what commands were executed for each test on the right hand side. I can also see that the .cast files are in order. Additionally, I can quickly go to the file that …

fix: add proper labels to artifacts in E2E

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/schema.ts

Refactor the impact of non-nullable field with relation directive on the generated connection fields in object definition and input types.
- Connection fields(foreign keys) will always be nullable in the `UpdateInput` type, which is consistent to other non-nullable fields.
Fix https://github.com/aws-amplify/amplify-codegen/issues/461

fix(relation-transformer): relation field nullability in object and input type

---

.circleci/config.base.yml
packages/amplify-category-api/package.json
packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json
packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
packages/amplify-dynamodb-simulator/package.json
packages/amplify-e2e-core/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/__tests__/api_7.test.ts
packages/amplify-e2e-tests/src/__tests__/apigw.test.ts
packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-index-transformer/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-migrator/package.json
packages/amplify-util-mock/package.json
packages/graphql-transformer-core/package.json
yarn.lock

This PR:
- uses AmplifyError instead of workaround to emit override error.
- bumps cli versions needed for this change
- brings back tests that were commented out earlier

chore: use AmplifyError for overrides failure

---

.circleci/config.base.yml

Undo part of https://github.com/aws-amplify/amplify-category-api/pull/994/files . I.e. increase timeout back to 90m for e2e tests.
The `searchable-migration-l` test keeps timing out consistently. So bumping timeout back to original value until better solution is put in place.

chore: bump timeout for e2e tests

---

packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts
packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts
packages/amplify-graphql-auth-transformer/src/resolvers/search.ts

Fixes the Auth transformer to properly set the allowed aggregate fields in the stash for Search query auth resolvers with IAM auth and having admin roles.
https://github.com/aws-amplify/amplify-category-api/issues/73
Added unit test and JS sample app.

fix: aggregate fields access for iam auth with admin roles

---

packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts

enforcing all network traffic for elasticsearch domains to be over HTTPS instead of HTTP. Added a oneliner in the cloudformation scripts from the documentation: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticsearch-readme.html#audit-logs
n/a
ran yarn test
- [n/a] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [n/a] Relevant documentation is changed or added (and PR referenced)
- [n/a] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

chore: enforcing traffic on ES domains via HTTPS

---

packages/amplify-category-api/amplify-plugin.json
packages/amplify-category-api/src/commands/api.ts
packages/amplify-category-api/src/commands/api/import.ts
packages/amplify-graphql-schema-generator/package.json
packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/mysql-datasource-adapter.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/datasource-adapter/mysql-datasource-adapter.ts
packages/amplify-graphql-schema-generator/src/index.ts
packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts
packages/amplify-graphql-schema-generator/src/schema-generator/index.ts
packages/amplify-graphql-schema-generator/src/schema-representation/types.ts

Generate GraphQL schema from schema internal representation data structure.
Temporarily we are reading the DB details from `rds.env` file from the API resource folder. Eventually, we will modify the workflow to prompt from the customer.
Sample rds.env file below:
```json
{
"host": "host.server.com",
"database": "db_name",
"port": 3306,
"username": "username",
"password": "password"
}
```
Running `amplify import api` will import the database schema and convert it to GraphQL schema and store it in `schema.rds.graphql` file.
- manual test
- added unit tests

feat(api): convert rds schema graphql

---

packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/graphql-v2/index-with-stack-mappings.test.ts
packages/amplify-graphql-index-transformer/src/resolvers.ts

Use stack resource manage to get stack to attach index-based resolvers to. Without this change, the StackMapping isn't being respected for these items. Add an e2e test to verify the behavior.
Internal ticket.
Tested manually, and via e2e test which verifies that resolvers are in the correct stack, and that they can still be queried against.
[E2E Test Flow](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/2830/workflows/edad96fd-a3e1-439a-a445-e80c4331817e)

fix: resolvers generated from index respect StackMappings

---

.circleci/config.base.yml
packages/amplify-e2e-core/package.json
packages/amplify-e2e-core/src/index.ts
packages/amplify-migration-tests/package.json
packages/amplify-migration-tests/src/__tests__/migration_tests_v10/scaffold.test.ts
packages/amplify-migration-tests/src/configure_tests.ts
packages/amplify-migration-tests/src/migration-helpers-v10/init.ts
packages/amplify-migration-tests/src/migration-helpers/check-version.ts
scripts/split-e2e-test-filters.ts
scripts/split-e2e-tests.ts
yarn.lock

This adds support for migration testing from v10 to vNext (v11+).
This is done by adding the v10 migration test setup/scaffold & verified with an initial 'scaffold.test.ts' that just installs v10 globally (to .amplify/bin/amplify), and verifies that it works.
This allows us to use the local source code for the latter part of a typical migration test, where we run the amplify commands against the locally installed codebase (located at ~/repo/packages/amplify-cli/bin/amplify).
E2E is running here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api?branch=run-e2e/aluja/add-support-for-migration-tests-v10
This PR is a sibling to this other PR in the CLI repo: https://github.com/aws-amplify/amplify-cli/pull/11535
By submitting this pull request, I confirm that my …

chore: add migration test support for v10

---

packages/amplify-graphql-default-value-transformer/src/__tests__/__snapshots__/amplify-grapphql-default-value-transformer.test.ts.snap
packages/amplify-graphql-default-value-transformer/src/__tests__/amplify-grapphql-default-value-transformer.test.ts
packages/amplify-graphql-default-value-transformer/src/graphql-default-value-transformer.ts

When using the @default directive there is a minor bug where the function to assign the custom default values is not created if your Model name is in lowercase.
```
##doesn't work
type priceApprovalsTemp @model @auth(rules: [
{allow: private, provider: userPools},
{allow: private, provider: iam, operations: [read, create, delete, update]}]) {
id: ID!
oldPrice: Float
newPrice: Float
approvalStatus: String @default(value:"PENDING")
approvedBy: String
name: String @default(value: "Some name")
}     
type PriceApprovalsNew @model @auth(rules: [
{allow: private, provider: userPools},
{allow: private, provider: iam, operations: [read, create, delete, update]}]) {
id: ID!
oldPrice: Float
newPrice: Float
approvalStatus: String @default(value:"PENDING")
approvedBy: String
}   
```
NA
- Manual test …

fix(api): default value for model name start with lowercase

---

packages/amplify-category-api/amplify-plugin.json
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/amplify-meta-utils.test.ts
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/import-rds-utils/globalAmplifyInputs.test.ts
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/rds-secrets/database-secrets.test.ts
packages/amplify-category-api/src/commands/api.ts
packages/amplify-category-api/src/commands/api/generate-schema.ts
packages/amplify-category-api/src/commands/api/import.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthrough-types/import-appsync-api-types.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/generate-graphql-schema-walkthrough.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/import-appsync-api-walkthrough.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/amplify-meta-utils.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/graphql-schema-utils.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/import-rds-utils/globalAmplifyInputs.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-secrets/database-secrets.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-secrets/ssmClient.ts
packages/amplify-graphql-base-default-value-transformer/package.json
packages/amplify-graphql-base-index-transformer/package.json
packages/amplify-graphql-base-model-transformer/package.json
packages/amplify-graphql-rds-default-value-transformer/package.json
packages/amplify-graphql-rds-index-transformer/package.json
packages/amplify-graphql-rds-model-transformer/package.json
packages/amplify-graphql-schema-generator/src/datasource-adapter/mysql-datasource-adapter.ts
packages/graphql-transformer-core/src/util/transformConfig.ts

Initial Draft of the `amplify import api` and `amplify api generate-schema` commands.
The behavior matches the Options A.2 and B.1 discussed in the RFC https://github.com/aws-amplify/amplify-category-api/issues/815.
This covers the most common use-case where the customers want to import the existing MySQL DataSource with or without an already existing API.
**Note:** This PR does not include:
- The multi-database use-cases where a customer wants to import multiple different RDS engine DBs.
- `update-environment-variables` flow that will be added later.

feat: add api import, generate-schema workflows

---

packages/amplify-graphql-index-transformer/src/resolvers.ts

Use node.id instead of `node._actualNode.id` when references table stack. This is important because CDKv2 does not expose `_actualNode`.
N/A
Unit tests pass, and I have an e2e test that will act as a regression test, verifying that the mapped resolver sits in the correct stack.
[E2E Test Run](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/3001/workflows/7a869669-6745-4947-acb4-f39520f33392)

chore: use node.id instead of node._actualNode.id when references table stack

---

.circleci/config.base.yml
.circleci/local_publish_helpers.sh

This PR forces e2e tests to run from source.
The cdk v2 beta line has pinned down category api and transformer packages versions on the cli side, so mechanism that pulls cli and fresh data packages doesn't work as expected.
This should be undone after GA. https://app.asana.com/0/1202389680978480/1203592330499167/f

chore: force e2e tests from source

---

packages/amplify-e2e-core/package.json
packages/amplify-e2e-core/src/utils/index.ts
packages/amplify-e2e-core/src/utils/rds.ts
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/__tests__/rds-v2.test.ts

E2E Core library for RDS tests. This includes the below helpers.
- Create a RDS Instance
- Add external IP of current machine running the test to security group
- Remove the IP from the security group
- Delete a RDS Instance
- A sample test to show how to use the above methods
- E2E Test

test(api): e2e core library for rds tests

---

.github/PULL_REQUEST_TEMPLATE.md

Updating the PR template, example of using this updated template below:
This change adds support for Code-based AppSync resolvers and functions in Amplify.
Relevant docs update: TK
* Conditionally added support for `Code` based AppSync Functions: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html#cfn-appsync-functionconfiguration-code
* Conditionally added support for `Code` based AppSync Resolvers: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html#cfn-appsync-resolver-code
N/A
Unit and e2e tests all pass.

chore: add explicit section for CDK and CFN param changes

---

packages/amplify-category-api/src/__tests__/graphql-transformer/utils.test.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-category-api/src/graphql-transformer/transformer-factory.ts
packages/amplify-graphql-transformer-core/src/config/index.ts
packages/amplify-graphql-transformer-core/src/config/project-config.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-datasource-provider.ts
packages/graphql-transformer-core/src/util/amplifyUtils.ts
packages/graphql-transformer-core/src/util/transformConfig.ts

Introduces model to datasource mapping to transformer context instance. This will help future work to differentiate between DDB vs MySQL for amplify GraphQL transformers.
Once this is merged, we can use the below logic to get database type.
```ts
const dbInfo = context.modelToDatasourceMap.get(modelName);
// If dbInfo doesn't have an entry for the model, then treat it as DDB.
const dbType = dbInfo ? dbInfo.dbType : 'DDB';
// dbType will be DDB or MySQL
```
- Manual test
- No E2E added (should be added as part of transformer changes)

chore(api): add datasource info to transformer context instance

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/resolvers.ts

Add null check to filter argument for index query resolvers. This will make sure that the index query resolver satisfy the resolver security check.
https://github.com/aws-amplify/amplify-category-api/issues/729
- Manual test
- yarn test

fix(graphql): add filter null check to index query resolver

---

packages/amplify-graphql-model-transformer/API.md
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/resolvers/dynamodb/mutation.ts
packages/amplify-graphql-model-transformer/src/resolvers/generator/dynamodb-vtl-generator.ts
packages/amplify-graphql-model-transformer/src/resolvers/generator/rds-vtl-generator.ts
packages/amplify-graphql-model-transformer/src/resolvers/generator/vtl-generator.ts

This PR improves the typing for the VTL generator methods' arguments as per this [discussion](https://github.com/aws-amplify/amplify-category-api/pull/1188#discussion_r1087322819).
- (Type safety) Adds config types which are strongly typed for the respective operation.

chore(graphql): improve typing on vtl generator methods

---

packages/amplify-schema-validator/src/__tests__/schemas/schema-with-nonnulltype.graphql
packages/amplify-schema-validator/src/__tests__/utils/resolve-field-type-name.test.ts
packages/amplify-schema-validator/src/__tests__/validates-schemas-with-nonnulltype.test.ts
packages/amplify-schema-validator/src/helpers/resolve-field-type-name.ts
packages/amplify-schema-validator/src/validators/relation-required-with-belongs-to.ts

This PR adds a fix to the @aws-amplify/graphql-schema-validation package to support nested schemas
N/A
Unit tests added

fix: update belongs to relation required logic to handle nested schemas

---

packages/amplify-category-api/src/commands/api/update-secrets.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/mysql-datasource-adapter.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts

There are broadly 2 types of Default values that could be specified in MySQL customer's DDL:
- **Literal constants:** These are straight forward constant defaults for scalar types. The fields with these defaults are generated as optionals and `@default` directive is attached to them.
- **Computed values:** These are constructed using built-in scalar functions and are computed by the database. The current `@default` directive does not support this. The fields with these defaults are however still generated as optionals but without the `@default` directive.
[Refer MySQL docs for more info](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html)

feat: RDS generate schema handles default values

---

packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/mysql-datasource-adapter.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/datasource-adapter/datasource-adapter.ts
packages/amplify-graphql-schema-generator/src/datasource-adapter/mysql-datasource-adapter.ts
packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts
packages/amplify-graphql-schema-generator/src/schema-representation/types.ts

Infer Enum field types from MySQL table and creates a GraphQL schema.
For example: The below SQL table should generate the GraphQL schema as shown.
```sql
/* Create Table Script */ 
CREATE TABLE `Person` (
`id` varchar(40) default (uuid()) not null primary key,
`firstName` varchar(50),
`profile_type` ENUM('EMPLOYEE', 'MANAGER')
)
```
```graphql
enum Person_profile_type {
EMPLOYEE
MANAGER
}
type Person @model {
id: String! @default(value: "uuid()") @primaryKey
firstName: String
profile_type: Person_profile_type
}
```
- yarn test
- manual test

feat(graphql): infer enums from database schema

---

packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/schemas/simple_two_models.graphql
packages/amplify-e2e-tests/src/__tests__/graphql-v2/lambda-conflict-handler.test.ts
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts

Fix the bug that per model conflict resolution is not respected
The `SyncConfig` is now correctly generated based on per model rule.
Fix https://github.com/aws-amplify/amplify-category-api/issues/1192

fix(transformer): conflict detection respects to per model rule

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/graphql-primary-key-transformer.ts
packages/amplify-graphql-index-transformer/src/resolvers/generators/dynamodb-vtl-generator.ts
packages/amplify-graphql-index-transformer/src/resolvers/generators/rds-vtl-generator.ts
packages/amplify-graphql-index-transformer/src/resolvers/generators/vtl-generator.ts
packages/amplify-graphql-index-transformer/src/resolvers/resolvers.ts

Adds @index directive support for RDS datasource. Import workflow detects the indexes and adds @index on the field. 
- Customer can edit a generated index and add a queryField attribute which will create a GraphQL query with the given name.

feat(graphql): add index directive support for rds datasource

---

packages/amplify-graphql-model-transformer/rds-lambda/clients/mysql/MySQLClient.ts
packages/amplify-graphql-model-transformer/src/resolvers/generators/rds-vtl-generator.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/index.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/query.ts
packages/amplify-graphql-schema-generator/src/datasource-adapter/mysql-datasource-adapter.ts

Fix for timestamp fields in mysql, map correctly to AWSDateTime in AppSync
Fixes issues with the input signature matching when calling list on lambda
Also updates field mapping for generating schema from RDS so MySQL timestamp is correctly mapped to AWSDateTime scalar type

Get LIST operations working RDS

---

client-test-apps/js/api-model-relationship-app/package.json

Fix the failing canary tests in main branch.
The failures are caused by the 'joi' dependency. It is addressed here by resolving it to a specific version.

fix(test): canary joi package version issue

---

.circleci/config.base.yml
.circleci/config.yml
package.json

CLI 10.7.2 and 10.7.3 are based off API tagged release and using them for E2E testing causing version conflict on the tests. With this change, we lock the CLI version to 10.7.1.
```
? Select the plugin module to execute …  (Use arrow keys or type to filter)
❯ @aws-amplify/amplify-category-api@4.1.9-alhotpatchfeb.0
@aws-amplify/amplify-category-api@4.1.8
```

test(api): use 10.7.1 for e2e tests

---

package.json
packages/amplify-graphql-function-transformer/src/__tests__/__snapshots__/amplify-graphql-function-transformer-override.test.ts.snap
packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer-override.test.ts
packages/amplify-graphql-http-transformer/src/__tests__/__snapshots__/amplify-graphql-http-transformer-override.test.ts.snap
packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer-override.test.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer-override.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer-override.test.ts
packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer-override.test.ts.snap
packages/amplify-graphql-predictions-transformer/src/__tests__/amplify-graphql-predictions-transformer-override.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts

Fixes error that happens on pull.
This was introduced by not swallowing error in previous change. However this scenario has been missed.
Main vs CDKv2 branch:
E2E run with this PR + version bump https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/4417/workflows/e2970acc-4cd8-4a9b-ad69-94eaca6ad167 .
The failing `client_e2e_tests` also fail on main due to 3rd party libraries dependency problem.

fix: error in transformers if override has never been setup

---

packages/amplify-category-api/src/provider-utils/supported-datasources.ts
packages/amplify-e2e-core/src/configure/index.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/graphql-elasticsearch-transformer/src/resources.ts

This PR enables support in eu-south-1 region (MXP). Associated with https://github.com/aws-amplify/amplify-cli/pull/12042
N/A
N/A
I've created a tagged release of both `amplify-category-api` with https://github.com/aws-amplify/amplify-category-api/pull/1273 and `amplify-cli` including https://github.com/aws-amplify/amplify-cli/pull/12042.
The eu-south-1 CLI can be installed via 
```
npm i -g @aws-amplify/cli@10.8.0-mxp.0
```
I then set eu-south-1 in my `~/.aws/config` for my amplify profile.
First, to test amplify-cli, I ran:
```
amplify init
amplify add auth
amplify add storage
amplify push
```
accepting all default values.
Then, to test `amplify-category-api`, I ran `amplify add api && amplify push`.
It all works and the expected resources / CFN stacks appear in my AWS account in …

add support for eu-south-1 MXP

---

client-test-apps/js/api-model-relationship-app/src/__tests__/utils/testHarness.ts

Extend the timeout for setup local host to 5 mins
Cloud e2e job passed https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/4643/workflows/ebcf9d7c-e23e-4fbe-8058-47f37469d4b8/jobs/90960/steps

fix(canary): add longer timeout for local server

---

package.json

This adds `--conventional-graduate` to release step.
So that `5.1.0-beta.6`  becomes  `5.1.0` (instead of `5.1.0-beta.7`)
FWIW that flag is used in CLI https://github.com/aws-amplify/amplify-cli/blob/4490c7e24060d68568ce36813c51b2a98465953c/.circleci/publish.sh#L61
Tested locally by replicating command from publish:release
**WITH CHANGE**
**WITHOUT CHANGE**

chore: add conventional-graduate to publish release

---

.circleci/config.base.yml

Building on windows is currently blocking the test jobs that run on linux making the development cycle longer.
This change uncouples windows build job but retains the dependency of `deploy` on it.
Link to updated workflow: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/4870/workflows/76d66a9d-601a-4ac8-91dd-44cc53c13a1f

Separate windows build job to unblock linux based tests

---

packages/amplify-category-api/src/provider-utils/awscloudformation/pipeline-with-awaiter.ts

Correct the policy for downloading ECR image used by codebuild for container enabled API. This removes the incorrect one `BatchGetDownloadUrlForLayer` and adds the correct one `GetDownloadUrlForLayer`.
Fixes https://github.com/aws-amplify/amplify-category-api/issues/1255
- Manual test

fix(api): correct container code build policy

---

.circleci/config.base.yml
.circleci/local_publish_helpers.sh

Removes the workaround that was forcing e2e tests to run from source.
E2E test run https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/4978/workflows/578d2b2b-9451-45ec-a1b5-daab99d01049 .
There's one test that's failing consistently also on main branch. Not related to the change.

chore: remove force from source run after CLI v11 release

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/ecs-alb-stack.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-transformer-core/src/appsync-function.ts
packages/amplify-graphql-transformer-core/src/graphql-api.ts

CDK method 'addDependsOn' is deprecated. This PR changes 'addDependsOn' method calls to 'addDependency'. 
NA
- Manual test

chore(api): change addDependsOn to addDependency

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/owner-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithAuthV2.e2e.test.ts

This PR checks if the group claim is an array or string before evaluation for `@index` queries. This is something we already do for mutations and get & list queries. This PR applies the same logic to `@index` queries on `groupsField`.
NA
Fixes https://github.com/aws-amplify/amplify-category-api/issues/857, https://github.com/aws-amplify/amplify-category-api/issues/468
- Manual test
- E2E test

fix(graphql): evaluate group claim - string vs array behavior

---

packages/amplify-category-api/API.md
packages/amplify-category-api/src/__tests__/category-utils/show-auth-acm.test.ts
packages/amplify-category-api/src/category-utils/show-auth-acm.ts
packages/amplify-category-api/src/index.ts

Move https://github.com/aws-amplify/amplify-cli/blob/d0e60d149d1720bced15ec96c03bce22aade9d20/packages/amplify-cli/src/commands/status.ts#L50-L102 and https://github.com/aws-amplify/amplify-cli/blob/d0e60d149d1720bced15ec96c03bce22aade9d20/packages/amplify-cli/src/extensions/amplify-helpers/show-auth-acm.ts files/functions/tests over to the API category so CLI doesn't depend on transformers directly.
N/A
N/A
Unit tests pass, will validate in CLI refactor that things are working e2e.

chore: copy show-auth-acm and showApiAuthAcm from CLI core package

---

packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer-override.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-relations-with-custom-primary-key.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-relations-with-custom-primary-key.test.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/graphql-transformers-e2e-tests/src/__tests__/RelationalWithOwnerFieldAsKeySchemaAuth.e2e.test.ts
yarn.lock

Use `stash` instead of `source` for owner auth resolver when the owner field of related model is part of the key schema. The connection fields will be put into `$ctx.stash.connectionAttributes` in auth resolver and consumed by the latter data resolver.
Fix https://github.com/aws-amplify/amplify-category-api/issues/1383
Unit & e2e tests
Team Bug bash

fix(auth): ownerfield as pk in relational models

---

packages/amplify-schema-validator/src/__tests__/schemas/invalid-use-belongsto-when-datastore-inuse.graphql
packages/amplify-schema-validator/src/__tests__/schemas/invalid-use-directives-from-newer-transformer-version.graphql
packages/amplify-schema-validator/src/__tests__/schemas/invalid-use-directives-from-older-transformer-version.graphql
packages/amplify-schema-validator/src/__tests__/validates-use-belongsto-when-datastore-inuse.test.ts
packages/amplify-schema-validator/src/__tests__/validates-use-directives-from-newer-transformer-version.test.ts
packages/amplify-schema-validator/src/__tests__/validates-use-directives-from-older-transformer-version.test.ts
packages/amplify-schema-validator/src/helpers/schema-validator-props.ts
packages/amplify-schema-validator/src/helpers/transformer-validation.ts
packages/amplify-schema-validator/src/index.ts
packages/amplify-schema-validator/src/validators/auth-must-be-annotated-with-model.ts
packages/amplify-schema-validator/src/validators/belongs-to-fields-match-related-type-primary-key.ts
packages/amplify-schema-validator/src/validators/correct-type-in-many-to-many-relation.ts
packages/amplify-schema-validator/src/validators/enum-is-defined-once.ts
packages/amplify-schema-validator/src/validators/field-is-defined-once.ts
packages/amplify-schema-validator/src/validators/fields-match-in-parent-model.ts
packages/amplify-schema-validator/src/validators/index-exists-in-related-model.ts
packages/amplify-schema-validator/src/validators/index-is-defined-once-in-model.ts
packages/amplify-schema-validator/src/validators/index-scalar-types.ts
packages/amplify-schema-validator/src/validators/key-exists-in-related-model.ts
packages/amplify-schema-validator/src/validators/relation-required-with-belongs-to.ts
packages/amplify-schema-validator/src/validators/relationname-doesnot-conflict-with-typename.ts
packages/amplify-schema-validator/src/validators/reserved-field-name.ts
packages/amplify-schema-validator/src/validators/reserved-type-name.ts
packages/amplify-schema-validator/src/validators/sort-key-field-exists.ts
packages/amplify-schema-validator/src/validators/two-many-to-many-locations.ts
packages/amplify-schema-validator/src/validators/type-is-defined-once.ts
packages/amplify-schema-validator/src/validators/use-belongsto-when-datastore-inuse.ts
packages/amplify-schema-validator/src/validators/use-directives-from-newer-transformer-version.ts
packages/amplify-schema-validator/src/validators/use-directives-from-older-transformer-version.ts

This PR adds below mentioned schema validations:
1) XX and YY cannot refer to each other via @hasOne or @hasMany when DataStore is in use. Use @belongsTo instead
2) Schema should not use directives from an older version of the GraphQL Transformer when the version used is 2.
3) Schema should not use directives from a newer version of the GraphQL Transformer when the version used is 1.
Nona
N/A
Added unit tests

Schema validations

---

packages/amplify-category-api/API.md
packages/amplify-category-api/package.json
packages/amplify-category-api/src/__tests__/category-utils/is-datastore-enabled.test.ts
packages/amplify-category-api/src/category-utils/is-datastore-enabled.ts
packages/amplify-category-api/src/index.ts
yarn.lock

Expose a utility method from the API Category to proxy calls to `isDataStoreEnabled` in the `graphql-transformer-core` package given just the context object.
N/A
N/A
Added some unit tests.

feature: expose isDataStoreEnabled utility given amplify context

---

packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-types/common.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/schema.ts
yarn.lock

Added `_deleted` field to the generated `ModelXXXFilterInput` so people can query the API without the deleted items, for example.
None.
Implemented #78.
I noticed that people are actively asking in the thread to implement the feature, but wasn't sure why it hasn't been implemented yet.
If there's a special reason or an intentional decision not to implement it (or not do it that way), please let me know.
1. Created an example `Todo` model that has the list/sync query, pushed it and made sure the filter applies in the AppSync console
2. Created the `Todo` model without sync or list, but connected it to another model (`ListOfTodos`) with an `@hasMany` directive. Pushed and made sure the query for `Todo`s through `ListOfTodos` has this field and that it's working.
By submitting this pull …

feat(datastore-filters): add filters for DataStore _deleted property

---

package.json

Update `add-cli-no-save` NPM script to not update `yarn.lock` file.
N/A
N/A
`yarn setup-dev`

build: don't update lockfile on cli add in yarn setup-dev

---

package.json
yarn.lock

Upgrade eslint to be compatible with the installed version of typescript. Eliminates the following warning when running eslint.
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
YOUR TYPESCRIPT VERSION: 4.9.5
Please only submit bug reports when using the officially supported version.
=============
```
N/A
N/A
Run local eslint install on some file.
`npx eslint packages/amplify-graphql-transformer-core/src/transformation/transform.ts`

style: upgrade eslint

---

packages/amplify-e2e-tests/src/__tests__/graphql-v2/sync_query_datastore.test.ts
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/resolvers/resolvers.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/resolvers/dynamodb/query.ts

Currently Sync operation is scanning the table several times when a model has a custom primary key or GSI (2 preAuth slots and 1 data resolver slot). This change is intended to fix this behavior.
Going forward, the `preAuth` slot will run against NONE_DS instead of the DDB table datasource. `PreAuth` slot will only construct the DDB query (place it on `$ctx.stash.QueryRequest`) and the data resolver will determine whether to use the query or perform a table scan. 
With this PR, sync operation will,
- Use query if sync filter is on a GSI/table's partition key (partition key and sort key(s) aren't auth field).
- Use query if sync filter is on a partition key and it matches with one of the auto generated auth filter. 
In all other cases, table will be scanned once.
Fixes …

fix(api): use scan and query correctly on sync operation

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/group-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/owner-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithAuthV2WithFF.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithClaimFieldAsSortKeyAuth.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithOwnerFieldAsSortKeyAuth.e2e.test.ts

- Pass the key schema infos when generating auth expressions
- Add owner/group auth field with `eq` when it is part of index sort key and missing in the args input
- When the field is missing in input, it will retrieve the last item of claim list by default
- Add unit/e2e tests
Unit & e2e tests
AppSync Console testing

fix(auth): owner & group field as sort key field of GSI

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/containers-walkthrough.ts

Fixed container resource name input validation pattern to allow only alphanumeric with no uppercase letters.
#1489
- Unit Testing (yarn test)
- Manual Testing
- amplify-dev api add
```
amplify-dev add api    
? Select from one of the below mentioned services: REST
? Which service would you like to use API Gateway + AWS Fargate (Container-based)
? Provide a friendly name for your resource to be used as a label for this category in the project: test-container
>> Resource name should be alphanumeric with no uppercase letters
```

fix: container resource name input validation pattern

---

.circleci/config.yml

use node18 instead of default image for all pipelines - this should address canary/e2e-resource-cleanup failures like [this failing canary run](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/6584/workflows/a977d4b9-e9b8-448d-aaa7-4eef0bb67ffb/jobs/129925)
N/A
N/A
Running workflows from this branch:
* [Canary](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/6602/workflows/6b895792-4af2-45f6-8aa8-f1ca896dae24)
* [E2E Resource Cleanup](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/6603/workflows/972f8cc2-a991-4dae-bae2-40f718864942)

fix: use node18 instead of default image for all pipelines

---

depcheck.config.js
package.json

Adding depcheck step to post-commit hook. This is intended to validate we don't reintroduce key dependencies into the GQLV2 dependency chain. There are other ways to do this, but this was just something we can add ASAP while we're touching the deps.
N/A
N/A
Test-committed file w/ `fs` as an import.

chore: adding depcheck step to post-commit hook

---

packages/amplify-graphql-transformer-core/src/cdk-compat/template-asset.ts

The `fromFile` static method does not appear to be used anywhere in project. Removing it.
N/A - explicitly.
I have touched some of the core resource generation code, though I don't anticipate any impact here.
N/A

chore: remove fs access from template asset construction

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/auth-operations.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/auth-operations.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/utils/warnings.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/schema.ts
packages/amplify-graphql-model-transformer/src/resources/model-resource-generator.ts

While renaming subscriptions, transformers do not generate auth resolvers for the operation. This PR fixes the issue.
**For example:** For the below schema, currently no auth resolvers are generated for `onNoteUpdate` subscription.
```graphql
type Note 
@model(subscriptions: { onUpdate: ["onNoteUpdate"] }) 
@auth(rules: [{ allow: owner }]) 
{
noteId: String! @primaryKey
comments: String
}
```
NA
Internal ticket

fix(graphql): renamed subscription should generate auth resolver

---

packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-schema-test-library/src/__tests__/index.test.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-filepaths-provider.ts

Remove the now-unused `filepaths` object from the v2 transformer context, and no longer pass down to the client.
N/A
N/A

chore: remove filepaths from context

---

packages/amplify-category-api/src/amplify-graphql-transform/graphql-transformer-v2.ts
packages/amplify-category-api/src/graphql-transformer/directive-definitions.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-category-api/src/graphql-transformer/transformer-factory.ts
packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts

Create a top-level transform package for the v2 transformer chain to simplify invocation from the API Category, and simplify invocation of the transform/preprocessing system from multiple clients.
~~Step 1. break apart the v1/v2 logic a bit, and moving the chain generation into a separate file (which will eventually be pulled into it's own package).~~ Merged in https://github.com/aws-amplify/amplify-category-api/pull/1528
Step 2. Consolidate all input param generation into a single place for the v2 transformer, and migrate `GraphQLTransform` construction into a single place, with a tight interface (today is overly permissive, and leaks in significant amplify cli and deploy concerns). Under review in https://github.com/aws-amplify/amplify-category-api/pull/1548
__(Current Step) Step 3. …

GraphQL Refactor Step 3 - Refactor Transform Invocation into Separate Package

---

packages/amplify-category-api/src/__tests__/graphql-transformer/transformer-options-v2.test.ts
packages/amplify-category-api/src/graphql-transformer/transformer-options-types.ts
packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/__tests__/transformation/transform.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer/API.md
packages/amplify-graphql-transformer/src/graphql-transformer.ts

Move number to param coercion into the API Category layer for a legacy flag we're passing into the transformer.
N/A
N/A

chore: refactor so legacyApiKey flag is a boolean in-transformer, not a number

---

packages/amplify-category-api/package.json
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-default-value-transformer/package.json
packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-index-transformer/package.json
packages/amplify-graphql-maps-to-transformer/package.json
packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-predictions-transformer/package.json
packages/amplify-graphql-relational-transformer/package.json
packages/amplify-graphql-schema-generator/package.json
packages/amplify-graphql-searchable-transformer/package.json
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-migrator/package.json
packages/amplify-graphql-transformer/package.json
packages/graphql-auth-transformer/package.json
packages/graphql-connection-transformer/package.json
packages/graphql-dynamodb-transformer/package.json
packages/graphql-elasticsearch-transformer/package.json
packages/graphql-function-transformer/package.json
packages/graphql-http-transformer/package.json
packages/graphql-key-transformer/package.json
packages/graphql-mapping-template/package.json
packages/graphql-predictions-transformer/package.json
packages/graphql-relational-schema-transformer/package.json
packages/graphql-transformer-common/package.json
packages/graphql-transformer-core/package.json
packages/graphql-versioned-transformer/package.json

Add unit test coverage thresholds (currently set to `min(curr_val, 80)`) to prevent reduction in unit test coverage.
Info on the coverage configuration can be found here https://jestjs.io/docs/27.x/configuration#coveragethreshold-object
Line coverage refers to what % of lines are covered in the given package (in average across all files, since we're using global)
Branch coverage refers to what % of code paths are covered in the given package (in average across all files, since we're using global)
Function coverage refers to what % of functions are covered in the given package (in average across all files, since we're using global)
N/A
N/A
Unit tests

chore: add minimum unit test threshold

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/import-rds-utils/__snapshots__/globalAmplifyInputs.test.ts.snap
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/import-rds-utils/globalAmplifyInputs.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-input-utils.ts
packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts
packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-model-transformer/publish-notification-lambda/.gitignore
packages/amplify-graphql-model-transformer/publish-notification-lambda/README.md
packages/amplify-graphql-model-transformer/publish-notification-lambda/package.json
packages/amplify-graphql-model-transformer/publish-notification-lambda/src/index.ts
packages/amplify-graphql-model-transformer/publish-notification-lambda/tsconfig.json
packages/amplify-graphql-model-transformer/rds-patching-lambda/.gitignore
packages/amplify-graphql-model-transformer/rds-patching-lambda/package.json
packages/amplify-graphql-model-transformer/rds-patching-lambda/src/index.ts
packages/amplify-graphql-model-transformer/rds-patching-lambda/tsconfig.json
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/amplify-graphql-model-transformer/src/resources/rds-model-resource-generator.ts
packages/graphql-transformer-common/API.md
packages/graphql-transformer-common/src/ResourceConstants.ts
packages/graphql-transformer-core/API.md
packages/graphql-transformer-core/src/util/transformConfig.ts

- Adds patching mechanism for SQL lambda.
- Modifies RDS lambda runtime from Node 16.x to 18.x.
- Fixes a bug related to `input AMPLIFY` object. Now there is no need to have schema.graphql file to enable sandbox mode.
NA
NA
- Manual test
- E2E tests updated

feat(graphql): patching rds lambda layer

---

packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-api-construct/src/__tests__/__functional__/basic.test.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/predictions.test.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/props.test.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/relationships.test.ts
packages/amplify-graphql-api-construct/src/__tests__/internal/conflict-resolution.test.ts
packages/amplify-graphql-api-construct/src/__tests__/internal/user-defined-slots.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/index.ts
packages/amplify-graphql-api-construct/src/internal/conflict-resolution.ts
packages/amplify-graphql-api-construct/src/internal/index.ts
packages/amplify-graphql-api-construct/src/internal/user-defined-slots.ts
packages/amplify-graphql-api-construct/src/types.ts

Addressing a few bugs and asks in the proposed interface from testing.
1. Fix predictionsConfig wiring, and add a test to verify it synthesizes.
2. Fix functionSlot `setIn` function, which had a bad condition in it, added tests for that.
3. Add comments to remaining types.
4. Rename `ResolverConfig` to `conflictResolution`, and take types internal so customers don't need to import from transformer packages.
5. Bump unit test coverage numbers for added tests.
6. Update API Extract to reflect these changes.
N/A
N/A
Unit tests pass.

fix: adding tests, and fixing some bugs, updating api a bit

---

packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts

Replace usage of deprecated `addDependsOn` with `addDependency`.
This should not result in changing CDK, since it's a replacement method for addDependsOn.
N/A - getting build and test warnings.

fix: use addDependency instead of addDependsOn

---

packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-api-construct/src/__tests__/__functional__/auth-modes.test.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/props.test.ts
packages/amplify-graphql-api-construct/src/__tests__/amplify-graphql-api.test.ts
packages/amplify-graphql-api-construct/src/__tests__/internal/conflict-resolution.test.ts
packages/amplify-graphql-api-construct/src/__tests__/internal/user-defined-slots.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/index.ts
packages/amplify-graphql-api-construct/src/internal/authorization-modes.ts
packages/amplify-graphql-api-construct/src/internal/conflict-resolution.ts
packages/amplify-graphql-api-construct/src/internal/construct-exports.ts
packages/amplify-graphql-api-construct/src/internal/user-defined-slots.ts
packages/amplify-graphql-api-construct/src/types.ts

Updating types per conversations w/ a few folks, and feedback so far, but hopefully this is close to what we expect the final types to look like (though I expect some minor feedback and updates during alpha/beta testing).
Updates in this PR.
* No longer return a `Record<String, T> `, since the keys of that record are contextual, and not necessarily obvious to users. Instead, return a `T[]` so they can perform simple list comprehensions, filters, etc. to pull out the value they wish based on arbitrary values in the key (there is no data/context loss with this reshape).
* Expose a `referencedFunctions` object, which is intended to provide an affordance to name CDK generated (and named) functions, and eliminate the current amplify idiom of searching for a function by `name` in the …

chore: updating types to what we expect for alpha scope

---

packages/amplify-graphql-model-transformer/rds-patching-lambda/src/index.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts

- Adds delay to the RDS patching lambda to avoid throttling issues.
- Updates layer version to the latest.
NA
NA
- Manual test

fix(api): add delay to rds patching

---

package.json
packages/amplify-category-api/package.json
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-index-transformer/package.json
packages/amplify-graphql-maps-to-transformer/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-predictions-transformer/package.json
packages/amplify-graphql-relational-transformer/package.json
packages/amplify-graphql-searchable-transformer/package.json
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-interfaces/package.json
packages/amplify-migration-tests/package.json
packages/graphql-transformers-e2e-tests/resources/jsonServer/package.json
yarn.lock

Using peer deps for transformer CDK version, and bumping amplify plugin and library versions to use 2.80. This will need to be run through e2e tests to verify behavior.
Using a new CDK version, but no CDK code or config has changed.
This takes us through the following CDK releases:
* https://github.com/aws/aws-cdk/releases/tag/v2.80.0
* https://github.com/aws/aws-cdk/releases/tag/v2.79.1
* https://github.com/aws/aws-cdk/releases/tag/v2.79.0
* https://github.com/aws/aws-cdk/releases/tag/v2.78.0
* https://github.com/aws/aws-cdk/releases/tag/v2.77.0
* https://github.com/aws/aws-cdk/releases/tag/v2.76.0
* https://github.com/aws/aws-cdk/releases/tag/v2.75.1
* https://github.com/aws/aws-cdk/releases/tag/v2.75.0
* https://github.com/aws/aws-cdk/releases/tag/v2.74.0
* …

chore: use peer deps for cdk and constructs, and update in amplify packages

---

packages/amplify-e2e-tests/src/__tests__/datastore-modelgen.test.ts

The error is not rejected in codebuild but in CircleCI in modelgen test. The PR is to fix this issue.
The `unknown type` error are both thrown if I check both the artifacts from CCI and CodeBuild. Also the error stack trace is same. However, the codebuild does not reject the promise.  The only difference is that the error of `amplify-meta.json` not existing is displayed in different colors(red in CCI and white in CodeBuild)
- In CCI:
The output is too quick to get a screenshot. Attach the link for reference
https://output.circle-artifacts.com/output/job/1e954839-8ff8-44f8-a7ec-7a5830836d2b/artifacts/0/packages/amplify-e2e-tests/amplify-e2e-reports/index.html
- In CodeBuild:

fix: modelgen test promise issue

---

.eslintrc.js
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-default-value-transformer/src/validators.ts
packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnOutput.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/amplify-graphql-transformer-core/src/__tests__/transformation/transform.test.ts
packages/amplify-graphql-transformer-core/src/__tests__/transformation/utils.test.ts
packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformation/utils.ts

Turning off `no-new` eslint rule, since our CDK usage will cause this to break all over. Also ensuring the core `transformer` file passes all eslint rules to make it easier to work on over the next few changes.
N/A
N/A
Unit tests

chore: update lint rules, and catch up transform so it passes

---

.circleci/config.base.yml
packages/amplify-graphql-api-construct/package.json

* Remove `private` flag on `package.json` for the new CDK construct to publish in an alpha state.
* Revert manual changes in tests required to get private package publishing to verdaccio correctly.
N/A
N/A
Unit + E2E Tests, passing CDK test https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/7943/workflows/463edcdb-ede6-43c8-9167-8cb3fdd9ce70/jobs/162669

feat: release alpha cdk construct

---

packages/amplify-category-api/src/index.ts
packages/amplify-graphql-api-construct/src/index.ts
packages/amplify-graphql-auth-transformer/src/index.ts
packages/amplify-graphql-default-value-transformer/src/index.ts
packages/amplify-graphql-function-transformer/src/index.ts
packages/amplify-graphql-http-transformer/src/index.ts
packages/amplify-graphql-index-transformer/src/index.ts
packages/amplify-graphql-maps-to-transformer/src/index.ts
packages/amplify-graphql-model-transformer/src/index.ts
packages/amplify-graphql-predictions-transformer/src/index.ts
packages/amplify-graphql-relational-transformer/src/index.ts
packages/amplify-graphql-schema-generator/src/index.ts
packages/amplify-graphql-schema-test-library/src/index.ts
packages/amplify-graphql-searchable-transformer/src/index.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-migrator/src/index.ts
packages/amplify-graphql-transformer/src/index.ts
packages/graphql-auth-transformer/src/index.ts
packages/graphql-connection-transformer/src/index.ts
packages/graphql-dynamodb-transformer/src/index.ts
packages/graphql-elasticsearch-transformer/src/index.ts
packages/graphql-function-transformer/src/index.ts
packages/graphql-http-transformer/src/index.ts
packages/graphql-key-transformer/src/index.ts
packages/graphql-predictions-transformer/src/index.ts
packages/graphql-transformer-core/src/index.ts
packages/graphql-versioned-transformer/src/index.ts

Trigger republish of the following packages:
```
Changes:
- @aws-amplify/amplify-category-api: 5.4.3 => 5.4.4
- amplify-category-api-e2e-core: 4.1.6 => 4.1.7 (private)
- amplify-category-api-e2e-tests: 3.12.6 => 3.12.7 (private)
- @aws-amplify/graphql-construct-alpha: 0.2.0 => 0.3.0
- @aws-amplify/graphql-auth-transformer: 2.1.8 => 2.1.9
- @aws-amplify/graphql-default-value-transformer: 1.1.8 => 1.1.9
- @aws-amplify/graphql-function-transformer: 1.2.6 => 1.2.7
- @aws-amplify/graphql-http-transformer: 1.2.6 => 1.2.7
- @aws-amplify/graphql-index-transformer: 1.2.4 => 1.2.5
- @aws-amplify/graphql-maps-to-transformer: 2.1.8 => 2.1.9
- amplify-category-api-graphql-migration-tests: 2.3.37 => 2.3.38 (private)
- @aws-amplify/graphql-model-transformer: 1.3.4 => 1.3.5
- …
```

release update

---

shared-scripts.sh

Synchronizing Codebuild config w/ CircleCI config
N/A
E2E tests on codebuild are failing
https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:382a21c7-ff3d-4c9f-94c3-5523095f243a?region=us-east-1

fix: use tagged release for e2e tests for codebuild

---

packages/amplify-category-api/package.json
scripts/cloud-utils.sh

Use Peer dep for api category to ensure we're more easily aligned w/ the CLI moving forward. Related PR in CLI https://github.com/aws-amplify/amplify-cli/pull/12937
N/A
N/A
Unit + E2E tests

chore: use peer deps for api category for cdk and constructs

---

shared-scripts.sh

Fixed the issue of the branch not being checkout in the `publishToLocalRegistry` when the build is triggered with webhook

fix: publish issue with webhook trigger

---

packages/amplify-category-api/src/graphql-transformer/override.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/index.ts
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
packages/amplify-graphql-index-transformer/src/resolvers/resolvers.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
packages/amplify-graphql-model-transformer/src/resources/model-resource-generator.ts
packages/amplify-graphql-model-transformer/src/resources/rds-model-resource-generator.ts
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnParameters.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-datasource.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/__tests__/transformation/transform.test.ts
packages/amplify-graphql-transformer-core/src/transform-host.ts
packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-graphql-transformer-core/src/transformer-context/stack-manager.ts
packages/amplify-graphql-transformer-core/src/utils/authType.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transform-host-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/stack-manager-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-resolver-provider.ts

This change is a precursor to a refactor of the internal stack manager, where we'll no longer always pass stacks around, but instead could deal w/ arbitrary scopes.
This is to decouple and shrink the changes in a PR such as this https://github.com/aws-amplify/amplify-category-api/pull/1699
N/A
N/A

chore: pass constructs around instead of stacks

---

.prettierignore

* add vpc-db-lambda/lib and rds-patching-lambda/lib to prettier ignore
Some lib dirs are missing from the prettier ignore causing lint step to fail on CB.
N/A
N/A
`yarn prettier-check`.

build: add vpc-db-lambda/lib and rds-patching-lambda/lib to prettier ignore

---

codebuild_specs/e2e_workflow.yml
packages/amplify-category-api/src/graphql-transformer/override.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts

For API Category, ensure before we `require` a file for overrides, we clean the require cache. This caused some issues in CLI if a customer used the unbundled CLI, so addressing here as well until we can migrate to user their utility.
N/A
Related to VM2 removal.
Manually verified via `setup-dev` that I could deploy an app, add overrides, and change the overrides (and changes took effect).

chore: clean require cache before executing overrides

---

packages/amplify-category-api/amplify-plugin.json
packages/amplify-category-api/src/commands/api.ts
packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-model-v2.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-v2.test.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts
packages/amplify-graphql-transformer-core/src/wrappers/object-definition-wrapper.ts

Currently, if a model has primary key field 'id' of type 'Int', amplify generates the CreateModelInput type with optional id field which results in assigning autogenerated uuid (string) to an integer field. This results in error in DDB and id field evaluate to MAX_INT value in RDS. To avoid the problem, making the field as mandatory if the type is not ID/String.
This PR also adds back the RDS commands and RDS E2E tests back.
NA
NA
- Manual test
- Unit test

fix(api): make id optional if not a string type

---

codebuild_specs/e2e_workflow.yml
package.json
scripts/package.json
scripts/view-test-artifacts.ts
scripts/yarn.lock

Add a utility to make it easier to look at multiple failing test artifacts in parallel.
N/A
N/A
Verified locally.

feat: support view-test-artifacts rather than a single artifact

---

packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/__tests__/transformation/sync-utils.test.ts
packages/amplify-graphql-transformer-core/src/__tests__/transformation/transform.test.ts
packages/amplify-graphql-transformer-core/src/__tests__/transformer-context/resource-helper.test.ts
packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resource-helper.ts
packages/amplify-graphql-transformer-core/src/transformer-context/stack-manager.ts
packages/amplify-graphql-transformer-core/src/utils/authType.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/parameter-manager.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/stack-manager-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/amplify-graphql-transformer-test-utils/src/cdk-compat/transform-manager.ts
packages/amplify-graphql-transformer-test-utils/src/test-transform.ts
packages/amplify-graphql-transformer/src/cdk-compat/transform-manager.ts
packages/amplify-graphql-transformer/src/graphql-transformer.ts

Refactor the `parameterManager` into a standalone component, and out of the `stackManager` component. This is to facilitate creating code-based parameters for the CDK construct (since we don't want to actually invoke or add new parameters to the top-level CDK managed stack on customer behalf).
This does not add the new behavior yet, simply a refactor of the existing system.
N/A
N/A
Unit tests

param store refactor

---

packages/amplify-category-api/src/provider-utils/supported-datasources.ts
packages/amplify-e2e-core/src/configure/index.ts

This PR enables support in ap-northeast-3 region (KIX)
N/A
Associated CLI PR: https://github.com/aws-amplify/amplify-cli/pull/13039
I set ap-northeast-3 in my ~/.aws/config for my amplify profile and created an app.
I ran: 
amplify-dev init
amplify-dev add api (default graphQL options)
amplify-dev push
Confirmed that an API was successfully deployed to my account in ap-northeast-3 region

chore: 🤖 add support for ap-northeast-3 KIX

---

packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/src/index.ts
packages/amplify-graphql-api-construct/src/types.ts
packages/amplify-graphql-maps-to-transformer/src/field-mapping-lambda.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/__tests__/utils/resource-name.test.ts
packages/amplify-graphql-transformer-core/src/appsync-function.ts
packages/amplify-graphql-transformer-core/src/graphql-api.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/transform-host.ts
packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
packages/amplify-graphql-transformer-core/src/utils/index.ts
packages/amplify-graphql-transformer-core/src/utils/resource-name.ts

Rename CfnResource output in CDK Construct, and update `setResourceName` utility to allow for auto-adding the same name to the defaultChild, if one exists.
N/A
N/A
Unit Tests

cfn resource generation

---

packages/amplify-graphql-api-construct/src/__tests__/__functional__/basic.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts

No longer adding the `env` variable to the end of the graphql api name if it the default value `NONE`. Because this is a `No Interruptions` action in CFN, it should be safe to apply this to users who have deployed these cfn stacks manually without an ENV set, they'll just have the API name update in the cloudformation console/sdk results.
* CfnGraphqlApi.Name property has been changed, which is a No Interruptions style update. [Reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#aws-resource-appsync-graphqlapi-properties)
N/A
Unit Test

chore: remove env suffix from API name for graphql construct

---

packages/amplify-graphql-api-construct/src/__tests__/__functional__/functions.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-function-transformer/API.md
packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
packages/amplify-graphql-transformer/API.md
packages/amplify-graphql-transformer/src/graphql-transformer.ts

Allow for passing in functions defined in-stack be used by the `@function` directive rather than relying on reference by name, or name +region, etc.
N/A
N/A
Unit tests, I didn't add a unit test to the function transformer package due to difficulty in generating a function in a different stack, and passing it through, so instead just testing in the construct itself.

feat: enable passing in generated functions to the graphql transform

---

packages/amplify-category-api/src/__tests__/graphql-transformer/transform-graphql-schema-v2.test.ts
packages/amplify-category-api/src/graphql-transformer/cdk-compat/transform-manager.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts

Apparently userOverriddenSlots was used in mock, so re-enabling in the output.
N/A
N/A,  getting e2e tests to pass on https://github.com/aws-amplify/amplify-category-api/pull/1751
Added unit tests after using debugger to inspect passed through state.

fix: re-enable userOverriddenSlot response from api category transformation, to support mock

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/rds-utils.test.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-resources/utils.ts

Some of the directives like `auth, searchable` etc. are not yet supported for RDS datasource backed models.
We check for these and throw a useful error message so that customers can remove them from their schema before they re-compile again.
Added unit tests, tested in a CLI project.

Check for directives not supported in RDS yet

---

packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/src/__tests__/__functional__/outputs.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/graphql-output.ts

Stores the AppSync API ID in the CFN stack output. This ID is needed downstream to fetch the introspection schema from AppSync.
aws_appsync_apiId added to CFN output.

feat: store api id on stack output

---

packages/amplify-graphql-api-construct/src/__tests__/__functional__/__snapshots__/predictions.test.ts.snap
packages/amplify-graphql-api-construct/src/__tests__/__functional__/predictions.test.ts
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts

If a token is passed in for the predictions bucket name, then don't perform substitution, since conceivably this is already a token to a final value.
This gets predictions working for the CDK construct.
Rework how table access is referenced if a token is provided for the bucket name.
N/A
Updated function tests for CDK construct, and validated manually that I can deploy and successfully use predictions.
Also running e2e suite to verify not regressions to existing functionality.
Validated with the following shape
```typescript
new AmplifyGraphqlApi(stack, 'MyApi', {
schema: /* GraphQL */ `
type Query {
recognizeTextFromImage: String @predictions(actions: [identifyText])
}
`,
predictionsBucket: new s3.Bucket(stack, 'PredictionsBucket'),
authorizationConfig: { apiKeyConfig: { expires: …
```

fix: don't perform sub if bucketName is an unresolved token

---

packages/amplify-category-api/src/graphql-transformer/cdk-compat/transform-manager.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/__tests__/transformation/transform.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-graphql-transformer-core/src/transformer-context/stack-manager.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/stack-manager-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transform-parameter-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-resolver-provider.ts
packages/amplify-graphql-transformer/API.md
packages/amplify-graphql-transformer/src/graphql-transformer.ts

Adding back in alias methods to keep from breaking 3p transformers.
This pr reintroduces the following APIs in core:
* `resolver.mapToStack`
* `context.stackManager.getParameter`
* `context.stackManager.getStackFor`
N/A, exposing paramMap for existing plugin use-cases.
N/A
Running unit + e2e tests.

chore: add back in backwards compatibility apis to core transformer

---

packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/api-rest-lambda.migration.test.ts.snap

Updating migration test snapshot to align w/ changes made in CLI repo https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/api-rest-lambda.migration.test.ts.snap
N/A
N/A - failing e2e test
Running e2e suite.

chore: fix api lambda migration test

---

packages/amplify-category-api/src/__tests__/graphql-transformer/utils.test.ts
packages/amplify-category-api/src/graphql-transformer/utils.ts

In CLI `11.1.1`, specifying the admin role names as a string in the `custom-roles.json` file as shown below is supported.
```
{
"adminRoleNames": "amplify-123456-unauthRole"
}
```
While in the latest version `12.3.0`, we fail with error message `customRoleConfig.adminRoleNames.map is not a function`.
This PR fixes this regression and restores the original behavior.
Added unit tests,
Tested in a JS app that a single string input for admin role names compiles.

fix: reading admin role names

---

packages/amplify-schema-validator/package.json
packages/amplify-schema-validator/src/__tests__/schemas/invalid-unique-field-names-with-relation.graphql
packages/amplify-schema-validator/src/__tests__/schemas/valid-unique-field-names-with-relation.graphql
packages/amplify-schema-validator/src/__tests__/validates-unique-field-names-with-relation.test.ts
packages/amplify-schema-validator/src/index.ts
packages/amplify-schema-validator/src/validators/unique-field-names-with-relation.ts

This PR adds schema validation for relationship fields with the same name
None
N/A

fix(graphql-schema-validation): relationship names not unique

---

packages/amplify-graphql-auth-transformer/src/utils/index.ts

Use `rules?.forEach` to fix the error of `Cannot read properties forEach of undefined`

fix: cannot read properties of undefined

---

packages/amplify-e2e-tests/src/__tests__/rds-relational-directives.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/mysql-datasource-adapter.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts
packages/amplify-graphql-schema-generator/src/schema-generator/schema-overrides.ts

Include/Exclude Option
- Customers can specify in the input AMPLIFY to exclude or only include certain tables from being re-generated.
- Customers can not have "include" and "exclude" statements at the same time. they are mutually exclusive.
**Example:**
```
input AMPLIFY {
exclude: [String] = ["todos", "hello"]
}
```
or
```
input AMPLIFY {
include: [String] = ["todos", "hello"]
}
```
This change also includes preserving customer added relational fields on schema regeneration.
NA
NA
- Manual test
- New unit tests
- New E2E test

feat(api): specify include or exclude tables option to generate schema

---

packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/Dockerfile
packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/DynamoDBActions.js
packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/package.json
packages/amplify-category-api/resources/awscloudformation/container-templates/dockerfile-rest-express/Dockerfile
packages/amplify-category-api/resources/awscloudformation/container-templates/dockerfile-rest-express/DynamoDBActions.js
packages/amplify-category-api/resources/awscloudformation/container-templates/dockerfile-rest-express/package.json
packages/amplify-category-api/resources/awscloudformation/container-templates/graphql-express/Dockerfile
packages/amplify-category-api/resources/awscloudformation/container-templates/graphql-express/package.json
packages/amplify-category-api/resources/awscloudformation/container-templates/graphql-express/resolvers.js

For the 3 sample nodejs-based container apps, flip to using nodejs18 and aws sdk v3.
N/A
N/A, EOL for Nodejs14
Manually deployed via `setup-dev` to test these three apps after the changes, verifying they successfully deploy.

chore: update container templates to use node18 and aws sdk v3

---

packages/amplify-graphql-default-value-transformer/.npmignore
packages/amplify-graphql-model-transformer/.npmignore
packages/amplify-graphql-searchable-transformer/.npmignore

I've noticed that we ship unnecessary files to npm.
Repro:
- create any npm project `npm init`
- add latest `@aws-amplify/cli-internal` as dependency
- `npm install`
- search for `describe` (or some other test keyword) in node_modules.
See screenshot

fix: npm publish ignore tests and lambdas sources

---

packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/internal/codegen-assets.ts

Enable `autoDeleteObjects` on the codegen assets bucket, since we're currently failing deletion to that resource, the assets are useless after a stack is deleted.
Also, update id of the assets bucket resources, to align w/ backend deployment expectations.
Yes, `autoDeleteObjects` is set on the codegen assets bucket.
N/A
Tests + Build, and verified manually in a CDK app.

fix: enable autoDeleteObjects on the codegen bucket

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-category-api/src/provider-utils/vpc-utils.ts
packages/amplify-e2e-core/src/utils/rds.ts
packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-model-v2.test.ts
packages/amplify-graphql-model-transformer/rds-lambda/handler.ts
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/graphql-api-provider.ts
packages/amplify-graphql-transformer-interfaces/src/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/amplify-graphql-transformer-test-utils/src/test-transform.ts
packages/amplify-graphql-transformer/API.md
packages/amplify-graphql-transformer/src/graphql-transformer.ts

- Deploy the SQL lambda in VPC if the database is in VPC regardless whether the database is accessible through internet or not.
- Add VPC endpoints required to read the secrets if the database is in a VPC.
- Inject the SSM VPC endpoints to SQL lambda environment variable.
- SQL lambda uses SSM endpoint from the environment variable.
NA
NA
- Manual test
- E2E tests

feat(api): always use vpc for aws rds instances and clusters 

---

packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-v2-generate-schema.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-v2.test.ts
packages/amplify-graphql-schema-generator/API.md
packages/amplify-graphql-schema-generator/package.json
packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate-schema.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/mysql-datasource-adapter.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/generate-schema.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/schema-overrides.test.ts
packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts
packages/amplify-graphql-schema-generator/src/schema-generator/schema-overrides.ts

- Adds `@refersTo` to model objects automatically during `import api` if the table name is not idiomatic GraphQL type name.
- Preserves any manual edits to automatically inferred model name mappings during `api generate-schema`.
Added unit and E2E tests
[First run](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:354a4cb4-a2cd-4246-89e1-07bbe95bc130?region=us-east-1#) and [second](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:d711487c-5db2-4091-a387-3ad666f94fc7?region=us-east-1) after fixing a test
By submitting this pull request, I confirm that my contribution is made …

feat: infer refersTo for models in the import flow and preserve edits during schema regeneration

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/src/__tests__/internal/amplify-metadata.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/internal/amplify-metadata.ts
packages/amplify-graphql-api-construct/src/internal/index.ts

Add amplify metadata to root stack description if none is set already (e.g. don't override customer description).
No, only updating the description conditionally.
N/A
Unit tests, validate in a tag release before shipping.

feat: add amplify metadata to stack description if none is provided

---

packages/amplify-graphql-default-value-transformer/src/__tests__/amplify-grapphql-default-value-transformer.test.ts
packages/amplify-graphql-default-value-transformer/src/graphql-default-value-transformer.ts
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-transformer-test-utils/API.md

Disable default value validation for RDS datasource. The default value exists to understand the table configuration, we do not use it in our resolvers.
When customer define defaults in the database, they can use function calls or certain database specific syntax to define the defaults (eg: CURRENT_TIMESTAMP for datetime type). In such cases, we do not want to validate or set the default value in the transformers. We will leave it up to the database to set the default value if it is not present in the input.
NA
NA
- Manual test
- Unit tests

fix(graphql): disable default value validation for rds

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/__snapshots__/apigw-stack-builder.test.ts.snap
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts

When a REST API path contained a path parameter (`/path/{param}`) and this API had an IAM policy associated with it (when user group is used for auth), we were putting this path directly in the resource of the policy, meaning it would never match. This PR replaces `{param}` path components in the policy resource with a wildcard (*).
A previous [PR](https://github.com/aws-amplify/amplify-cli/pull/5092) addressed the issue in the legacy add REST API process. This PR is to fix the same issue for current approach.
Updates the User Group Policy generation to substitute path parameters with wildcards.
**New IAM policy:**
```
{
"Version": "2012-10-17",
"Statement": [
{
"Action": "execute-api:Invoke",
"Resource": [
"arn:aws:execute-api:us-west-2:0123456789012:abcdefghijk/dev/GET/book/*", …
```

fix(apigw): replace path param with wildcard

---

packages/amplify-category-api/src/__tests__/graphql-transformer/override/__snapshots__/amplify-graphql-index-transformer-override.test.ts.snap
packages/amplify-category-api/src/__tests__/graphql-transformer/override/__snapshots__/amplify-graphql-primary-key-transformer-override.test.ts.snap
packages/amplify-e2e-tests/src/__tests__/graphql-v2/sync_query_datastore.test.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts

Fixes the issue with `deltaSyncTableTtl` that's being set as string causing the `minLastSync` value to be incorrectly computed.
Added E2E test. [Link to E2E](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:765eaacb-1b00-46bb-9699-b511bba68d87?region=us-east-1#)

fix: change the ttl to integer

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/__snapshots__/ecs-apigw-stack.test.ts.snap
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/ecs-apigw-stack.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/base-api-stack.ts

Sometimes the policies have a single action as a string instead of a list of string. I'm not sure what cases this happens in. When it is a string `iam.PolicyStatement` will split the string as if it were an array resulting in the following error.
```
Action 's' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.
```
N/A
Unit testings

fix: convert single action to list of actions

---

packages/amplify-graphql-api-construct/src/internal/codegen-assets.ts

This change bumps s3 bucket deployment memory setting to 1536 MB, which is optimizing cost while providing reasonable performance boost until we find better solutions.
See https://docs.aws.amazon.com/lambda/latest/operatorguide/computing-power.html .
This is a follow up to https://github.com/aws-amplify/amplify-category-api/pull/1933 after gathering more data.
Full benchmarking procedure and its artifacts can be found here https://github.com/sobolk/aws-cdk/blob/bucket-upload/testapps/testapp001/hotswap_s3_summary.md .
Benchmark was run by using isolated s3 bucket deployment scenario that processes upload of 3 files that have volume ~400 Bytes when compressed.
All samples taken by:
1. Adjusting memory settings
2. Executing `npx cdk deploy` to stabilize
3. Editing asset file by appending …

fix: optimize codegen asset upload

---

packages/amplify-e2e-tests/src/__tests__/rds-mysql-auth-apikey-lambda.test.ts
packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-mutation-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-query-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-subscription-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/rds-mutation-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/rds-query-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/rds-subscription-auth.test.ts
packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/resolvers/common.ts
packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/resolvers/mutation.ts
packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/resolvers/query.ts
packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/resolvers/subscription.ts

Minor resolver changes after E2E testing in ICN region after AppSync deployment of AuthUtils.
Add E2E test for Api Key and Lambda auth on queries and mutations.
NA
NA
- Manual test
- E2E test

fix(api): resolver correction for userpools provider and mutation operation

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/src/internal/construct-exports.ts
packages/amplify-graphql-api-construct/src/types.ts
packages/amplify-graphql-index-transformer/API.md
packages/amplify-graphql-index-transformer/src/index.ts
packages/amplify-graphql-index-transformer/src/resolvers/resolvers.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/amplify-dynamodb-table-generator.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/amplify-table-manager-lambda.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/amplify-dynamodb-table-generator.test.ts
packages/amplify-graphql-model-transformer/src/__tests__/amplify-table-manager-lambda.test.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamo-model-resource-generator.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts

Added non-GSI update support in the amplify table handler, which includes
- `BillingMode`
- `ProvisionedThroughput` (both table and index)
- `TimeToLiveSpecification`
- `PointInTimeRecoverySpecification`
- `StreamSpecification`
- `SSESpecification`
- `DeletionProtectionEnabled`
Most of the attributes require a dedicated `UpdateTable` call and cannot be merged with others.
So far some limitations have been observed from manual testing:
- `BillingMode` update to `PAY_PER_REQUEST` is only allowed for once per 24 hours. (Table creation with `PAY_PER_REQUEST` also counts)
- TimeToLive(TTL) update is subject to a minimum time interval of 30 minutes. (Confirmed from DynamoDB team)
- Sever side encryption (SSE) updates are limited in the 24h window. After the first 4 change, each subsequent …

feat(amplify-table): add non-GSI update in handler

---

packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-e2e-core/src/init/amplifyPush.ts
packages/amplify-e2e-core/src/utils/rds.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-auth-iam-apikey-lambda-subscription.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-auth-iam.test.ts
packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts
packages/amplify-e2e-tests/src/utils/api.ts
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-mutation-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-query-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-subscription-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/resolvers/common.ts
packages/amplify-graphql-schema-generator/src/__tests__/vpc-helper.test.ts

Adding E2E tests for Auth Directive IAM provider support.
- Covers IAM public and private rules. (Public rule strictly gives access to unauthRule and private rule gives access to the logged in users).
- Mutli-auth scenarios with API key, lambda and IAM for queries, mutations and subscriptions.

test(api): e2e for iam provider on rds models

---

packages/amplify-graphql-auth-transformer/src/__tests__/rds-mutation-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/rds-query-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/rds-subscription-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/validations.ts

For the initial release, we do not support field auth on RDS models.
This change throws an error if auth directive is defined on a field of RDS models.
- Added unit tests.

fix(api): do not allow field auth on rds models

---

packages/amplify-category-api/src/provider-utils/supported-datasources.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts

This PR enables support in ap-east-1 region (HKG). Associated with https://github.com/aws-amplify/amplify-cli/pull/13332
N/A
N/A
I set `ap-east-1` in my ~/.aws/config for my amplify profile and created an app.
I ran:
amplify-dev init
amplify-dev add api (default graphQL options)
amplify-dev push
I was able to observe the stack successfully deployed to HKG.

chore: add ap-east-1 (HKG) region

---

packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerV2Tests.e2e.test.ts

Update predictions E2E test inline regex strings. This resolves a flaky test due to the underlying service 'polly' sdk response.

test(api): update predictions test inline string match

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-mutation-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-query-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-subscription-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/rds-mutation-auth.test.ts
packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/resolvers/common.ts

Adding admin roles support for IAM provider using AppSync auth utils.
- Admin roles include function roles / studio managed roles and roles defined in custom-roles.json file.
- We do partial match of the role name similar to DDB.
NA
NA
- Unit tests
- Manual test

fix(api): add iam auth support for admin roles with auth utils

---

packages/amplify-e2e-tests/src/__tests__/rds-postgres-import.test.ts
packages/amplify-graphql-schema-generator/API.md
packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate-schema.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/generate-schema.test.ts
packages/amplify-graphql-schema-generator/src/datasource-adapter/datasource-adapter.ts
packages/amplify-graphql-schema-generator/src/datasource-adapter/pg-datasource-adapter.ts
packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts

- Add support to import enum types on postgres datasource.
- Fix a bug where non nullable ENUM field would incorrectly import as 'String'.
NA
NA
- Unit tests
- E2E tests
- Manual test

feat(api): add enum support for postgres import

---

packages/amplify-graphql-api-construct-tests/src/__tests__/all-auth-modes.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/all-auth-modes/authorizer.ts
packages/amplify-graphql-api-construct-tests/src/graphql-request.ts
packages/amplify-graphql-api-construct/src/internal/authorization-modes.ts
packages/amplify-graphql-transformer-core/src/graphql-api.ts
packages/amplify-graphql-transformer-core/src/utils/authType.ts
packages/amplify-graphql-transformer-interfaces/src/graphql-api-provider.ts

Lambda authorizers were still computing an ARN which included `-NONE` at the end, to align w/ older amplify convention. This is no longer guaranteed, given the lambda can be created in a normal CDK app, instead pass in the IFunction ARN in a CDK context, and use that when available.
Updated the all-auth-roles e2e test for CDK to flex this functionality.
Yes, GraphqlApi auth config for lambda will use the arn if possible.
N/A
Updated E2E test and manually.

fix: pass in and use correct lambda arn for lambdaauthorizers

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/src/__tests__/__functional__/props.test.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/sql-bound-api.test.ts
packages/amplify-graphql-api-construct/src/__tests__/amplify-graphql-definition.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/types.ts

Make VPC configuration optional in CDK construct.
Unit tests and manual tests. No good way to do e2e tests on this since it requires a publicly available database, which RDS doesn't like to do.

fix: Make VPC configuration optional

---

codebuild_specs/e2e_workflow.yml
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/oidc-provider.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-auth-apikey-lambda.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-auth-iam-apikey-lambda-subscription.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-auth-iam.test.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-apikey-lambda-iam-subscription.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-apikey-lambda.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-iam.ts
scripts/split-e2e-tests.ts

Disable failing RDS Auth E2E including the `custom-claims` on MySQL and all PostgreSQL tests.
These will be re-enabled once fixed and confirmed in CI.
[E2E run](https://tiny.amazon.com/gqwp1fg9/IsenLink)

chore: disable failing auth e2e tests for RDS

---

client-test-apps/js/api-model-relationship-app/package.json
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/testHarness.ts

"It works on my machine!"
Trying to figure out how to get around some timeout issues w/ jest-dev-server, I bumped to the latest version and explicitly set the `host` now. There's an additional `path` param, which I'd prefer to set to `auth-modes` so that first test suite has a better chance of success, but that's not working for me so left it out.
N/A
Canaries are failing intermittently right now due to many classes of timeouts.
Ran locally

fix: bump jest-dev-server, and update test harness accordingly

---

packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-1.test.ts

Increase test timeout for iterative deploy step.
N/A
N/A
E2E Test passes

chore: bump timeout for api table test, since it's inconsistently completing in time

---

codebuild_specs/e2e_workflow.yml
packages/amplify-category-api/src/__tests__/graphql-transformer/sandbox-mode-helpers.test.ts
packages/amplify-category-api/src/graphql-transformer/sandbox-mode-helpers.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/custom-claims-userpool.ts
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/oidc-provider.ts
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-provider.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-multi-auth-1.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-oidc-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-userpool-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-custom-claims-refersto-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-oidc-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-userpool-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-v2.test.ts
packages/amplify-e2e-tests/src/rds-v2-test-utils/index.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-custom-claims-refersto-auth.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-oidc.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
scripts/split-e2e-tests.ts

- Do not throw error when global Auth rule is not present. Moved from https://github.com/aws-amplify/amplify-category-api/pull/2034
- Update the SQL lambda layer version after latest release of layer
- Add Postgres Auth E2E tests
- Excludes a small subset of V1 transformer E2Es to make room for new tests. These will be added back once CI account is scaled.
CI checks

test: add remaining postgres Auth E2Es

---

codebuild_specs/e2e_workflow.yml
scripts/split-e2e-tests.ts

- Runs RDS tests as solo jobs
- Remove items in excluded tests.
[Full E2E run](https://tiny.amazon.com/13972esx7/IsenLink). The `rds_import_vpc` looks like a legit failure coming from the String DataSource abstractions. A follow-up PR will fix this.

chore: split RDS tests as solo jobs and re-add excluded V1 tests

---

client-test-apps/js/api-model-relationship-app/package.json

`wait-on` (dep of `jest-dev-server`) was updated to use the latest version of `axios`. `axios` updated to default to ESM instead of common js. This results in the canary app failing to compile.
Set jest to use the common js version of `axios`.
N/A
N/A
Ran canary locally.

test: fix canary transitive dep to use common js version

---

.prettierignore
packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-array-objects.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-import.test.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-model-v2.ts
packages/amplify-graphql-model-transformer/rds-lambda/package.json
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/graphql-transformer-common/API.md
packages/graphql-transformer-common/src/ResourceConstants.ts

Renames the VPC Endpoint prefix from RDS to SQL. This is not a breaking change, since these endpoints are created and consumed by Amplify. 
Additional changes:
- Fixes an e2e test that was looking for an incorrect Lambda Layer CDK resource name after the RDS -> SQL renaming in #2069.
- Add a transient dynamodb simulator file to the prettier ignore, since it is sometimes not removed if a local test is interrupted before cleaning up
- Remove deprecated `@types/knex` dependency per its deprecation message:
> npm WARN deprecated @types/knex@0.16.1: This is a stub types
> definition. knex provides its own type definitions, so you do not need
> this installed.

fix: Rename VPC Endpoint CDK prefix

---

packages/amplify-graphql-schema-generator/src/__tests__/schema-overrides.test.ts
packages/amplify-graphql-schema-generator/src/schema-generator/schema-overrides.ts

If the customers have enum types in their schema that do not exist in their database but are defined manually to represent either the inputs or outputs of custom GraphQL operations, we will preserve them when they re-generate their schema.
Added unit tests

fix: retain custom enums during schema regeneration

---

packages/amplify-e2e-core/src/index.ts
packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts

Fix e2e test that broke because of the patching lambda regionalization

test: fix subscription prefix in rds-import-vpc.test.ts

---

packages/amplify-graphql-model-transformer/package.json

Increase model transformer test coverage lines > 80%.
Currently coverage provider is set to babel (default) which produces incorrect coverage report. I have verified the lines showed as uncovered with breakpoints and those lines are definitely covered. Upon further analysis, it is found that coverage provider "v8" provides more accurate report.

test(api): increase model transformer test coverage

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/src/__tests__/amplify-graphql-definition.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-definition.ts
packages/amplify-graphql-api-construct/src/internal/data-source-config.ts

Validates the user provided DataSource Strategy for SQL backend to ensure that the input SSM paths have a prefix of `/`.
Added unit tests

fix: validate SSM paths in sql db connection config

---

packages/amplify-category-api/src/__tests__/graphql-transformer/transform-graphql-schema-v2.test.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-e2e-core/src/init/amplifyPush.ts
packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-multi-auth-1.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-oidc-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-userpool-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-array-objects.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-relational-directives.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-relational-directives.test.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-apikey-lambda-iam-subscription.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-apikey-lambda.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-custom-claims-refersto-auth.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-iam.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-oidc.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-model-v2.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-refers-to-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-refers-to.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/sql-e2e-config.ts

Use the published beta layer versions to run all the E2E tests. This allows us to publish the layer version to PROD after full E2E testing.

test(api): use beta layer for e2e tests

---

codebuild_specs/e2e_workflow.yml
codebuild_specs/e2e_workflow_base.yml
codebuild_specs/pr_workflow.yml
codebuild_specs/release_workflow.yml

Updates the `build_windows` step of relevant codebuild specs to depend on `build_linux` rather than making it a top-tier step.
The behavior I observed from manual testing is that any tasks declared with no dependencies must complete before any dependent tasks complete. By moving the long-running `build_windows` task to depend on `build_linux`, we make the tradeoff of decreased wallclock times for codebuild execution (estimated savings: ~20min per build) at the cost of a delay in detecting Windows build failures.
Since Windows build failures are rare (at least in my experience), this seems like a tradeoff worth making for the quality-of-life benefit.

chore: update build dependency order

---

.vscode/settings.json
client-test-apps/js/api-model-relationship-app/.gitignore
client-test-apps/js/api-model-relationship-app/package.json
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/amplifyCLI.ts
client-test-apps/js/api-model-relationship-app/src/__tests__/utils/execUtils.ts

`@types/react` released a breaking change in 18.2.43 that made `placeholder` a required attribute in components from our `@aws-amplify/ui-react` dependency.
This change pins `@types/react` to 18.2.42 until they release a new version, to restore canary coverage.
Additional changes:
- Update fixAll.eslint setting (auto-applied by VSCode)
- Opportunistic lint fixes
- Fix missing `strip-ansi` import that was breaking local canary execution
- Local canary execution now succeeds

test: Fix beta canary

---

packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate-schema.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/generate-schema.test.ts
packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts
packages/amplify-graphql-transformer-core/package.json

Add a validation step to make sure that the imported ENUM values are valid GraphQL enum values. Otherwise, throw an error.
No.
NA
- Manual test
- Unit test

fix(api): validate imported enum values

---

packages/amplify-category-api/src/__tests__/graphql-transformer/override/amplify-graphql-searchable-transformer-override.test.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts

Minor change to assert `EnforceHTTPS` flag in searchable transformer tests.

test: Add EnforceHTTPS assertions to OpenSearch transformer

---

packages/amplify-graphql-api-construct/src/__tests__/__functional__/combine-synthesis.test.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/relationships.test.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/test-utils.ts
packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts

Fixes Gen2/CDK Construct regression in manyToMany relationships with Amplify-managed table strategies.

fix: Fix manyToMany relationships with Amplify managed table strategies

---

packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-transformer-test-utils/API.md
packages/amplify-graphql-transformer-test-utils/src/deployment-resources.ts
packages/amplify-graphql-transformer-test-utils/src/index.ts

Adds a couple of missing multi-auth test cases from the V1 suite.
This change also adds a test utility to retrieve from the root stack, resources by key prefix. Useful for grabbing the policy docs we wanted to assert on. After this is merged I'll port the test in #2164 to use the new util.

test: add additional multi-auth tests from V1 suite

---

packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/definitions.ts

I extended the searchable transformer definitions, so the generated enum includes the cardinality aggregation type. 
The cardinality aggregation works without any other changes with the current resolver templates.
Used the amplify-dev build to do a `amplify-dev codegen` and verfied that the `cardinality` is generated into the API.ts. Then used the cardinality agg to fetch data from opensearch. 

feat: Adds support for cardinality aggregation type

---

dependency_licenses.txt
packages/graphql-transformer-core/package.json
packages/graphql-transformer-core/src/__tests__/util/amplifyUtils.test.ts
packages/graphql-transformer-core/src/util/amplifyUtils.ts
yarn.lock

The `glob` package has a breaking change for version greater than `7.2.0`, in which the following code snippet generates different results on the windows platform.
```TypeScript
const fileNames = glob.sync('**/*', {
cwd: directory,
nodir: true,
});
```
glob version less and equal to 7.2.0
```
['foo/bar/baz']
```
glob version greater than 7.2.0
```
['foo\bar\baz']
```
This causes the incorrect S3 upload keys generated, which causes the `amplify push` failing in the windows machine with error of access denied from S3.
The fix is to add the `posix` flag to `true` to always generate match result in the forward slash `/` format.
Reference: 
https://github.com/isaacs/node-glob/issues/480
https://github.com/isaacs/node-glob/issues/467
Unit tests
`amplify-dev push` on a windows machine
By …

fix(glob): remove backslash in s3 upload key

---

packages/amplify-e2e-tests/src/__tests__/rds-mysql-field-auth-apikey.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-field-auth-lambda.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-field-auth-apikey.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-field-auth-lambda.test.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-field-auth-apikey.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-field-auth-lambda.ts
packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/non-model-auth.test.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/definitions.ts
packages/amplify-graphql-transformer-test-utils/API.md
packages/amplify-graphql-transformer-test-utils/src/deployment-resources.ts
packages/amplify-graphql-transformer-test-utils/src/index.ts
packages/amplify-schema-validator/jest.config.js
packages/amplify-schema-validator/package.json
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts

Add E2E tests for API Key and Lambda Authorizer field rules.
(The change also includes the commits from main)
No.
NA
- New E2E tests

test(api): add rds e2e tests for api key and lambda authorizer field auth

---

FixJestEnvironment.js
packages/amplify-e2e-core/src/cli-test-environment.js
packages/amplify-e2e-tests/package.json
packages/amplify-graphql-api-construct-tests/package.json
packages/amplify-graphql-http-transformer/package.json
packages/amplify-util-mock/package.json
packages/graphql-transformers-e2e-tests/package.json

3351250a9 fixed the Jest environment by adding the `structuredClone` global to the environment. However, that commit overwrote a custom environment declaration used by some E2E tests. This PR restores that custom environment and ports the `structuredClone` fix to it. It also removes some duplicate `testEnvironment` declarations from various **package.json** files.

test: Restore custom CLI jest environment

---

packages/amplify-e2e-tests/src/__tests__/rds-mysql-field-auth-iam.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-field-auth-iam.test.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-field-auth-iam.ts

Add E2E tests for RDS MySQL and Postgres field level auth rules for IAM provider.
Changes are tested by running the new E2E tests locally and codebuild.

test(api): rds e2e field auth tests for iam provider

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/rds-utils.test.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-resources/utils.ts

Download the RDS Mapping S3 manifest only if the project contains SQL datasource strategy.
No
NA
- Manually tested and made sure that the S3 file is downloaded only if the project contains SQL datasource strategy.
- E2E tests to make sure all the scenarios are working fine.

fix(api): download rds layer only if required

---

packages/amplify-e2e-core/src/utils/rds.ts

The RDS instances that we create in our E2E tests use the default CA certification which is `rds-ca-2019` that has an expiry date in August, 2024. This PR updates it to the newly [recommended](https://w.amazon.com/bin/view/RDS/CA_Certificate_Rotation_Program_2024) certificate i.e `rds-ca-rsa2048-g1`
[Link to full E2Es](https://tiny.amazon.com/1bs1gnwlg/IsenLink).
Some of these are known failures that are being fixed on `main`. What we care about here is that atleast one RDS E2E succeeds which verifies that the Lambda data source is able to connect to the DB with updated certificate.

chore: use updated ca certificate for rds instances

---

packages/amplify-graphql-auth-transformer/API.md
packages/amplify-graphql-auth-transformer/src/__tests__/combination-tests/auth-operations-custom-mutations-queries.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/combination-tests/auth-operations-models.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/combination-tests/auth-operations-non-models.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/definitions.ts
packages/amplify-graphql-auth-transformer/src/utils/index.ts

Support 'read' operation alias for SQL data sources:
```graphql
type Todo @model @auth(rules: [{allow: owner, operations: [read]}]) { ... }
```
This change is enabled by adding an `isSqlDataSource` option to the `getAuthDirectiveRules` utility function. That function is exported from the V2 transformer and so changes the API.md, but does not change the customer-facing API.

fix: support 'read' operation alias for SQL data sources

---

codebuild_specs/e2e_workflow.yml
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/oidc-provider-fields.ts
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-provider-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-oidc-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool-fields.ts
scripts/split-e2e-tests.ts

- Add cognito/OIDC group based field authorization e2e tests. Includes static, dynamic single and list of groups scenarios.
- Remove previous TODOs that were waiting on AppSync Auth utils changes since they are now deployed to ICN region.
- Update split E2E script to run the new tests in ICN until the AppSync Auth utils changes are deployed to all regions.
Running added E2Es locally and on CI environment.

test: add group based field auth e2e tests for SQL sources

---

packages/amplify-graphql-api-construct/src/internal/default-parameters.ts
packages/amplify-graphql-transformer-core/src/__tests__/utils/directive-wrapper-test.ts
packages/amplify-graphql-transformer-core/src/utils/directive-wrapper.ts

This PR optimizes the merging of default and user provided directive arguments by avoiding deep cloning of default values in cases where:
- No user provided args exist. In this case, we essentially just return the default values as is.
- No common properties exist. In this case, we include properties from both inputs and no need for recursively merging them.
This fixes the https://github.com/aws-amplify/amplify-category-api/issues/1978 without changing the default behavior of the construct. The stack size error is being thrown by lodash's deep clone utility due to some circular references in the nested object which includes GraphQL AST nodes with multiple sub-nodes within them. These don't imply any relational circular dependencies between models in the schema.
Added unit tests which also …

fix: deep merge default behavior

---

packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-iam-fields.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-field-auth-userpool-iam.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-field-auth-userpool-iam.test.ts
packages/amplify-e2e-tests/src/rds-v2-test-utils/index.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool-iam-fields.ts

Added the field auth combination tests(userpool + public/private iam) for mysql and postgres
Run the e2e tests locally and get both passed.

test(rds): add e2e tests for field auth (userpool+iam)

---

client-test-apps/js/api-model-relationship-app/cypress.config.ts

Currently our canary test is failing intermittently because the page fails to load within one min (the default pageload timeout). Increasing the pageload timeout to 3 minutes in attempt to fix it.

test(api): increase cypress page load timeout

---

packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Clean up stale roles created using SDK by E2E tests.
- auth exhaustive roles
- rds-schema-inspector roles
- amplify_e2e_tests_lambda roles
- JsonMockStack-jsonMockApi roles
- SubscriptionAuthV2Tests roles

chore(api): clean up stale roles created using sdk

---

packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-iam-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool-iam-fields.ts

fix(rds): userpool & iam e2e tests

---

client-test-apps/js/api-model-relationship-app/src/components/CRUDLComponents.tsx

Add missing await to the `onClick` event handler in canary tests.

test(api): await async event handler call in canary

---

shared-scripts.sh

Increase canary test build step `yarn` timeout to 3 minutes.

test(api): increase canary test yarn install timeout

---

codebuild_specs/e2e_workflow.yml
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/oidc-provider-fields.ts
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-provider-fields.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-oidc-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-userpool-auth.test.ts
packages/amplify-e2e-tests/src/rds-v2-test-utils/index.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-oidc-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-oidc.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool.ts

- Tests access to non-model fields that are protected.
- Tests that Auth rules are respected on renamed fields with `@refersTo`.
- Skips test cases covering custom operations from `MySQL/PG` and `userpool/oidc` test suites until a fix is deployed to ICN region for `validateUsingSource` Auth util. This action item is being tracked in [this ticket](https://app.asana.com/0/1206048977824382/1206538503760206/f). 
[Added E2Es pass on CI](https://tiny.amazon.com/1jq5usor8/IsenLink)

(test): add E2Es for non-model and renamed field auth - userpool and oidc providers

---

codebuild_specs/e2e_workflow.yml
packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-static-dynamic-fields.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-field-auth-userpool-static-dynamic.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-field-auth-userpool-static-dynamic.test.ts
packages/amplify-e2e-tests/src/rds-v2-test-utils/index.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool-iam-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool-static-dynamic-fields.ts
packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts

Added the field auth combination tests(userpool static & dynamic) for mysql and postgres

test(rds): add e2e tests for field auth (userpool static & dynamic)

---

packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Fixes the resource cleanup regex for cdkamplifytable IAM roles. Currently test accounts are not destroying those roles. Note: I'm assuming that the regex evaluation allows character classes and normal `*` wildcards. If it does not, the behavior will be that roles continue to not be removed. In no case will this impact any production code.

test: fix resource cleanup regex for cdkamplifytable roles

---

codebuild_specs/createapi_canary_workflow.yml

Add codebuild spec to run a canary test in all supported regions. The region list is taken from the SQL layer pipeline.

test(api): add create api canary codebuild buildspec

---

codebuild_specs/createapi_canary_workflow.yml
packages/amplify-e2e-tests/src/__tests__/api_canary.ts

Remove the below steps which are not required for canary.
- Windows build.
- Yarn lock verify.
- License validation.
- Verify CDK version.
- Verify API extract.
Modified the test to a simple usecase so that the canary is faster.

test(api): remove unwanted steps from canary build spec

---

packages/amplify-e2e-tests/src/__tests__/rds-mysql-field-auth-iam.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-pg-field-auth-iam.test.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-field-auth-iam.ts

Add E2E test cases for validating IAM provider field level auth for update and delete operations.

test(api): add e2e for iam private field auth

---

codebuild_specs/createapi_canary_workflow.yml

Temporarily disable running the tests in opt-in regions and clean up script.
These will be enabled again once we merge https://github.com/aws-amplify/amplify-category-api/pull/2261.

chore(ci): temp disable opt-in regions in canary

---

codebuild_specs/createapi_canary_workflow.yml
codebuild_specs/emit_createapi_canary_metric.yml
codebuild_specs/run_createapi_canary_tests.yml
shared-scripts.sh

- Increase npm fetch retries to 5 (default is 2).
- Increase npm fetch fetch timeout to 10 minutes (default is 5 min).
- Emit canary metrics.

chore(ci): increase npm timeout and emit canary metrics

---

client-test-apps/js/api-model-relationship-app/src/__tests__/utils/execUtils.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/init/amplifyPush.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/nexpect.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/sql-models.test.ts
packages/amplify-graphql-api-construct-tests/src/commands.ts

- Fixes deployment errors due to unsupported Node14 Lambda runtime in custom resource provider in CDK v2.80.0
- Increases "no output timeout" for a few tests to account for codegen asset BucketDeployment
- Suppresses errors getting bucket tags, so non-erroring buckets can be processed

test: improve E2E test reliability

---

packages/amplify-graphql-model-transformer/rds-lambda/handler.ts

Add credential refresh and retry logic to SQL lambda. 
This is merging into a feature branch.
N/A
N/A
Manual testing. E2E tests will come in subsequent PR.

feat: add credential retry logic to sql lambda

---

codebuild_specs/emit_createapi_canary_metric.yml

Emit canary metric task doesn't need scan artifacts step, this was added in error in the previous PR https://github.com/aws-amplify/amplify-category-api/pull/2276. This step emits the current status of the pipeline to cloudwatch, any errors while executing the put-metric operation will be recorded in the codebuild logs (no need for artifacts).

chore(api): remove scan artifacts command when reporting metrics

---

codebuild_specs/createapi_canary_workflow.yml
codebuild_specs/run_canary_e2e_tests.yml
shared-scripts.sh

Currently the metrics for failed canaries are not emitted to cloudwatch. We expect codebuild to send '0' for failed canary runs.
This is fundamentally due to how codebuild works, codebuild sets the environment variable `CODEBUILD_BUILD_SUCCEEDING` to 1 if the last step of the build step is succeeding (based on error code). Since we have emit metrics command in 'build' step, this emits `1` when all the tests are passing but skipped if any of the prior steps fail.
In this PR, we are changing this behavior. We will emit metrics for each test. The alarm would consolidate all these values and work as expected because we consider only the AVERAGE to trigger it.

chore(ci): emit canary metrics on each region test

---

shared-scripts.sh

Another attempt to solve intermittent ERR_SOCKET_TIMEOUT errors on E2E tests.
- Increase npm config maxsockets to 1. (This will cause downloads to be slow but expected to be more reliable).
- Slightly increase min and max retry timeouts.
(I have run full pipeline to make sure there is no adverse behavior).

chore(ci): add max socket to npm config

---

codebuild_specs/createapi_canary_workflow.yml

Enable Create API canary in opt-in regions.
- ap-east-1
- eu-south-1
- me-south-1

chore(ci): enable canary optin regions

---

shared-scripts.sh

Using absolute path since the current directory is not reset to root in E2E retries.

chore: fix fetching test regions in e2e retry

---

codebuild_specs/e2e_workflow.yml
packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-1.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-3.test.ts
packages/amplify-graphql-api-construct-tests/src/commands.ts
scripts/split-e2e-tests.ts

Upgrades the version of CDK used in our E2E tests. This does not include the version of CDK libs we use in our construct or plugin.
Other changes:
- Split up the long running `amplify_table_1`.
- Added couple of tests that were prone to failures to solo jobs so we can better monitor them going forward.
[Full E2E suite passed](https://tiny.amazon.com/yfrhl0k6/IsenLink)

chore: upgrade CDK version in tests to `2.129.0`

---

packages/amplify-e2e-tests/src/__tests__/rds-mysql-oidc-auth.test.ts
packages/amplify-e2e-tests/src/__tests__/rds-mysql-userpool-auth.test.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-oidc.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool.ts

Re-enabled custom operations E2E tests. NOTE: These changes are currently only deployed to ICN (ap-northeast-2), so make sure we only run tests there. The updated tests run successfully.

test: re-enabled custom operations E2E tests

---

packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-ddb-fields-transformer.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-sql-transformer.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/data-source-based-directive-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-belongs-to-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-one-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-ddb-fields-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-sql-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-ddb-fields-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-sql-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-transformer-factory.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/utils/model-datasource-strategy-utils.ts

Refactor of `amplify-graphql-relational-transformer` splitting out datasource specific directive logic. The goal of refactor is to allow additional logical branches for data sources & directive parameter combinations (e.g. DynamoDB references) to be added in a maintainable way.
There are no functional changes included in this PR.
**Changes:**
- Adds `DataSourceBasedDirectiveTransformer` interface to represent the methods called in the existing relational transformers that operate on individual `<RelationType>DirectiveConfiguration` types. [[11efed6](https://github.com/aws-amplify/amplify-category-api/pull/2330/commits/11efed6a5f54c87153c773046ea0f043e635a34f)]
- Adds `DataSourceBasedDirectiveTransformer` implementing types for:
- `belongsTo` …

refactor(graphql-relational-transformer): split out datasource specific directive logic

---

codebuild_specs/e2e_workflow.yml

Changes to the E2E workflow are not necessary for the new secrets manager e2e test. Revert the workflow the state on main.
N/A
N/A
* E2E tests

chore: revert e2e workflow

---

packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Update the regex for stale IAM roles for those generated by GraphQL E2E tests

chore: update cleanup script for more stale iam roles

---

packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/resolver/ddb-fields-generator.ts
packages/amplify-graphql-relational-transformer/src/resolver/generator-factory.ts

Renames `DDBRelationalResolverGenerator` to `DDBFieldsRelationalResolverGenerator` and updates usage.
**No functional change.** This is to disambiguate between the existing the existing DDB fields resolver generator and the incoming `DDBReferencesRelationalResolverGenerator` (coming in subsequent PR).

refactor(graphql-relational-transformer): rename existing ddb-generator to include fields in name

---

packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-relational-transformer/src/types.ts

- Adds the `updateTableForReferencesConnection` method, which will be invoked in `generateResolvers` in the incoming `HasManyDirectiveDDBReferencesTransformer` (subsequent PR). 
- Makes an initial pass at consolidating common parts of `updateTableForConnection` (fields) and `updateTableForReferencesConnection`.
There are few TODOs included with this change that will be resolved in later PRs.
Once we have a commit in `feat/ddb-references`, I'll open a draft PR against main and start tracking these as open items in feature branch PR description.

feat(graphql-relational-transformer): add gsi creation for ddb references queries

---

packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/resolver/ddb-fields-generator.ts
packages/amplify-graphql-relational-transformer/src/resolver/ddb-references-generator.ts

- Adds `DDBRelationalReferencesResolverGenerator`, the `references` based counterpart to `DDBRelationalFieldsResolverGenerator`. 
- `makeHasManyGetItemsConnectionWithKeyResolver` and `makeBelongsToGetItemConnectionWithKeyResolver` are based on a combination of the existing implementations for SQL references and DDB fields.
All test cases still pass when invoking `yarn test`, but it fails because the 90% threshold isn't hit. Test cases are incoming in a subsequent PR.

feat(graphql-relational-transformer): add resolver generator for ddb references with hasMany and belongsTo

---

packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts

Adds appropriate Cognito Identity ID conditions to role trust policies for E2E test roles. These conditions mimic those created by Amplify CLI.

test: Scope auth/unauth roles created in e2e tests

---

packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/base-cdk.test.ts
packages/amplify-graphql-api-construct/src/internal/codegen-assets.ts

Enable CORS on the codegen assets bucket. This is required for console team to access the objects from user context.
No.
NA.
- Local Testing
- Added E2E tests

feat(api): enable cors on codegen asset bucket

---

package.json

Fixes the `publish:tag` script in package.json to allow the `$NPM_TAG` env var to be correctly interpolated into the commit message.
Run a tagged release from [a branch containing this commit](https://github.com/aws-amplify/amplify-category-api/tree/palpatim.chore.fix-publish-tag) and ensure the commit message is correct. See that b32d1359c has the commit message: `chore(release): Publish tagged release fix-publish-tag [ci skip]` rather than the previous `chore(release): Publish tagged release $NPM_TAG [ci skip]`

chore: fix publish:tag script to interpolate NPM_TAG

---

packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-one-references-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-references-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-one-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-ddb-fields-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-sql-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/resolver/ddb-generator.ts
packages/amplify-graphql-relational-transformer/src/resolver/ddb-references-generator.ts
packages/amplify-graphql-relational-transformer/src/resolver/generator.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-relational-transformer/src/schema.ts
packages/amplify-graphql-relational-transformer/src/types.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

Adds `references` support for DDB data sources when defining `@hasOne` relationships.
- Adds `HasOneDirectiveDDBReferencesTransformer`
- Fixes input types in `RelationalResolverGenerator` abstract class and some method signatures.
- Adds some logic in the `getHasOneDirectiveTransformer` to unlock use references implementation for `hasOne`.
- Adds `hasOne` resolver implementation.
- Adds (start of) unit test in `amplify-graphql-has-one-references-transformer.test.ts`
None
N/A

feat(graphql-relational-transformer): add ddb references support for hasOne directive

---

packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-transformer-factory.ts

Small fix to branching logic when determining fields vs references in relational transformers.
Dependent on https://github.com/aws-amplify/amplify-category-api/pull/2380
None
N/A

fix(graphql-relational-transformer): fix references vs fields branching logic

---

packages/amplify-graphql-relational-transformer/src/resolvers.ts

Adds missing support for sort keys on generated GSIs on the related model DDB table in the new `references` world.
Example schema
```graphql
type Foo @model {
id: ID! @primaryKey(sortKeyFields: ["baz", "quux"])
baz: String!
quux: Int!
bar: Bar @hasOne(references: ["fooID", "fooBaz", "fooQuux"])
}
type Bar @model {
id: ID!
fooID: ID
fooBaz: String
fooQuux: Int
foo: Foo @belongsTo(references: ["fooID", "fooBaz", "fooQuux"])
}
```
None
N/A
Unit and manual E2E testing

fix(graphql-relational-transformer): properly create sortkey for generated gsi on related table

---

packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-references-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-references-transformer.test.ts

Adds some more unit tests for has-many references based relationships with DDB data sources.
None
N/A
Unit tests passing.

test(graphql-relational-transformer): add some more unit tests for has-many references ddb

---

codebuild_specs/release_workflow.yml

Our current release workflow allows a `deploy` even if prior steps fail. In a production release this isn't of practical concern since we have prior flows that correctly check things like API consistency, license files, and yarn.lock. However in a tagged release, we intentionally bypass a lot of those previous steps, so it's possible to deploy a tagged release even if prior steps failed.
This change makes the `deploy` step depend on all previous steps.

chore: fix release workflow build dependencies

---

codebuild_specs/release_workflow.yml

This reverts commit f671eca05c0b5ab1ae703f230bd8242e674728d4.
The change in https://github.com/aws-amplify/amplify-category-api/pull/2407 set dependencies so that a deploy would not kick off if any of the validations fail. However, CodeBuild expects build steps to produce an artifact by default, so deployments now fail with an error:
```
[no objects found under S3 prefix for dependency artifact verify_yarn_lock verify_yarn_lock no objects found under S3 prefix for dependency artifact verify_dependency_licenses_extract verify_dependency_licenses_extract no objects found under S3 prefix for dependency artifact verify_cdk_version verify_cdk_version no objects found under S3 prefix for dependency artifact verify_api_extract verify_api_extract]
```
I attempted to defines the validation steps …

Revert "chore: fix release workflow build dependencies (#2407)"

---

packages/amplify-graphql-api-construct-tests/src/__tests__/deploy-velocity/3-gsis-100k-records.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/deploy-velocity/deploy-velocity-constants.ts

Increase the timeout of `3-gsis-100k-records.test.ts` test to 45 minutes.
Adjusting the timeout for `3-gsis-100k-records.test.ts` E2E test based on local testing. This test took anywhere between 23 - 38 while testing in local. Based on this data, adjusting the no output timeout to 45 minutes.

test(api): increase no output time for gsi 100k records e2e test

---

packages/amplify-graphql-api-construct/src/__tests__/__functional__/resources.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts

The Amplify customers can have a schema like that is shown below, 
```
type Query {
generateRandomNumber: Int
}
```
where they only have custom GraphQL operations. These custom GraphQL operations do not use any lambda function as their datasource but have their computation logic within the custom AppSync resolvers. These custom resolvers need a `NONE` type datasource which we do not generate by default. This leads to failures in Gen2 deployments for customers following [this guide](https://docs.amplify.aws/gen2/build-a-backend/data/custom-business-logic/#step-2---configure-custom-business-logic-handler-code) since we [default to a datasource](https://github.com/aws-amplify/amplify-api-next/blob/7d9865b72123e5d714ead5e3f82df5f49da24208/packages/data-schema/src/Handler.ts#L64) named …

feat: adds a default none data source

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-field-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/acm-test-library.ts
packages/amplify-graphql-auth-transformer/src/__tests__/rds-field-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts

Currently if related models use the same dynamic group field type then their datatype is incorrectly overridden by the last model processed. This is due to the way the roles are stored in a data structure in auth transformer. This PR fixes it by adding model name to the role name in the internal data structure.
```graphql
type User 
@model 
@auth(rules: [
{ allow: groups, groups: ["Admin"] },
{ allow: public, operations: [get] },
{ allow: groups, groups: ["Dev"], operations: [read] }
{ allow: groups, groupsField: "groupsField", operations: [update, delete] }
])
{
id: String! @primaryKey
name: String
groupsField: String
profile: Profile @hasOne(references: ["userId"])
}
type Profile 
@model 
@auth(rules: [
{ allow: groups, groups: ["Admin"] },
{ allow: public, operations: [list] },
{ …
```

fix(api): dynamic auth fields use correct data type on related models

---

codebuild_specs/e2e_workflow.yml
scripts/split-e2e-tests.ts

We no longer need to run the SQL field auth tests in just ICN since the AppSync Auth util fixes have been deployed to all regions. Removing this override from our `split-e2e` script randomizes the region they run in like any other E2E test.
Full E2Es passed

chore: remove region override for field auth tests

---

packages/amplify-category-api/API.md
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-model-v2.ts
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/amplify-graphql-model-transformer/src/resources/rds-model-resource-generator.ts
packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-core/src/utils/resource-name.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/model-datasource/types.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/amplify-graphql-transformer-test-utils/API.md
packages/amplify-graphql-transformer-test-utils/src/test-transform.ts
packages/amplify-graphql-transformer/API.md
packages/amplify-graphql-transformer/src/graphql-transformer.ts
packages/graphql-transformer-common/API.md
packages/graphql-transformer-common/src/ResourceConstants.ts

This change removes the hard-coded account number of the SQL Lambda Pipeline that is used to construct the SNS Topic ARN, subscribed to by the SQL lambda patcher.
The alternative approach that is implemented here is to fetch the service vended SNS Topic ARN per region from the SQL manifest bucket using a custom resource that is deployed to the customer's account for Gen2 deployments. 
For Gen1 deployments, we read it from the manifest bucket directly during the build step since Async operations are allowed. The necessary backend changes are already deployed. This approach is no different from the one we use fetch the SQL Lambda layer mapping from the manifest bucket and was already discussed with the team.
**Related API changes:** The API changes supporting this will be very similar to …

feat: Fetch SNS topic ARN from SQL manifest

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts

This bug was introduced in https://github.com/aws-amplify/amplify-category-api/pull/2236
* A field with null name is included when timestamps are removed with `@model(timestamps: { createdAt/updatedAt: null })`.
```
type Foo @model(timestamps: { updatedAt: null }) {
id: ID!
title: String!
}
```
This results in schema deploy error because of field named `null`.
```
input ModelFooConditionInput {
title: ModelStringInput
and: [ModelFooConditionInput]
or: [ModelFooConditionInput]
not: ModelFooConditionInput
createdAt: ModelStringInput
null: ModelStringInput // should not be included
}
```
* Bad filter inputs are added when timestamps are removed with `@model(timestamps: null)`
```
type Foo @model(timestamps: null) {
id: ID!
title: String!
}
```
Schema deploys fine in this case.
```
input …
```

fix: remove null timestamp fields from filter input

---

packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-references-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-one-references-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-references-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-references-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/data-source-based-directive-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-belongs-to-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/resolver/ddb-references-generator.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts

Adds missing support for references based relationships where the primary model has a primary key with a composite sort key and the Related model uses a DynamoDB table as a data source.
```graphql
type Primary @model {
tenantId: ID! @primaryKey(sortKeyFields: ["instanceId", "recordId"])
instanceId: ID!
recordId: ID!
content: String
related: [Related!] @hasMany(references: ["primaryTenantId", "primaryInstanceId", "primaryRecordId"])
}
type Related @model {
content: String
primaryTenantId: ID!
primaryInstanceId: ID!
primaryRecordId: ID!
primary: Primary @belongsTo(references: ["primaryTenantId", "primaryInstanceId", "primaryRecordId"])
}
```
In this example, `primaryInstanceId` and `primaryRecordId` are the composite sort key of the global secondary index created on the `Related` model's …

fix(graphql-relational-transformer): ddb references relationships with composite sortkeys

---

packages/amplify-graphql-schema-generator/API.md
packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate-ts-data-schema.test.ts.snap
packages/amplify-graphql-schema-generator/src/__tests__/generate-ts-data-schema.test.ts
packages/amplify-graphql-schema-generator/src/ts-schema-generator/helpers.ts
packages/amplify-graphql-schema-generator/src/ts-schema-generator/ts-schema-generator.ts
packages/graphql-transformer-common/API.md
packages/graphql-transformer-common/src/TypescriptSchemaConstants.ts

Add identifier to the generated typescript data schema file. This identifier is later used with `defineData` to construct an unique datasource strategy ID.
NA
NA
- New unit tests
- Manual test

fix(api): add identifier to generated ts data schema

---

packages/amplify-graphql-api-construct-tests/src/__tests__/deploy-velocity/replace-2-gsis-update-attr-100k-records.test.ts

Change the GSI 2K update E2E timeout to 45 minutes.
- replace-2-gsis-update-attr-100k-records.test.ts

chore(api): increase gsi e2e test timeout to 45 minutes

---

packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-provider-fields.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-userpool-fields.ts
packages/amplify-graphql-name-mapping-transformer/src/__tests__/__integ__/__snapshots__/with-has-many.test.ts.snap
packages/amplify-graphql-name-mapping-transformer/src/__tests__/__integ__/__snapshots__/with-has-one.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-belongs-to-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-one-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/resolver/rds-generator.ts

Fix: Relational directive hasMany, hasOne and belongsTo respect owner rule on the related type.
Example: In the below schema, primary.relatedMany and related.primary must respect the owner rule on the corresponding model.
```graphql
type Primary @model @auth(rules: [{ allow: owner }]) {
id: String! @primaryKey
owner: String
relatedMany: [RelatedMany] @hasMany(references: ["primaryId"])
}
type RelatedMany @model @auth(rules: [{ allow: owner }]) {
id: String! @primaryKey
owner: String
primaryId: String
primary: Primary @belongsTo(references: ["primaryId"])
}
```
NA
NA (Internal Ticket)
- New E2E Tests
- Manual test

fix(api): protect sql relational fields when using owner rule

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/API.md
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/resolvers/common.ts
packages/amplify-graphql-model-transformer/src/resolvers/dynamodb/mutation.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/mutation.ts
packages/amplify-graphql-model-transformer/src/resources/model-resource-generator.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-one-references-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap

The auto generated ID is missing when timestamps are removed `@model(timestamps: null)`. This PR fixes that issue. This PR also remove auto id for id fields with type Float, Int, and Boolean.
The auto ID is used in these cases (see test cases for schemas):
* explicit id with type ID
* explicit id with type String
* auto id is not used for other types (Float, Int, Boolean)
* implicit id
N/A
Resolves: https://github.com/aws-amplify/amplify-category-api/issues/978
* Unit tests
* E2E tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:bcb694d0-590a-4c36-9137-33cb41354d32?region=us-east-1
By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix: auto generated id when timestamps: null

---

.github/CODEOWNERS

Adjust some of the CODEOWNERS rules:
- We already allow `e2e_workflow.yml` to be approved by team rather than admin, so also allow team approval for changes to `scripts/split-e2e-tests.ts`
- Require admin approval for CODEOWNERS file
- Sorted the CI/CD scripts section

chore: only require team approval for scripts/split-e2e-tests.ts

---

packages/amplify-graphql-auth-transformer/src/__tests__/iam-access.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-references-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-one-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-references-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-references-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-sql-transformer.ts
packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/data-source-based-directive-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-one-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-sql-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-sql-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-transformer-factory.ts
packages/amplify-graphql-relational-transformer/src/resolver/ddb-references-generator.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-relational-transformer/src/types.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

- Adds bidirectional validation for references based relationships.
- Improves error messages for invalid schema / directive scenarios.
- Updates necessary tests -- error message assertions, schemas / relevant snapshots
Docs PR: https://github.com/aws-amplify/docs/pull/7222
N/A
N/A
- Unit tests
- [E2E tests](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:328eb397-5107-41ee-b919-e07eca87a122?region=us-east-1)

fix: relational bidirectionality validation and improved error messages

---

packages/amplify-e2e-core/src/utils/rds.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/sql-models-2.test.ts
packages/amplify-graphql-api-construct-tests/src/sql-datatabase-controller.ts
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/src/__tests__/__functional__/sql-model-strategy.test.ts
packages/amplify-graphql-api-construct/src/__tests__/internal/data-source-config.test.ts
packages/amplify-graphql-api-construct/src/internal/data-source-config.ts
packages/amplify-graphql-api-construct/src/model-datasource-strategy-types.ts
packages/amplify-graphql-api-construct/src/sql-model-datasource-strategy.ts
packages/amplify-graphql-model-transformer/rds-lambda/handler.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/amplify-sql-resource-generator.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/amplify-sql-resource-generator.test.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/amplify-graphql-model-transformer/src/resources/rds-model-resource-generator.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/model-datasource/types.ts

With this feature, we will allow the customers of Amplify GraphQL CDK construct to specify more than one SSM paths that hold the connection URI for the SQL database. This enables customers of Amplify Console to have both shared and branch specific secrets for database connection URIs.
The provided SSM paths are resolved in the order that is specified in the array by the customer and based on the availability to read them at runtime during execution of the SQL Lambda datasource.
This PR also updates the error messages to make them more readable.
The change is backwards compatible since existing customers can continue to specify the connection URI SSM path as a single string.
Added unit and E2E tests. The added E2E test runs successfully on CI.
By submitting this pull request, I confirm …

feat: support multiple connection Uris for SQL databases

---

packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts

* set installLatestAwsSdk on AwsCustomResource to false
```
installLatestAwsSdk was not specified, and defaults to true. You probably do not want this. Set the global context flag '@aws-cdk/customresources:installLatestAwsSdkDefault' to false to switch this behavior off project-wide, or set the property explicitly to true if you know you need to call APIs that are not in Lambda's built-in SDK version.
```
`installLatestAwsSdk` set to false. https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cx-api/FEATURE_FLAGS.md#aws-cdkcustomresourcesinstalllatestawssdkdefault
N/A
* Unit tests
* E2E tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:67bc453c-41aa-4623-b3ff-5fb3f2180d …

fix: set installLatestAwsSdk on AwsCustomResource to false

---

packages/amplify-graphql-model-transformer/src/__tests__/amplify-sql-resource-generator.test.ts
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
packages/amplify-graphql-model-transformer/src/resources/rds-model-resource-generator.ts
packages/amplify-graphql-transformer-core/src/transform-host.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transform-host-provider.ts

Adds a tag and a description to the Lambda function provisioned for SQL data sources.
We will use the description field in an upcoming PR to override the Lambda Layer version for CDK-based tests.

feat: add tag to SQL datasource function

---

codebuild_specs/scripts/local_publish_helpers.sh
shared-scripts.sh

New helper function to publish local workspace to local Verdaccio registry.

chore: add local publish helper for release verification against amplify-backend

---

codebuild_specs/scripts/local_publish_helpers.sh

This adds some quoting to the Verdaccio publish helper script to work around shell errors in log inspection that I encountered on my local workstation.

chore: quote log references in verdaccio scripts

---

codebuild_specs/e2e_workflow.yml
packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-5.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/simple-todo/attributeTypeChange/app.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.ts
packages/amplify-graphql-transformer-core/API.md

Fix the bug: Attribute type changes are not reflected in amplify managed tables.
To resolve this, we will delete all the indexes referencing the attribute with type changes and recreate them.
NA
NA
- Manual test
- New E2E test

fix(api): handle attribute type change on gsi

---

packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NonModelAuthFunction.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts

Add the below condition to the auth and unauth roles created by E2E tests. This restricts the role to be assumed only by the users authenticated by the identity pool which was created as part of the same test project.
```
'StringEquals': {
'cognito-identity.amazonaws.com:aud': { Ref: 'IdentityPool' },
}
```

test: restrict auth and unauth role conditions on e2e

---

codebuild_specs/publish_to_local_registry.yml
shared-scripts.sh

We've seen the below error during Git operations like fetching tags on CI:
```
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
```
There is a [community recommended workaround](https://gist.github.com/daopk/0a95772d582cafb202142ff7871da2fc) by changing the Http version and increasing the max buffer size to receive larger response payloads.

chore: update config to avoid errors during Git operations on CI

---

codebuild_specs/e2e_workflow.yml
packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/src/internal/default-parameters.ts
packages/amplify-graphql-api-construct/src/types.ts
packages/amplify-graphql-auth-transformer/src/__tests__/relational-field-redaction.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-transformer-core/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer/src/__tests__/graphql-transformer.test.ts
packages/amplify-util-mock/src/__e2e__/utils/index.ts
packages/graphql-transformers-e2e-tests/src/__tests__/RelationalWithAuthV2NonRedacted.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/RelationalWithAuthV2Redacted.e2e.test.ts
yarn.lock

Allow subscriptions to inherit primary model auth rules for relational fields if `subscriptionsInheritPrimaryAuth` is set to `true`.
NA
TODO: To be updated later.
- New E2E tests
- New unit tests

feat: allow subscriptions to inherit primary model auth rules for relational fields behind a feature flag

---

packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
yarn.lock

Upgrade JSII dependency, as current version is EOL as of 30-Jun-2024.
- Build passes
- After release, will ensure new [graphql-api-construct](https://constructs.dev/packages/@aws-amplify/graphql-api-construct) and [data-construct](https://constructs.dev/packages/@aws-amplify/data-construct) versions appear on ConstructHub as expected

chore: upgrade jsii

---

packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate-ts-data-schema.test.ts.snap
packages/graphql-transformer-common/src/TypescriptSchemaConstants.ts

Change the SSL certificate property in the generated typescript data schema to `sslCert`.
NA
NA
- Updated unit tests

fix(amplify-category-api): ssl cert api name change

---

packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/API.md
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-api-construct/src/__tests__/__functional__/disable-gen1-patterns.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/internal/default-parameters.ts
packages/amplify-graphql-api-construct/src/types.ts
packages/amplify-graphql-relational-transformer/src/graphql-belongs-to-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-one-transformer.ts
packages/amplify-graphql-transformer-core/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer/API.md
packages/amplify-graphql-transformer/src/__tests__/graphql-transformer.test.ts
packages/amplify-graphql-transformer/src/graphql-transformer.ts
packages/amplify-util-mock/src/__e2e__/utils/index.ts

Add translation behavior to disable gen 1 patterns:
* Use of `@manyToMany`
* Use of `@searchable`
* Use of `@predictions`
* Use of `fields` argument on `@hasOne`, `@hasMany`, and `@belongsTo`.
* Use of `@hasOne`, `@hasMany`, and `@belongsTo` on required fields.
* Add `allowGen1Patterns` which defaults to `true`.
N/A
* Unit testing

fix: add translation behavior to disable gen 1 patterns

---

packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-1.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-3.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-4.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/rate-limit/createTableTtl/app.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/rate-limit/updateTableTtl/disabled/app.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/simple-todo/app.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/simple-todo/updateIndex/app.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/simple-todo/updateKeySchema/enabled/app.ts
packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/amplify-dynamodb-table-generator.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/amplify-table-manager-lambda.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/amplify-table-manager-lambda.test.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamo-model-resource-generator.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/cfn-response.ts
yarn.lock

Amplify Gen 2 applies some default tags to make it easy for customers to use resource explorer or "MyApplications" to browse their app's resources. The tags are applied on the CFN level and typically (automatically) applied onto the underlying AWS resources by CFN. Because we use a custom resource for DynamoDB tables, these tags aren't automatically applied.
This PR fixes that issue by copying the tags from the resource provision lambda and assign it to the tables.
No.
NA.
- New E2E tests
- Manual test

fix: add tags to dynamodb tables

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/__snapshots__/ecs-apigw-stack.test.ts.snap
packages/amplify-category-api/src/provider-utils/awscloudformation/base-api-stack.ts

With the CDK version upgrade the runtime version of the custom resource lambda changed from 16 to 18. With the runtime change the lambda code needed be changed to account for breaking changes between 16 and 18. However, the S3 key for the zip file containing the lambda code was not changed, even though the hash of code has changed. During the CFN deploy if the S3 key for the lambda code is unchanged the lambda code will not be updated. 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html
> Changes to a deployment package in Amazon S3 or a container image in ECR are not detected automatically during stack updates. To update the function code, change the object key or version in the template.
This resulted in the runtime version being …

fix: update awaiter s3 key

---

packages/amplify-graphql-api-construct-tests/src/__tests__/migration/many-to-many-migration.test.ts
packages/amplify-graphql-directives/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-graphql-directives/src/directives/belongs-to.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-belongs-to-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/graphql-belongs-to-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-many/has-many-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/has-one/has-one-directive-ddb-references-transformer.ts
packages/amplify-graphql-relational-transformer/src/types.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

Add `overrideIndex` name to `@belongsTo` to change the name of the GSI that is automatically created with references.
See above.
N/A
* Unit testing
* E2E testing

feat: add overrideIndexName to configure index name

---

packages/amplify-e2e-core/src/utils/rds.ts

Print the full error object while making a call to the data api.

fix(amplify-category-api): data api call print the full error object

---

packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Added stale RDS instance cleanup steps in the scheduled cleanup workflow
The stale instances meet the following requirements:
- DB identifier contains `integtest`
- Status is `available`
- Has been created more than 2 hours
Run cleanup script locally with temp credential from e2e parent account

chore: add stale rds instances cleanup in scheduled workflow

---

packages/amplify-graphql-api-construct-tests/src/sql-datatabase-controller.ts

This fixes the failures we observed with SQL tests when the randomly generated/RDS managed database password has special characters and is not encoded.
Ran the canary with changes and verified that tests now pass.

fix: encode password to handle special chars

---

packages/amplify-graphql-api-construct-tests/src/__tests__/migration/migration-validation.test.ts
yarn.lock

* add additional migration validation test cases
N/A
N/A
* Run the tests

test: add additional migration validation test cases

---

CONTRIBUTING.md

Update CONTRIBUTING.md to specify Node version v18.x. 
`yarn && yarn build && yarn test` yields `error jsii@5.4.23: The engine "node" is incompatible with this module. Expected version ">= 18.12.0". Got "16.20.2"` on Node version v16.x
n/a
n/a
ran this by @phani-srikar

docs(contributing): ✏️ require node v18.x

---

codebuild_specs/e2e_workflow.yml
packages/amplify-e2e-core/src/utils/rds.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/sql-pg-canary.test.ts
packages/amplify-graphql-api-construct-tests/src/sql-datatabase-controller.ts
packages/amplify-graphql-api-construct-tests/src/utils/sql-local-testing.ts
packages/amplify-graphql-api-construct-tests/src/utils/sql-pre-provisioned-cluster.ts
scripts/split-e2e-tests.ts

Update the SQL E2E test setup to be able to use the pre-provisioned cluster. Use `sql-pg-canary` test to run in parent account and `us-east-1` region that has the pre-provisioned cluster.
Ran the updated test

test: use pre provisioned cluster

---

packages/amplify-graphql-transformer-core/API.md
packages/amplify-graphql-transformer-core/src/__tests__/utils/function-runtime-test.ts
packages/amplify-graphql-transformer-core/src/appsync-function.ts
packages/amplify-graphql-transformer-core/src/transform-host.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-graphql-transformer-core/src/utils/function-runtime.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/graphql-api-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transform-host-provider.ts

This change is only applicable to the transformer internals -- it does not expose a way for customers to specify the runtime of a resolver function.
Note: The changes made to accomplish this are the minimal changes necessary, not necessarily the best way. A more appropriate way of supporting JS runtime would be adding overloads or additional optional properties specifying `code` / `codeS3Location`. This is likely what we should do when adding support for handling `a.handler.custom({})` in the transformer. In the meantime, I favored minimal risk over ideal approach for this change.
* Conditionally added support for `Code` based AppSync Functions: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html#cfn-appsync-functionconfiguration-c …

allow specifying JS runtime when creating resolver functions within transformer

---

client-test-apps/js/api-model-relationship-app/package.json

Client canary failures started after the Jest 29 upgrade (#2747) was merged to `main`. I was able to resolve locally by restoring the `moduleNameMapper` config to the canary's `package.json`.

test: Restore modulemapper to jest config in client canary

---

codebuild_specs/scripts/publish.sh
scripts/cloud-release.sh

Update triggering codebuild projects from current branch instead of using fixed branch names.
Add `api-plugin-stable` as known reserved tag so we prevent developers from using it during tag release workflows.

chore: use current branch for triggering release flow

---

packages/amplify-graphql-api-construct/src/__tests__/__functional__/disable-gen1-patterns.test.ts
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts

* don't print deprecation warning when pattern is not used
N/A
https://github.com/aws-amplify/amplify-category-api/issues/2803
* Unit tests

fix: don't print deprecation warning when pattern is not used

---

packages/amplify-e2e-core/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-graphql-api-construct-tests/package.json
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-default-value-transformer/package.json
packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-index-transformer/package.json
packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-name-mapping-transformer/package.json
packages/amplify-graphql-predictions-transformer/package.json
packages/amplify-graphql-relational-transformer/package.json
packages/amplify-graphql-schema-test-library/package.json
packages/amplify-graphql-searchable-transformer/package.json
packages/amplify-graphql-sql-transformer/package.json
packages/amplify-graphql-transformer-test-utils/package.json
packages/amplify-graphql-transformer/package.json
packages/graphql-transformers-e2e-tests/package.json

The following private packages used for unit/E2E testing are cause clashes of git tags published during the release from `main` and `release-api-plugin-stable` branches. Bumping the major versions for these to be able to deploy from both branches.
- amplify-category-api-e2e-core
- amplify-category-api-e2e-tests
- @aws-amplify/graphql-transformer-test-utils
- amplify-category-api-graphql-transformers-e2e-tests
CI checks

chore: bump private package versions

---

packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/package.json
yarn.lock

Updates `@aws-amplify/ai-constructs` from `^0.1.1` to `^0.1.2` to pull in this fix that addresses a problem with bundledDependencies and re-exported bedrock client stuff.
- https://github.com/aws-amplify/amplify-backend/pull/1962

fix: update ai-constructs to 0.1.2

---

codebuild_specs/amplify_ddb_canary.yml
codebuild_specs/default_ddb_canary.yml
codebuild_specs/sql_mysql_canary.yml
codebuild_specs/sql_pg_canary.yml

The upgraded version of `jest` consumes more memory that 3GB allocated in small sized containers. Bumping the size to medium gives upto 7GB.
Triggering canary run on top of these changes

chore: use medium sized containers for canaries

---

packages/amplify-category-api/package.json
packages/amplify-e2e-core/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-default-value-transformer/package.json
packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-index-transformer/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-name-mapping-transformer/package.json
packages/amplify-graphql-predictions-transformer/package.json
packages/amplify-graphql-relational-transformer/package.json
packages/amplify-graphql-searchable-transformer/package.json
packages/amplify-graphql-transformer-test-utils/package.json
packages/amplify-util-mock/package.json
packages/graphql-transformers-e2e-tests/package.json

Update the versions for private packages common b/w main and stable branches to the latest versions already published from `main` previously. This was identified when the `lerna publish` flow tried to push the git tags for these packages.
Following Git tags that were published for versions that don't yet exist on NPM as part of this old commit - https://github.com/aws-amplify/amplify-category-api/commit/f3ec4c4bdd1e9780b05878448031b6557403907b are deleted from Github.
- [graphql-mapping-template@4.21.0](https://github.com/aws-amplify/amplify-category-api/releases/tag/graphql-mapping-template%404.21.0)
- [graphql-auth-transformer@8.0.0](https://github.com/aws-amplify/amplify-category-api/releases/tag/graphql-auth-transformer%408.0.0)
- …

chore: update private package versions

---

packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/conversation.test.ts
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/package.json
yarn.lock

- Bumps `ai-constructs` dependency to `0.1.3` to **not** bundle the AWS SDK for the conversation route happy path (implicit lambda generation). This is done to prevent customers from needing to install `@aws-sdk/client-bedrock-runtime` as a dependency in their project. Here's the [backend PR for reference](https://github.com/aws-amplify/amplify-backend/pull/1969).
- Removes `@aws-sdk/client-bedrock-runtime` from `additionalDependencies` in conversation directive E2E tests.

chore(conversation-transformer): bump ai-constructs version

---

packages/amplify-graphql-directives/src/directives/function.ts
packages/amplify-graphql-function-transformer/src/__tests__/__snapshots__/amplify-graphql-function-transformer.test.ts.snap
packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer.test.ts
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts

Addresses feedback from
- https://github.com/aws-amplify/amplify-category-api/pull/2864
- Adds response mapping template snapshots for chained function directive test cases.
- misc. cleanup

test(function-transformer): add snapshots for chained functions

---

packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/package.json
yarn.lock

Bumps `ai-constructs` dependency to 0.1.4 to pull in this change:
- https://github.com/aws-amplify/amplify-backend/pull/1988
N/A
See linked backend PR for description of issue.
[E2E run](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:1a0e7580-1d94-41ce-a1eb-1f41fe7447a1?region=us-east-1)

chore(ai): bump ai-constructs to 0.1.4

---

packages/amplify-graphql-default-value-transformer/src/__tests__/__snapshots__/amplify-grapphql-default-value-transformer.test.ts.snap
packages/amplify-graphql-default-value-transformer/src/__tests__/amplify-grapphql-default-value-transformer.test.ts
packages/amplify-graphql-default-value-transformer/src/graphql-default-value-transformer.ts
packages/amplify-graphql-directives/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-graphql-directives/src/directives/default.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/utils/model-datasource-strategy-utils.ts

Transformer changes to support auto increment (`serial`) fields on Postgres datasources. Accomplished by making the 'create' input types optional when `@default` is applied.
1. Definition of `@default` has changed, its `value: String` parameter is now optional.
2. `default-value-transformer` allows no `value` on Int fields if the datasource is Postgres
3. Unit tests for the above
n/a
[Original Project Outline](https://quip-amazon.com/hM5jA6kb73o8/Support-Auto-Increment-and-Computed-fields-for-SQL-databases-Intern-Project-Plan)
[Design Doc](https://quip-amazon.com/OnyqA5tt6BdB/Design-Auto-Increment-Fields)
[API Doc](https://quip-amazon.com/nGiBATc29vbC/Generated-SQL-Field-API-Naming-Review)
Unit tests, _existing_ e2e tests, `testTransform`. Will write e2e test after implementing changes to …

feat: auto increment support

---

package.json
yarn.lock

Add resolutions for `path-to-regexp` scoped to `@aws-amplify/amplify-appsync-simulator`. It is ok to use resolutions here because `@aws-amplify/amplify-appsync-simulator` is only used in packages that are not published to NPM.
N/A
N/A
* E2E tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow%3A2310de89-c4dd-443e-b066-d48aa7963a4e?region=us-east-1

chore: add resolutions for path-to-regexp scoped to @aws-amplify/amplify-appsync-simulator

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
packages/amplify-graphql-model-transformer/src/resources/model-resource-generator.ts
packages/amplify-graphql-transformer-core/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer/src/__tests__/graphql-transformer.test.ts
packages/graphql-transformer-common/API.md
packages/graphql-transformer-common/src/ResourceConstants.ts

This reverts commit 02c7da0da0d5837ca05a8e4ff1b1536cc20ae15b.
Remove migration changes for Gen 1 CLI. The change has been moved to the stable branch: https://github.com/aws-amplify/amplify-category-api/pull/2896
---

Revert "feat: get datasource map for migration (#2668)"

---

shared-scripts.sh

Verify against backend't latest release instead of latest main.

update: fetch latest release tag

---

packages/amplify-graphql-api-construct-tests/src/commands.ts
packages/graphql-transformers-e2e-tests/src/cdkUtils.ts

Removes CDK bootstrap step in test code, in favor of out-of-band bootstrap stack management.
E2E tests that were previously failing due to missing `iam:UpdateAssumeRolePolicy` permissions during the bootstrap phase are no longer failing due to those missing permissions.

test: remove bootstrap in test code

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/resolvers/dynamodb/query.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-one-references-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap

Renames invalid `IndexName` key to valid `index` for generated model list queries.
The VTL data resolver for DynamoDB data sources in generated model list queries contains a code path that (as far as I can tell) is never hit. 
```vtl
#if( !$util.isNull($ctx.stash.metadata.index) )
#set( $ListRequest.IndexName = $ctx.stash.metadata.index )
#end
```
I'm confident it's never hit because `IndexName` is an invalid key to include in the request function evaluation for the only two DDB operations this resolver function can initiate -- Scan and Query. The correct key is `index`.
AppSync Documentation References
- [Query](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-resolver-mapping-template-reference-dynamodb-query.html)
- …

fix(model-transformer) IndexName -> index in query list resolver

---

packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/init-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/resolvers/init-resolver.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/invoke-lambda-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/resolvers/invoke-lambda-resolver.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts

Resources that reference 
```
"Fn::GetAtt": [
"GraphQLAPI",
"GraphQLUrl",
],
```
are not hot-swappable. This is a CDK constraint. 
The `invoke-lambda` resolver function currently references `ctx.api.graphqlUrl` in the resolver code. In addition to the GraphQLUrl, the `invoke-lambda` resolver function also contains the `systemPrompt`, `aiModel`, and `inferenceConfiguration` values defined in a conversation route / `@conversation` directive.
This is less than ideal because any changes to `systemPrompt`, `aiModel`, and/or `inferenceConfiguration` cannot hotswap today.
This change moves the `ctx.api.graphqlUrl` / `"Fn:GetAtt": ["GraphQLAPI", "GraphQLUrl"]` reference into the existing `init` resolver function. In turn, changes to `systemPrompt`, `aiModel`, and/or `'inferenceConfiguration` are …

fix(conversation): allow changes to systemPrompt, inferenceConfig, aiModel to be hotswapped

---

dependency_licenses.txt
packages/amplify-graphql-conversation-transformer/API.md
packages/amplify-graphql-conversation-transformer/package.json
packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-handler.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-inference-configuration-template.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-missing-ai-model.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-return-type.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool-with-relationships.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-with-inference-configuration.graphql
packages/amplify-graphql-conversation-transformer/src/grapqhl-conversation-transformer.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts
packages/amplify-graphql-transformer-test-utils/API.md
packages/amplify-graphql-transformer-test-utils/src/test-transform.ts
packages/amplify-graphql-transformer/src/graphql-transformer.ts
yarn.lock

> Related data-schema PR https://github.com/aws-amplify/amplify-api-next/pull/361
Updates ConversationTransformer to allow `functionMap?: record<string, lambda.IFunction>` to be passed. This is done to properly reference a custom conversation handler defined via `defineConversationHandlerFunction` in a Gen2 backend.
- New test case asserting `functionMap` value is used for Lambda data source.

fix(conversation): use functionMap for custom handler IFunction reference

---

packages/amplify-graphql-api-construct-tests/src/sql-tests-common/schemas/sql-models/schema.graphql
packages/amplify-graphql-api-construct-tests/src/sql-tests-common/sql-models.ts

This removes a test case from #2883 that was causing failures in e2e tests.
[E2E Codebuild](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow%3A23119b44-bdb8-4718-a57a-a8b93e2e42e3?region=us-east-1)

fix: sql default value e2e failures

---

packages/amplify-graphql-api-construct-tests/src/__tests__/generations/graphql/schema-generation.graphql
packages/amplify-graphql-generation-transformer/src/__tests__/__snapshots__/amplify-graphql-generation-transformer.test.ts.snap
packages/amplify-graphql-generation-transformer/src/resolvers/invoke-bedrock.ts

If an `inferenceConfiguration` is specified in a `@generation` directive, it creates invalid JS code due to a trailing comma, resulting in a failed deployment.
- Removes trailing comma.
- Adds `inferenceConfiguration` to an E2E test case to catch related regressions in the future.
N/A
N/A
Ran the generation E2E tests locally.

fix(generation): remove trailing comma in inferenceConfig resolver code

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-transformer-core/src/graphql-api.ts

break circular dependency in setupLogConfig with scoped down policy

---

packages/amplify-graphql-schema-generator/src/__tests__/generate-schema.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/generate-ts-data-schema.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/input.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/mysql-string-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/pg-datasource-adapter.test.ts
packages/amplify-graphql-schema-generator/src/__tests__/pg-string-datasource-adapter.test.ts

Small cleanup changes from while I was working on #2952.
This pull request focuses on cleaning/updating test cases in the `amplify-graphql-schema-generator` package. The most important changes include replacing `toThrowError` with `toThrow` for exception assertions, removing unnecessary `await` keywords, and cleaning up imports in several test files.
**N/a**
**N/a**
Root level `yarn test`

chore: cleanup imports and update deprecated jest functions

---

codebuild_specs/scripts/lint_pr.sh
packages/amplify-graphql-conversation-transformer/API.md
packages/amplify-graphql-conversation-transformer/package.json
packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-handler-deprecated.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-custom-handler-event-version.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-custom-handler-function-name-and-handler-provided.graphql
packages/amplify-graphql-conversation-transformer/src/grapqhl-conversation-transformer.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts
packages/amplify-graphql-directives/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-graphql-directives/src/directives/conversation.ts
yarn.lock

Change how `@conversation` directive accepts custom conversation handler.
From:
```
@conversation(
aiModel: "anthropic.claude-3-haiku-20240307-v1:0", 
systemPrompt: "Hello, world!",
functionName: "FnCustomHandlerChatBot",
eventVersion: '1.0'
)
```
To:
```
@conversation(
aiModel: "anthropic.claude-3-haiku-20240307-v1:0", 
systemPrompt: "Hello, world!",
handler: {
functionName: "FnCustomHandlerChatBot",
eventVersion: '1.0'
}
)
```
While still accepting older version. Older version will be removed upon GA.
This is a companion PR to https://github.com/aws-amplify/amplify-backend/pull/2089 .
And a pre-requisite for https://github.com/aws-amplify/amplify-api-next/pull/369 .
These PRs setup a versioning for the event protocol between conversation route resolvers and lambda handler.
The protocol …

feat: constrain custom conversation handler event version

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/src/__tests__/__functional__/authorizer.ts
packages/amplify-graphql-api-construct/src/__tests__/__functional__/metadata.test.ts
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-api-construct/src/internal/metadata.ts

Add additional metrics metadata for `authorizationMode` and `customOperations`. The metric data is stored in the CFN stack description.
```typescript
{
"metadata": {
"dataSources": "dynamodb,mysql,postgres", // exists today
// new fields below
/*
Possible options
'aws_iam',
'openid_connect',
'amazon_cognito_identity_pools',
'amazon_congnito_user_pools',
'api_key',
'aws_lambda',
*/
"authorizationModes", "api_key,aws_lambda",
"customOperations": "queries,mutations"
}
}
```
The metrics are stored in the CFN description. No real functional change, but the descriptions will be updated.
N/A
* Unit tests

feat: add metrics metadata for auth mode and custom operations

---

packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/API.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/conversation.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/mutations.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/queries.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/subscriptions.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/test-implementations.ts
packages/amplify-graphql-conversation-transformer/src/graphql-types/session-model.ts

- Enables model generated update mutation on `Conversation<RouteName>` model type for conversation routes.
- Adds E2E test for update conversation mutation.
- codegen: https://github.com/aws-amplify/amplify-codegen/pull/895
- data-schema: https://github.com/aws-amplify/amplify-api-next/pull/365
Release ordering:
1./2. `amplify-category-api` and `amplify-codegen`. Note: Ideally `amplify-category-api` first, but it's not entirely necessary.
3. `amplify-api-next`. This must go last to ensure the update API in the data client hits an existing GraphQL mutation field.
N/A
N/A
- CI PR Workflow
- Added E2E test -- [E2E run](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/build/amplify-category-api-e2e-workflow%3A1b69a8eb-18c3-4b0 …

feat(conversation): enable update mutations on conversation model

---

packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/assistant-response-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/assistant-response-subscription-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/generate-resolver.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/list-messages-init-resolver.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/resolver-function-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/send-message-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts

Fixes two issues introduced in https://github.com/aws-amplify/amplify-category-api/pull/2957
1. uses inline template for `init` slot in send message mutation to work around `Fn:GetAtt:GraphQLUrl` not resolving in S3 Asset based templates.
2. fixes incorrect data source for assistant response mutation resolver.
This also adds test assertions for expected data sources and snapshots for the remaining resolver functions generated within the conversation transformer.
N/A
N/A
- manually tested
Note: I'm working on adding support for subscriptions in the E2E test package to mitigate the risk of these silly regressions in the future.

fix(conversation): inline template for init slot and correct datasource in assistant response mutation

---

codebuild_specs/cleanup_workflow.yml

Setup the node version to the defined version to let the cleanup workflow work build and work as expected, and have resources cleanup back to normal operation.
CI cleanup workflow.

fix: override the node version to have the cleanup workflow work

---

packages/amplify-graphql-api-construct-tests/src/utils/sql-pre-provisioned-cluster.ts

This PR let the E2E has correct region setting when trying to get manifest information about the pre-provisioned resource.
CI checks.

fix: use correct region setting for the pre-provisioned resource

---

packages/amplify-graphql-api-construct-tests/package.json
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/conversation.test.ts
packages/amplify-graphql-api-construct-tests/src/utils/appsync-graphql/subscription.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/assistant-messages-subscription-resolver-fn.template.js
yarn.lock

- Adds basic support for subscriptions in `amplify-graphql-api-construct-tests` ([reference](https://github.com/aws-amplify/amplify-category-api/pull/2983/files#diff-c9ad0a23d671ba2265df0aa91d87cb7722267d349fa3964326b29355e078de6e))
- Updates existing happy path E2E test to assert on assistant response through subscription. ([reference](https://github.com/aws-amplify/amplify-category-api/pull/2983/files#diff-455f8729f27403b483bf84b6e8bdcc5afe0ea696ba56209ffcbc7141507cebb3R75-R110))
- Adds negative owner auth test asserting that user's cannot receive events from another user's conversation. ([reference](https://github.com/aws-amplify/amplify-category-api/pull/2983/files#diff-455f8729f27403b483bf84b6e8bdcc5afe0ea696ba56209ffcbc7141507cebb3R171-R248))
- Includes correct auth filter in …

test(conversation): add subscription based e2e tests

---

dependency_licenses.txt
packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/API.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/conversation.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/mutations.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/queries.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/schema-conversation.graphql
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/subscriptions.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/test-implementations.ts
packages/amplify-graphql-api-construct-tests/src/utils/appsync-graphql/subscription.ts
packages/amplify-graphql-api-construct-tests/src/utils/duration-constants.ts
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/package.json
packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-schema-types.graphql
packages/amplify-graphql-conversation-transformer/src/conversation-directive-configuration.ts
packages/amplify-graphql-conversation-transformer/src/graphql-types/message-model.ts
packages/amplify-graphql-conversation-transformer/src/graphql-types/name-values.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/assistant-response-stream-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/index.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/send-message-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/assistant-streaming-mutation-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/invoke-lambda-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-field-handler.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-prepare-handler.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts
yarn.lock

- Adds support for streaming assistant responses.
- Updates E2E test cases for streaming.
- Adds E2E test case for streaming with client tools.
- Adds snapshot test cases for streaming resolvers.
The key change here is that the lambda function sends chunks / events to the assistant response mutation rather than a full message.
**Example**
Bedrock streaming response “hello world” is broken up into two chunks “hello” and “ world”. 
```js
// first event
{ 
// mutation response 
conversationId: '123',
associatedUserMessageId: 'abc',
contentBlockIndex: 0,
contentBlockDeltaIndex: 0,
contentBlockText: 'hello',
// persisted in messages table
accumulatedTurnContent: [{ text: 'hello' }]
}
// second event
{
// mutation response  
conversationId: '123',
associatedUserMessageId: 'abc', …
```

feat(conversation): support response streaming

---

packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/conversation.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/test-implementations.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/graphql-types/name-values.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/index.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/list-conversations-init-resolver-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/list-messages-init-resolver-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/list-messages-post-processing-resolver-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/send-message-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/list-conversations-init-set-index-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/list-messages-init-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/list-messages-init-set-index-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/list-messages-post-processing-resolver-fn.template.js
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/set-updated-at-conversation-table-fn.template.js
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts

The current `listConversationMessages` query uses a GSI to return messages ordered by `createdAt`. That GSI is:
- Name: `gsi-ConversationMessage.conversationId.createdAt`
- PK: `conversationId`
- SK: `createdAt`
The model generated list query does a DynamoDB Scan operation.
These messages are retrieved in ascending order because that is the only option for DynamoDB Scan operations. This is seemingly what we want -- most recent message as the final element. This ordering matches what a user interface would expect and is required by Bedrock's Converse API. It is, however, problematic for long running conversations with messages exceeding the provided `limit` argument. In these cases, the most recent messages are omitted. What we actually want is to retrieve the messages from the DynamoDB …

feat(conversation): sorting and performant list queries

---

packages/amplify-category-api/src/index.ts
yarn.lock

When overrides building fails. The root cause is eaten. Which makes troubleshooting impossible.
This PR includes root cause in Amplify error.
Similarly to this https://github.com/aws-amplify/amplify-cli/blob/b40e8e86f00b84737dd499ab05e2158b2b4c4315/packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts#L125 .

fix: Include root cause when overrides build fails.

---

packages/amplify-category-api/src/index.ts

When overrides building fails. The root cause is eaten. Which makes troubleshooting impossible.
This PR includes root cause in Amplify error.
Similarly to this https://github.com/aws-amplify/amplify-cli/blob/b40e8e86f00b84737dd499ab05e2158b2b4c4315/packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts#L125 .
(copied from https://github.com/aws-amplify/amplify-category-api/pull/3004 , targeting correct branch)

fix: include root cause when overrides build fails

---

packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/schema-conversation.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-handler-deprecated.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-handler.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-inference-configuration-template.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-custom-handler-event-version.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-custom-handler-function-name-and-handler-provided.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-missing-ai-model.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-missing-system-prompt.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-return-type.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool-with-relationships.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-with-inference-configuration.graphql
packages/amplify-graphql-directives/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-graphql-directives/src/directives/conversation.ts

- https://github.com/aws-amplify/amplify-api-next/pull/384
The `@conversation` directive implicitly uses owner auth (cognito user pool) for associated models and operations because it's the only supported option. 
In the future, we may want to extend conversation routes to additional authorization strategies. When that time comes, we'll be forced to make a decision between:
1. implicit owner auth by default, opt into new authorization strategies
**--- or ---**
2. breaking change (forcing explicit authorization definition)
We're not going to support additional authorization strategies by GA, but we are making the decision to go with _2. breaking change (forcing explicit authorization definition)_ already. We're doing this now while we can so that we don't have to make a difficult decision …

feat(conversation): require auth input for conversation directive

---

packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/package.json
yarn.lock

- Bumps `ai-constructs` to `^0.8.1`.
**Relevant `ai-constructs` PR:**
- https://github.com/aws-amplify/amplify-backend/pull/2195
N/A
N/A
N/A

chore: bump ai-constructs to ^0.8.1

---

packages/amplify-data-construct/.jsii
packages/amplify-graphql-api-construct/.jsii

`release` was manually synced back to `main` with https://github.com/aws-amplify/amplify-category-api/commit/9530eabc669d519eed397ecdcc2bc94f8c54585d.
This didn't trigger the typical `chore: update .jsii assembly` flow.
Updates the .jsii assembly for graphql-api-construct and data-construct.

chore: update .jsii assembly

---

packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/schema-conversation.graphql

One of the E2E test cases for the conversation transformer doesn't include the newly introduced (and required) `auth` directive argument (https://github.com/aws-amplify/amplify-category-api/pull/3007).
Adds missing `auth` argument to E2E test case.
N/A
N/A
- [E2E test run](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow%3A923382dd-b7cf-4d34-9857-cca5a58a2191?region=us-east-1)

test(conversation): add missing auth input in e2e test

---

packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
packages/amplify-graphql-conversation-transformer/API.md
packages/amplify-graphql-conversation-transformer/package.json
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/grapqhl-conversation-transformer.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts
packages/amplify-graphql-transformer/API.md
packages/amplify-graphql-transformer/package.json
packages/amplify-graphql-transformer/src/graphql-transformer.ts

The default lambda handler deployed for conversation routes via `ai-constructs` doesn't stream function logs for sandbox deployments when using the `--stream-function-logs` flag ([documentation](https://docs.amplify.aws/react/build-a-backend/functions/streaming-logs/)).
- Plumb `outputStorageStrategy` from `AmplifyGraphqlApi` through the `ConversationTransformer` to `ai-constructs`.
This allows `ai-constructs` to include the conversation handler Lambda function in the root stack outputs for streaming.
> [!NOTE]
> https://github.com/aws-amplify/amplify-category-api/pull/3014 contains an alternative approach that also works, but involves duplicating the types into `amplify-graphql-transformer-interfaces`.
**Relevant Backend PR**
- https://github.com/aws-amplify/amplify-backend/pull/2073
N/A …

fix: plumb outputStorageStrategy through conversation transformer to handler

---

packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-tool-definition-missing-fields.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-tool-definition-mixed-fields.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-tool-name.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-mixed-tools.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool-with-relationships.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/conversation-directive-configuration.ts
packages/amplify-graphql-conversation-transformer/src/tools/process-tools.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-field-handler.ts
packages/amplify-graphql-directives/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-graphql-directives/src/directives/conversation.ts

- https://github.com/aws-amplify/amplify-api-next/pull/390
1. Customers wanting to use generated model queries as tools for conversation routes must know the name of the generated model query in advance.
```graphql
type Todo @model @auth(rules: [{ allow: owner }]) {
content: String
isDone: Boolean
}
type Mutation {
chat(
conversationId: ID!,
content: [ContentBlockInput],
aiContext: AWSJSON,
toolConfiguration: ToolConfigurationInput
): ConversationMessage
@conversation(
aiModel: "anthropic.claude-3-haiku-20240307-v1:0",
systemPrompt: "You are a helpful chatbot. Answer questions to the best of your ability.",
tools: [
{
name: "listTodos",  # <--- must match query name
description: "lists todos",
},
],
auth: { strategy: owner, provider: userPools },
)
}
```
2. The name of a tool must be the …

feat(conversation): update directive input for tool definition for model list queries

---

packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/API.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/conversation.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/mutations.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/schema-conversation.graphql
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/test-implementations.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/conversation-field-handler.test.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-handler-deprecated.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-handler.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-custom-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-inference-configuration-template.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-custom-handler-event-version.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-custom-handler-function-name-and-handler-provided.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-missing-ai-model.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-missing-system-prompt.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-return-type.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-tool-definition-missing-fields.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-tool-definition-mixed-fields.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-invalid-tool-name.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-mixed-tools.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool-with-relationships.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-with-inference-configuration.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-schema-types.graphql
packages/amplify-graphql-conversation-transformer/src/graphql-types/message-model.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-field-handler.ts

- https://github.com/aws-amplify/amplify-api-next/pull/395
- https://github.com/aws-amplify/amplify-codegen/pull/907
Conversation routes add several GraphQL types (type, input, enum, interface) to the GraphQL schema. These types are only added if a conversation route is defined via the `@conversation` directive and are conversation route agnostic (only added once per GraphQL schema regardless of the amount of conversation routes).
These types have generic enough names that they can conflict with customer defined types. 
<details>
<summary>GraphQL Types</summary>
```graphql
enum ConversationParticipantRole {
user
assistant
}
interface ConversationMessage {
id: ID!
conversationId: ID!
associatedUserMessageId: ID
role: ConversationParticipantRole
content: [ContentBlock]
aiContext: AWSJSON …
```

fix(conversation): prefix supporting types with AmplifyAI 

---

packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/resolvers/send-message-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/invoke-lambda-resolver-fn.template.js
packages/amplify-graphql-generation-transformer/src/__tests__/__snapshots__/amplify-graphql-generation-transformer.test.ts.snap
packages/amplify-graphql-generation-transformer/src/resolvers/invoke-bedrock-resolver-fn.template.js
packages/amplify-graphql-generation-transformer/src/resolvers/invoke-bedrock.ts

The `x-amz-user-agent` header is sent by the data client to AppSync queries and mutations. These headers are not forwarded to the underlying data sources.
AppSync resolver includes `x-amz-user-agent` header in requests to applicable underlying data sources:
- **Generation Route:** Amazon Bedrock via HTTP Data Source
- **Conversation Route:** AWS Lambda function*
> *Lambda function already includes `x-amz-user-agent` header in requests to Bedrock and back to AppSync
> See https://github.com/aws-amplify/amplify-backend/pull/2181 and https://github.com/aws-amplify/amplify-backend/pull/2086
For requests made from the data client, an `x-amz-user-agent` header is included ([reference](https://github.com/aws-amplify/amplify-api-next/pull/339)).
The resolver function for conversation and …

fix(ai): forward user-agent with package metadata in generation and conversation requests

---

packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-generation-transformer/src/__tests__/__snapshots__/amplify-graphql-generation-transformer.test.ts.snap
packages/amplify-graphql-generation-transformer/src/__tests__/amplify-graphql-generation-transformer.test.ts

https://github.com/aws-amplify/amplify-category-api/pull/3029 introduced an issue with snapshot tests where they'll fail whenever a new version is used.
This fixes that by mocking the package version.

test: mock package version in conversation and generation for snapshot tests

---

packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool-with-relationships.graphql
packages/amplify-graphql-conversation-transformer/src/tools/process-tools.ts

The tool definition input for the `@conversation` directive allows customers to specify a `model` and `modelOperation`. For example:
```ts
const schema = a.schema({
Appointment: a.model({
time: a.timestamp(),
}).authorization((allow) => [allow.authenticated()]),
appointmentChat: a.conversation({
aiModel: a.ai.model("Claude 3.5 Sonnet"),
systemPrompt: `You are a friendly pet groomer who is helping with giving advice and selling clients on booking appointments.
You like grooming pets in creative ways, such as technicolor dye jobs, fun shaped cuts, and nail polish.
You should ask me more questions to learn about what I need in a grooming appointment.`,
tools: [
a.ai.dataTool({
name: 'getAppointmentTimes',
description: 'Searches for available appointments',
model: a.ref('Appointment'), …
```

fix(conversation): model list tool query name infinite recursion

---

packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/package.json
yarn.lock

Bumps `ai-constructs` dependency to `^1.0.0`.
N/A
N/A
- [E2E test run](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:68a6b480-0d76-4c87-80d2-fbc9f9cf3e8d?region=us-east-1)

fix: bump ai-constructs to ^1.0.0

---

packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/package.json
yarn.lock

PR to initiate API construct release.
The only change here is
- https://github.com/aws-amplify/amplify-category-api/pull/3040
Full E2E was run on the PR ([reference)](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow%3A68a6b480-0d76-4c87-80d2-fbc9f9cf3e8d?region=us-east-1). All tests passed with the exception of `PredictionsTransformerV2Tests`, which is an unrelated failure that is addressed in https://github.com/aws-amplify/amplify-category-api/pull/3041.
```
> git rev-parse origin/main^
022b19ef3b739f4cbdf6ed0bcb1cfc18ee38ef92
> git rev-parse origin/bump-ai-constructs^
022b19ef3b739f4cbdf6ed0bcb1cfc18ee38ef92
```

chore: merge main into release

---

codebuild_specs/e2e_workflow.yml
scripts/split-e2e-tests.ts

The `PredictionsTransformerV2Tests` E2E test case always passes locally buy has consistently failed in CI for a while now with the error:
```
TypeError: Invalid URL
18 |
19 |   async query(query: string, variables: any = {}): Promise<GraphQLResponse> {
> 20 |     const axRes = await axios.post<GraphQLResponse>(
|                               ^
21 |       this.url,
22 |       {
23 |         query,
at dispatchHttpRequest (../../node_modules/axios/lib/adapters/http.js:232:20)
at ../../node_modules/axios/lib/adapters/http.js:152:5
at wrapAsync (../../node_modules/axios/lib/adapters/http.js:132:10)
at http (../../node_modules/axios/lib/adapters/http.js:170:10)
at Axios.dispatchRequest (../../node_modules/axios/lib/core/dispatchRequest.js:51:10)
at Axios._request …
```

test: exclude unsupported region for PredictionsTransformerV2 E2E

---

packages/amplify-graphql-transformer-core/src/graphql-api.ts

Removed param doc for `getAppSyncLogGroupName` since it's not needed. 

chore: nit fix getAppSyncLogGroupName doc

---

packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-model-query-tool.graphql
packages/amplify-graphql-conversation-transformer/src/tools/process-tools.ts

An error is thrown at synth if a GraphQL enum field is included in the return type of a data tools used in conversation routes. When the selection set (used by conversation lambda handler) is generated, we're only checking `isScalar` to determine if we need to:
1.  use the `fieldName` by itself.
2. get the object type, then traverse that object's fields. Resulting in `fieldName { <nested fields> }`. 
If 2. we attempt to get the `ObjectTypeDefinitionNode` for that field's type name via `ctx.output.getObject(typeName)`. For enums this, logically, results in no `ObjectTypeDefinitionNode` found, where we throw an error `"Could not find type definition for <type-name>"`. 
Change the applicable `isScalar` checks to `isScalarOrEnum`. 
N/A
N/A
- Updated schema for test case and snapshot
- [E2E …

fix(conversation): handle enums in data tool selection sets

---

packages/graphql-transformers-e2e-tests/package.json
yarn.lock

Fix for [dependabot alert #150](https://github.com/aws-amplify/amplify-category-api/security/dependabot/150). `path-to-regexp` is used by package `@aws-amplify/amplify-appsync-simulator`, which is the dependency of `amplify-category-api-graphql-transformers-e2e-tests`.
`path-to-regexp` version is bumped to 0.1.12.

chore: dependabot alert fix #150

---

dependency_licenses.txt
package.json
yarn.lock

This package is our only dev dep that is not compatible with node 20. Upgrade to version that is compatible.
This will allow us to upgrade to node 20 in the future (which we should be doing at some point to improve jest performance).
---

style: upgrade eslint-plugin-jsdoc to ^50.6.1

---

packages/amplify-graphql-api-construct/jest.config.js
packages/amplify-graphql-api-construct/src/__tests__/index-import.test.ts
packages/amplify-graphql-api-construct/src/index.ts
packages/amplify-graphql-api-construct/src/types.ts

Suppress reexport and type-only files from coverage metrics in specified package.
Local test

chore[@aws-amplify/graphql-category-api]: suppress reexport and type-only files from coverage metrics

---

client-test-apps/js/api-model-relationship-app/package.json
shared-scripts.sh

The transitive dependencies for the client canary test app now require atleast v20 node. This PR pins these deps to versions that allow us to test min CLI supported version i.e node 18.
Running `yarn` with updated version installs dependencies successfully.
Also re-ran the canary flow with latest change and it succeeds.

fix: make canary deps compatible with node 18

---

packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/API.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/conversation.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/schema-conversation.graphql
packages/amplify-graphql-api-construct-tests/src/__tests__/conversations/graphql/subscriptions.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/graphql-types/message-model.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/send-message-pipeline-definition.ts
packages/amplify-graphql-conversation-transformer/src/resolvers/templates/assistant-streaming-mutation-resolver-fn.template.js

- Adds optional (for backwards compatibility) `p: String` field to the `CreateConversationMessage<RouteName>AssistantStreamingInput` type.
- Generates `p` value in `createAssistantResponseStream<RouteName>` resolver.
N/A
N/A
Manually validated with example Gen 2 application that:
- `p` is returned in event chunk subscription.
- A `p` value provided in mutation input (from Lambda) gets precedence.
[E2E Full Run](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:616b2757-2f36-4e9b-a481-5c474c2ca3ed?region=us-east-1)
[E2E conversation run post test updates](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-c …

fix(conversation): add padding to stream chunks

---

packages/amplify-graphql-validate-transformer/src/__tests__/invalid-directive-use.test.ts
packages/amplify-graphql-validate-transformer/src/__tests__/test-utils.ts
packages/amplify-graphql-validate-transformer/src/validators.ts

- add `validateOrderingWithDefaultDirective` to throw `InvalidDirectiveError` if `@validate` comes before `@default`
- updat `test-utils.ts` to include default transformer for testing
- unit tests added to test different combinations of ordering `@validate` and `@default`

add directive ordering enforcement between `@validate` and `@default`

---

packages/amplify-graphql-model-transformer/rds-lambda/dsql-helpers.ts
packages/amplify-graphql-model-transformer/rds-lambda/handler.ts
packages/amplify-graphql-model-transformer/rds-lambda/package.json
packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts

This PR introduces IAM-based authentication support for DSQL database connections in SQL lambda, enhancing our current authentication capabilities.
The implementation leverages existing SSM parameter to store the connection string, following our existing credential storage strategy for Gen2 brownfield support. Connection strings will follow the format `postgres://hostname:port/database`, with DSQL hosts identified by the `*.dsql.*.on.aws` domain pattern.
Authentication will use the default `admin` user, with database credentials dynamically generated using `DsqlSigner` helper methods provided by the SDK. This approach provides a flexible and secure method for establishing database connections while maintaining our infrastructure's existing patterns.
**Key Changes**
- Implement IAM …

feat(graphql-model-transformer): add dsql support for sql lambda

---

packages/amplify-graphql-model-transformer/src/__tests__/import-table.test.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/import-table.ts

Sort table description properties before comparing. `lodash.isEqual` is order sensitive when comparing arrays. Some properties on the TableDescription are arrays and can be given in a non-deterministic order. This change ensures the comparison is correct by sorting AttributeDefinitions, KeySchema, and GlobalSecondaryIndexes properties on the imported and expected description before comparing.
N/A
N/A
* Unit tests
* I didn't add E2E tests for this because it is difficult (maybe not possible) to ensure the order in E2E tests.

fix: sort table description properties before comparing

---

packages/amplify-graphql-api-construct-tests/src/__tests__/backends/validate-transformer/app.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/validate-transformer/__templates__/README.md
packages/amplify-graphql-api-construct-tests/src/__tests__/validate-transformer/validate-transformer-e2e.test.ts
packages/amplify-graphql-api-construct-tests/src/utils/validate-transformer-helper.ts

This PR adds e2e tests that send CREATE/UPDATE mutation queries to verify the validation logic. 
- Added a CDK app with USER and PRODUCT model types with a lot of validate directives
- Added some e2e helpers and e2e tests with the following structure:
```
User Type Tests
├── Valid Cases
│   ├── Create Operations
│   └── Update Operations
└── Invalid Cases
├── Create Operations
└── Update Operations
Product Type Tests
├── Valid Cases
│   ├── Create Operations
│   └── Update Operations
└── Invalid Cases
├── Create Operations
└── Update Operations
```
Small changes:
- Updated [`__templates__/README.md`](https://github.com/aws-amplify/amplify-category-api/pull/3165/files#diff-5afe0b49a420bd18cd39610a1cb38a62b0d62baacab5669efd31f5d5b207fafe)
- [e2e (`validate_transformer_evaluate_mapping` and …

feat: add e2e tests for validate directive

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/__tests__/graphql-transformer/transform-graphql-schema-v1.test.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v1.ts
packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
packages/amplify-graphql-model-transformer/src/resources/model-resource-generator.ts
packages/amplify-graphql-transformer-core/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer/src/__tests__/graphql-transformer.test.ts
packages/amplify-util-mock/src/__e2e__/utils/index.ts
packages/graphql-transformer-common/API.md
packages/graphql-transformer-common/src/ResourceConstants.ts
yarn.lock

* Add transformer option `enableGen2Migration`.
* Set dynamodb table data source removal policy to retain when true.
* Output a mapping of model name to table name when true.
* This will be exposed as a feature flag to gen 1 customers.
New behavior is not exposed through the construct because migration is not supported from construct to gen 2.
N/A
* Add transformer option `enableGen2Migration`.
* Set dynamodb table data source removal policy to retain when true.
* Output a mapping of model name to table name when true.

Gen1 migration

---

packages/amplify-graphql-api-construct-tests/src/__tests__/validate-transformer/.gitignore
packages/amplify-graphql-api-construct-tests/src/__tests__/validate-transformer/README.md
packages/amplify-graphql-api-construct-tests/src/__tests__/validate-transformer/validate-transformer-evaluate-mapping-template.test.ts
packages/amplify-graphql-api-construct-tests/src/utils/validate-transformer-helper.ts

- Git ignore `__templates__` and move `README.md` to `__tests__/validate-transformer/README.md`. 
- Added `#region` markers
[e2e](https://tiny.amazon.com/1bbvyr5pb/IsenLink)

chore: address previous comments

---

.github/workflows/run-pr-e2e.yaml

This PR fixes the consistent failure of `run-pr-e2e` GitHub action by specifying `bash` shell. 

chore: update github workflow to use `.` instead of `source`

---

packages/amplify-graphql-api-construct-tests/src/__tests__/migration/migration-validation.test.ts
packages/amplify-graphql-api-construct-tests/src/commands.ts
packages/amplify-graphql-model-transformer/src/__tests__/amplify-dynamodb-table-generator.test.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamo-model-resource-generator.ts

Add ddb deletion protection on imported tables
See above.
The deletionProtection param does not seem to be exposed for non-imported tables. This PR does not change that.
N/A
Add unit tests.

feat: add ddb deletion protection on imported tables

---

packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Current e2e cleanup script is not capturing some new test IAM roles created by the newly added android, swift, ts canaries. This PR adds `-integtest-` to match these test roles so they can be properly cleaned up. 

fix: add `-integtest-` to role regex in e2e cleanup script

---

dependency_licenses.txt
package.json
yarn.lock

This PR pins `@octokit/request-error`, `@octokit/request`, and `@octokit/plugin-paginate-rest` to patched versions to address the following dependabot alerts relating to `@octokit` versions: 
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/168
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/169
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/170

fix: pin octokit to secure versions for Gen1

---

dependency_licenses.txt
package.json
yarn.lock

This PR pins `@octokit/request-error`, `@octokit/request`, and `@octokit/plugin-paginate-rest` to patched versions to address the following dependabot alerts relating to `@octokit` versions: 
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/168
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/169
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/170

fix: pin octokit to secure versions

---

packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-table-1.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/simple-todo/updateIndex/app.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/migration/migration-validation.test.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamo-model-resource-generator.ts

Change the DynamoDB tables SSE config to use the AWS owned key instead of AWS managed key by default.
**Reason:** AWS managed keys incur additional charges and it is not the best option to be the default.
> **Note:** When SSE is undefined, it doesn't mean SSE is disabled, it means DynamoDB will use AWS owned key.
NA
NA

fix: use aws owned key as default for ddb sse

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/__tests__/graphql-transformer/transform-graphql-schema-v1.test.ts
packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v1.ts
packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
packages/amplify-graphql-model-transformer/src/resources/model-resource-generator.ts
packages/amplify-graphql-transformer-core/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer-interfaces/API.md
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transform-parameters.ts
packages/amplify-graphql-transformer/src/__tests__/graphql-transformer.test.ts
packages/amplify-util-mock/src/__e2e__/utils/index.ts
packages/graphql-transformer-common/API.md
packages/graphql-transformer-common/src/ResourceConstants.ts
yarn.lock

* Add transformer option `enableGen2Migration`.
* Set dynamodb table data source removal policy to retain when true.
* Output a mapping of model name to table name when true.
* This will be exposed as a feature flag to gen 1 customers.
The feature flag is now released on the Gen 1 CLI, so there shouldn't be any issue of the FF missing this time.
New behavior is not exposed through the construct because migration is not supported from construct to gen 2.
N/A
E2E tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:fa875e4f-1dbe-4c60-90f8-44eb2b838fe0?region=us-east-1
* Add transformer option `enableGen2Migration`.
* Set dynamodb table data source removal policy to retain when …

feat: gen 1 migrations

---

packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v1.ts

There is a typo on one occurrence of `enableGen2Migration` feature flag with an extra `s` on the end causing canaries to fail.
```
Flag 'enablegen2migrations' within 'graphqltransformer' is not registered in feature provider
```
There is no production impact currently because the package has not been updated in the CLI yet.
---

fix: typo on enableGen2Migration

---

shared-scripts.sh

- `Category-api canary` fails as it is not able to access `node_modules` from `S3` cache folder
- adding `rm -rf node_modules` to `loadCacheFromBuildJob` to fix the issue
- Validated changes on Code Build [test run](https://594813022831-qxxvc3uq.us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-canary-workflow/batch/amplify-category-api-canary-workflow%3Aa0481944-5327-4e1f-aabd-36cf14b69cb6?region=us-east-1#)

chore: remove node modules before loading cache in shared scripts

---

packages/amplify-graphql-model-transformer/src/__tests__/amplify-dynamodb-table-construct.test.ts
packages/amplify-graphql-model-transformer/src/__tests__/amplify-dynamodb-table-generator.test.ts
packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamodb-table-construct/index.ts

Add grantStreamRead to amplify managed table. This allows searchable to be used on Amplify managed tables for the purpose of migrations. The function does the same thing as the one on the Table construct: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.Table.html#grantwbrstreamwbrreadgrantee
N/A
* Unit tests
* Manual tests

feat: add grantStreamRead to amplify managed table

---

packages/amplify-graphql-auth-transformer/src/__tests__/iam-custom-operations.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts

fix: remove aws_iam directive incorrectly added to interfaces

---

packages/amplify-e2e-core/src/utils/credentials-rotator.ts
packages/amplify-e2e-tests/src/rds-v2-tests-common/rds-auth-oidc-fields.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/migration/many-to-many-migration.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/migration/migration-validation.test.ts
packages/amplify-graphql-api-construct-tests/src/__tests__/sql-pg-models.test.ts
shared-scripts.sh

Some long running e2e tests can have their creds expire after an hour. Based on recent failures, add credentials refresher to those e2e tests.
Extend credentials rotator to refresh child AWS accounts as well.

chore: refresh creds in some long running e2e tests

---

packages/graphql-transformers-e2e-tests/resources/jsonServer/yarn.lock
yarn.lock

Attempt to fix https://github.com/aws-amplify/amplify-category-api/security/dependabot/205 .
Note: this PR may not address all of of the warnings because we also depend on `aws-cdk-lib` which bundles `brace-expansion`. However, it should knock out at least 2/3 of them.

chore: bump brace-expansion

---

.vscode/settings.json
packages/amplify-graphql-model-transformer/rds-lambda/package.json
packages/amplify-graphql-model-transformer/rds-lambda/tsconfig.json
shared-scripts.sh

Cherry pick 
1. https://github.com/aws-amplify/amplify-category-api/pull/3324
2. https://github.com/aws-amplify/amplify-category-api/pull/3322
To fix canaries and tests on gen1 branch.

chore: fix tests on gen1 branch

---

.vscode/settings.json
packages/amplify-data-construct/.jsii
packages/amplify-data-construct/package.json
packages/amplify-graphql-api-construct/.jsii
packages/amplify-graphql-api-construct/package.json
packages/amplify-graphql-conversation-transformer/README.md
packages/amplify-graphql-conversation-transformer/package.json
packages/amplify-graphql-conversation-transformer/src/__tests__/__snapshots__/amplify-graphql-conversation-transformer.test.ts.snap
packages/amplify-graphql-conversation-transformer/src/__tests__/amplify-graphql-conversation-transformer.test.ts
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-with-cross-region-inference-disabled.graphql
packages/amplify-graphql-conversation-transformer/src/__tests__/schemas/conversation-route-with-cross-region-inference-enabled.graphql
packages/amplify-graphql-conversation-transformer/src/conversation-directive-configuration.ts
packages/amplify-graphql-conversation-transformer/src/transformer-steps/conversation-resolver-generator.ts
packages/amplify-graphql-directives/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-graphql-directives/src/directives/conversation.ts
packages/amplify-graphql-model-transformer/rds-lambda/package.json
packages/amplify-graphql-model-transformer/rds-lambda/tsconfig.json
shared-scripts.sh
yarn.lock

This PR introduces the `crossRegionInference` parameter to the `@conversation` GraphQL directive and creates new tests to cover the new feature. This sets up for complete cross-region inference support for AI conversation routes by passing through user preferences from the GraphQL schema into the Lambda conversation handler and underlying Bedrock resource resolution logic in `amplify-backend`
* Added optional `crossRegionInference` parameter to `@conversation` directive schema.
* Updated directive configuration type to include `crossRegionInference: boolean`
* Passed `crossRegionInference` into default conversation handler setup.
* Updated resolver generation logic to handle `crossRegionInference` parameter when building Lambda configuration.
* Updated snapshots and directive definitions …

feat(ai): add crossRegionInference parameter to conversation directive system

---

shared-scripts.sh

- Increase npm fetch retry min timeout from 30 seconds to 40 seconds
- Increase npm fetch retry max timeout from 3 minutes to 4 minutes

chore: increase npm fetch retry timeouts
