- .circleci/config.base.yml
Currently, subsequent builds are failing w/ some TSC errors. clean + build does work. adding this clean as a temporary mitigation.
N/A
Ran the build steps for the test.
> chore: update integration test to clean before setup-dev in order to mitigate the dup build failures

- package.json
- yarn.lock
Adding resolutions for dependabot alerts.
N/A
builds, unit tests run.
> chore: adding resolutions for dependabot alerts

- yarn.lock
`rm yarn.lock && yarn && yarn build`
N/A
Builds
> chore: rebuild yarn.lock file

- packages/amplify-category-api/package.json
- packages/amplify-util-mock/package.json
- yarn.lock
Updates the dependency on dynamodb simulator for util mock plugin.
Update yarn lock file.
> feat(amplify-category-api): update yarn lock after bumping package versions

- .circleci/config.base.yml
The package versions published locally are interfering with the main release to NPM. Disabling this temporarily.
> fix(ci-cd): remove local publish for release workflow

- package.json
- packages/amplify-e2e-tests/package.json
- packages/amplify-migration-tests/package.json
This PR fixes the e2e test setup by correcting the references to the e2e test environment, runner and reporter.
**Please Squash and Merge post approvals**
Ran unit and e2e tests (There are couple of test failures which will be fixed in `main`)
> Update the test environment, runner and reporter references

- Readme.md
> chore: no-op change to trigger pipelines

- Readme.md
> chore: no-op change to trigger pipelines (#545)

- package.json
Created a script called `hoist-cli-win` to be used by `setup-dev-win`. 
The new script `hoist-cli-win` is a translation of the `hoist-cli`, where:
1. `rm -rf` is replaced by `rimraf` 
2. `cp -r` is replaced by `xcopy /e /q`
3. `/` is replaced by `\\` in the path
[540](https://github.com/aws-amplify/amplify-category-api/issues/540) 
Validated by changing updating the scripts and running the setup again on Windows.
Created a script called `hoist-cli-win` to be used by `setup-dev-win`. 
The new script `hoist-cli-win` is a translation of the `hoist-cli`, where:
1. `rm -rf` is replaced by `rimraf` 
2. `cp -r` is replaced by `xcopy /e /q`
3. `/` is replaced by `\\` in the path …
> fix: Added Windows compatible translation of "hoist-cli" script

- package.json
- yarn.lock
Add a build target to refresh our lockfile, and updating our current lockfile.
N/A
Ran the target
> chore: add build target to refresh lockfile, and refreshing lockfile

- yarn.lock
Resolve conflicts between release and merge. Will use merge commits instead of squash ones
> Merge release to main

- .eslintrc.js
> Update linting rules

- packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
- packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
- packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
- packages/amplify-graphql-model-transformer/src/resolvers/query.ts
- packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
- packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
- packages/graphql-transformers-e2e-tests/src/__tests__/ModelTransformer.e2e.test.ts
Release the below items:
* fix(graphql): incorrect filter expression on model transformer
> API Category Release

- packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer-override.test.ts
- packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnOutput.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnParameters.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-layer-cfnMapping.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-datasource.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
- packages/amplify-graphql-searchable-transformer/src/definitions.ts
- packages/amplify-graphql-searchable-transformer/src/generate-resolver-vtl.ts
- packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
Fix lint error for `amplify-graphql-searchable-transformer`
> chore(searchable): fix lint errors

- packages/amplify-graphql-auth-transformer/src/__tests__/accesscontrol.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/acm.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/auth-operations.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/test-helpers.ts
Linting fixes for Auth V2 transformer package.
> chore(lint): Auth v2 transformer fix linting for test files

- packages/amplify-graphql-default-value-transformer/src/__tests__/__snapshots__/amplify-grapphql-default-value-transformer.test.ts.snap
- packages/amplify-graphql-default-value-transformer/src/__tests__/amplify-grapphql-default-value-transformer.test.ts
- packages/amplify-graphql-default-value-transformer/src/graphql-default-value-transformer.ts
- packages/amplify-graphql-default-value-transformer/src/validators.ts
Fix lint issues on default value transformer.
> chore(graphql): lint fix for default value transformer

- packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
- packages/amplify-graphql-auth-transformer/src/utils/index.ts
- packages/amplify-graphql-auth-transformer/src/utils/schema.ts
- packages/amplify-graphql-auth-transformer/src/utils/validations.ts
- packages/amplify-graphql-default-value-transformer/src/graphql-default-value-transformer.ts
- packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
- packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
- packages/amplify-graphql-index-transformer/src/graphql-index-transformer.ts
- packages/amplify-graphql-index-transformer/src/graphql-primary-key-transformer.ts
- packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
- packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
- packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
- packages/amplify-graphql-relational-transformer/src/graphql-belongs-to-transformer.ts
- packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
- packages/amplify-graphql-relational-transformer/src/graphql-has-one-transformer.ts
- packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts
- packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
- packages/amplify-graphql-transformer-core/src/__tests__/utils/directive-wrapper-test.ts
- packages/amplify-graphql-transformer-core/src/utils/directive-wrapper.ts
This allows public subscriptions to be generated on models, and adds use of a new feature flag to deep merge directive defaults. For a description of the behavior, see https://github.com/aws-amplify/amplify-cli/pull/10597
internally tracked
Unit testing and sample application
> Merge directive config

- packages/amplify-graphql-auth-transformer/src/__tests__/utils/warnings.test.ts
Refactor unit tests around owner auth warningm, and added a few more cases.
N/A
Unit test updates.
> chore: refactor unit tests around owner auth warning, add a few more cases

- packages/amplify-category-api/src/category-utils/context-util.ts
- packages/amplify-category-api/src/category-utils/schema-reader.ts
- packages/amplify-category-api/src/graphql-transformer/constants.ts
- packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
- packages/amplify-category-api/src/graphql-transformer/transformer-factory.ts
- packages/amplify-category-api/src/graphql-transformer/transformer-options-types.ts
- packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
re-add capability for single source read
temporarily not validated, adding as a no-op
> Single source schema

- packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
- packages/amplify-graphql-index-transformer/src/resolvers.ts
Refer https://github.com/aws-amplify/amplify-category-api/pull/811
> Release fix to sync query datastore issue

- .gitignore
This is to cover WebStorm IDE.
- [ x `yarn test` passes
> chore: add .idea to git ignore list

- packages/amplify-e2e-core/src/init/amplifyPush.ts
> Fix E2E core for changed CLI output

- .circleci/config.base.yml
- .circleci/config.yml
- .circleci/local_publish_helpers.sh
- packages/amplify-category-api/package.json
- packages/amplify-category-api/src/__tests__/force-updates/auth-notifications.ts
- packages/amplify-category-api/src/commands/api/add-graphql-datasource.ts
- packages/amplify-category-api/src/force-updates/auth-notifications.ts
- packages/amplify-category-api/src/force-updates/index.ts
- packages/amplify-category-api/src/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/pipeline-with-awaiter.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.ts
- packages/amplify-e2e-core/src/categories/api.ts
- packages/amplify-e2e-core/src/init/amplifyPush.ts
- packages/amplify-e2e-tests/schemas/circular_dependency_model.graphql
- packages/amplify-e2e-tests/src/__tests__/api_9.test.ts
- packages/amplify-e2e-tests/src/__tests__/graphql-v2/circular-dependency.test.ts
- packages/amplify-e2e-tests/src/__tests__/transformer-migrations/searchable-migration.test.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
- packages/amplify-graphql-auth-transformer/src/utils/index.ts
- packages/amplify-graphql-transformer-core/src/transformation/transform.ts
- packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
Merge main to cdkv2.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/1706/workflows/1e2c4101-3eef-4040-aaf6-507484a3a2f0
There are two new failing tests. They were added to main and suffer from known problem of:
```
? Select the plugin module to execute …  (Use arrow keys or type to filter)
❯ @aws-amplify/amplify-category-api@4.0.5
@aws-amplify/amplify-category-api@5.0.0
```
- [x ] PR description included
> chore: merge main to cdkv2

- packages/amplify-e2e-tests/src/__tests__/containers-api-1.test.ts
- packages/amplify-e2e-tests/src/__tests__/containers-api-2.test.ts
- packages/amplify-graphql-auth-transformer/src/resolvers/field.ts
- packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
- packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
- packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-relations-with-custom-primary-key.test.ts.snap
- packages/amplify-graphql-relational-transformer/src/resolvers.ts
- packages/graphql-transformers-e2e-tests/resources/jsonServer/yarn.lock
- packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2.e2e.test.ts
- scripts/split-e2e-tests.ts
- scripts/yarn.lock
> Release API Category

- client-test-apps/js/api-model-relationship-app/src/__tests__/utils/execUtils.ts
- packages/amplify-e2e-core/src/utils/nexpect.ts
Please read: https://github.com/aws-amplify/amplify-cli/pull/11133
The same issue is being addressed here.
> fix: redundant carriage return leads to unexpected behavior

- .circleci/config.base.yml
- .circleci/config.yml
- package.json
- packages/amplify-category-api/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json
- packages/amplify-dynamodb-simulator/package.json
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-tests/package.json
- packages/amplify-graphql-index-transformer/package.json
- packages/amplify-graphql-transformer-migrator/package.json
- packages/amplify-util-mock/package.json
- packages/graphql-transformer-core/package.json
- yarn.lock
> chore: update cli version

- scripts/update-cli-dependencies.sh
Make update-cli-dependencies a bit more flexible.
N/A
Tested in CLI repo.
> chore: update update-cli-depedencies script

- packages/amplify-category-api/src/__tests__/graphql-transformer/sandbox-mode-helpers.test.ts
- packages/amplify-category-api/src/graphql-transformer/sandbox-mode-helpers.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/field-auth-argument.test.ts.snap
- packages/amplify-graphql-auth-transformer/src/resolvers/field.ts
- packages/amplify-graphql-transformer-core/src/errors/index.ts
- yarn.lock
Squashing two PRs from ncarvajalc and reinstating the yarn.lock file.
N/A, see underlying commits.
Will run tests and e2e's.
E2E test run link: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/2371/workflows/b63802b4-90b5-4ef3-bc8e-7480c4086050
> Ncarvajalc merge

- packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
Allows stack mapping on function directive stack
Internally tracked
Manual testing
> Fix: allow mapping @function resolvers

- packages/amplify-graphql-schema-generator/package.json
- packages/amplify-graphql-schema-generator/src/index.ts
- packages/amplify-graphql-schema-generator/src/schema-representation/engine.ts
- packages/amplify-graphql-schema-generator/src/schema-representation/index.ts
- packages/amplify-graphql-schema-generator/src/schema-representation/schema.ts
- packages/amplify-graphql-schema-generator/src/schema-representation/types.ts
- packages/amplify-graphql-schema-generator/tsconfig.json
Adds interfaces and helper classes required to construct internal data representation for importing existing data sources.
> feat(api): interface and helpers for importing datasources

- packages/amplify-category-api/package.json
> No-op change to Re-Run release

- packages/amplify-graphql-schema-generator/package.json
- packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/index.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/mysql-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/index.ts
- packages/amplify-graphql-schema-generator/src/schema-representation/types.ts
- packages/amplify-graphql-schema-generator/tsconfig.json
- Add interface for describeTable.
- Add MySQL implementation for describeTable interface.
- Add datatype mapping (MySQL type -> Interface FieldType)
NA
- Manual test
> feat(graphql): mysql implementation for describe table interface

- packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
following the [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticsearch.CfnDomain.NodeToNodeEncryptionOptionsProperty.html), adding in this option to add encryption between nodes.
ran yarn test
- [n/a] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [n/a] Relevant documentation is changed or added (and PR referenced)
- [n/a] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
> chore: adding node-to-node encryption within cdk code

- .circleci/config.base.yml
- packages/amplify-category-api/src/__tests__/graphql-transformer/graphql-push-schema-checks.test.ts
- packages/amplify-category-api/src/graphql-transformer/api-utils.ts
- packages/amplify-category-api/src/index.ts
- packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts
- packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts
- packages/amplify-graphql-auth-transformer/src/resolvers/search.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
- packages/amplify-graphql-transformer-migrator/package.json
- packages/amplify-graphql-transformer-migrator/src/__tests__/migration/schema-migrator.test.ts
- packages/amplify-graphql-transformer-migrator/src/schema-inspector.ts
- packages/amplify-util-mock/package.json
- packages/amplify-util-mock/src/utils/lambda/load-lambda-config.ts
- packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts
- packages/amplify-util-mock/src/utils/lambda/populate-lambda-mock-env-vars.ts
Releasing API category
N/A
e2e and unit tests
> Release vNext of API Category

- packages/amplify-e2e-core/src/categories/api.ts
- packages/amplify-e2e-tests/src/__tests__/graphql-v2/index-with-stack-mappings.test.ts
- packages/amplify-graphql-index-transformer/src/resolvers.ts
Release support for StackMappings in Index resolvers.
N/A
e2e tests
> fix: resolvers generated from index respect StackMappings

- packages/amplify-category-api/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json
- packages/amplify-dynamodb-simulator/package.json
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-tests/package.json
- packages/amplify-graphql-auth-transformer/package.json
- packages/amplify-graphql-index-transformer/package.json
- packages/amplify-graphql-migration-tests/package.json
- packages/amplify-graphql-transformer-core/package.json
- packages/amplify-graphql-transformer-migrator/package.json
- packages/amplify-util-mock/package.json
- packages/graphql-transformer-core/package.json
- yarn.lock
> chore: bump cli versions

- packages/amplify-graphql-transformer-core/API.md
> fix circular dep - update api extract 

- scripts/verify-commit.ts
Commit verification script was failing due to a fake account number in a unit test.
Add the fake account number to the allowed patterns.
Commit verification also requested some style changes after modifying the file.
N/A
Committed this change and saw the verification pass.
> chore: fix allowed git secrets

- yarn.lock
Fixes [Dependabot Alert](https://github.com/aws-amplify/amplify-category-api/security/dependabot/37)
> chore: update json5 2.x

- packages/amplify-category-api/src/__tests__/graphql-transformer/sandbox-mode-helpers.test.ts
- packages/amplify-category-api/src/graphql-transformer/sandbox-mode-helpers.ts
- packages/amplify-graphql-transformer-core/API.md
- packages/amplify-graphql-transformer-core/src/errors/index.ts
Reverting change adding bracket detection due to customer issues reported through Github and Hosting.
https://github.com/aws-amplify/amplify-category-api/issues/1143
Unit and e2e tests pass.
> revert: remove bracket check since it's causing customer issues in hosting

- packages/amplify-category-api/src/graphql-transformer/auth-mode-compare.ts
> chore: update comment to trigger publish flow

- packages/amplify-category-api/src/graphql-transformer/transformer-factory.ts
- packages/amplify-graphql-index-transformer/src/schema.ts
- packages/amplify-graphql-model-transformer/package.json
- packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
- packages/amplify-graphql-model-transformer/src/graphql-rds-model-transformer.ts
- packages/amplify-graphql-model-transformer/src/index.ts
- packages/amplify-graphql-model-transformer/tsconfig.json
> Fixing build errors after rds package removal

- packages/amplify-e2e-core/src/init/amplifyPull.ts
- packages/amplify-e2e-core/src/utils/projectMeta.ts
- packages/amplify-migration-tests/overrides/override-api-gql.v10.ts
- packages/amplify-migration-tests/package.json
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/api-graphql-v2.migration.test.ts.snap
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/api-rest-basic.migration.test.ts.snap
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/api-rest-lambda.migration.test.ts.snap
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/api-rest-serverless.migration.test.ts.snap
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/api-graphql-v2.migration.test.ts
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/api-rest-basic.migration.test.ts
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/api-rest-lambda.migration.test.ts
- packages/amplify-migration-tests/src/__tests__/migration_tests_v10/api-rest-serverless.migration.test.ts
- packages/amplify-migration-tests/src/migration-helpers-v10/cfn-diff-exclusions.ts
- packages/amplify-migration-tests/src/migration-helpers/utils.ts
- scripts/split-e2e-test-filters.ts
This adds migration tests for the API category for v10 to Latest.
E2E in progress: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/3502/workflows/e812fdb2-e2a5-47af-97aa-a694f509075a
> chore: update e2e core & add v10 migration tests

- packages/amplify-category-api/API.md
- packages/amplify-graphql-model-transformer/API.md
- packages/graphql-transformer-common/API.md
Ran the `yarn extract-api` script to generate the updated `API.md` files.
This fixes the `verify-api-extract` CI job that's failing from [this commit](https://github.com/aws-amplify/amplify-category-api/commit/269386b8fcb3902b295ee63a078ad2e458376d63)
> chore: update API files

- packages/amplify-graphql-transformer-core/API.md
- packages/amplify-graphql-transformer-interfaces/API.md
- packages/graphql-transformer-core/API.md
Updates the changes to API files after recent merges.
> Fix api extract job on rds feature branch

- yarn.lock
https://github.com/aws-amplify/amplify-category-api/pull/1190
https://github.com/aws-amplify/amplify-category-api/pull/1196
> Fix dependent bot alert

- packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
- Batches the delete IAM role requests with batch size of 20. Tested from console that this size works.
- Adds Account ID to logs to identify exactly which account is misbehaving.
> chore: delete iam test roles in batches

- packages/amplify-graphql-model-transformer/rds-lambda/utils/rds_utils.ts
- packages/amplify-graphql-model-transformer/src/__tests__/test-utils/rds_utils.test.ts
This PR is clone of https://github.com/aws-amplify/amplify-category-api/pull/1209
> feat: add a utility to convert an input graphQL filter into an RDS query expression

- packages/graphql-relational-schema-transformer/src/RelationalDBMappingTemplate.ts
- packages/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts
- packages/graphql-relational-schema-transformer/src/__tests__/__snapshots__/RelationalDBResolverGenerator.test.ts.snap
The following changes were made to the legacy RDS transformers:
- Parameterized the SQL statements by adding a `variableMap` to the Request mapping templates all Queries and Mutations.
- Updated screenshots show the desired modifications
- Manual testing using an imported Aurora MySQL 5.6 RDS instance and importing the schema from it. 
> fix: Legacy RDS transformers to use parameterized SQL statements

- packages/amplify-graphql-index-transformer/src/resolvers/generators/rds-vtl-generator.ts
- packages/amplify-graphql-model-transformer/rds-lambda/clients/DBClient.ts
- packages/amplify-graphql-model-transformer/rds-lambda/clients/mysql/MySQLClient.ts
- packages/amplify-graphql-model-transformer/rds-lambda/interfaces/BaseRequest.ts
- packages/amplify-graphql-model-transformer/rds-lambda/interfaces/ListRequest.ts
- Fixes the RDS Index query request mapping template.
- Fixes the RDS lambda to process index query.
> fix(graphql): index rds query

- packages/amplify-e2e-core/src/categories/api.ts
- packages/amplify-e2e-core/src/utils/sdk-calls.ts
- packages/amplify-e2e-tests/schemas/simple_two_models.graphql
- packages/amplify-e2e-tests/src/__tests__/graphql-v2/lambda-conflict-handler.test.ts
- packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
- packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
- packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
- packages/amplify-schema-validator/src/__tests__/schemas/schema-with-nonnulltype.graphql
- packages/amplify-schema-validator/src/__tests__/utils/resolve-field-type-name.test.ts
- packages/amplify-schema-validator/src/__tests__/validates-schemas-with-nonnulltype.test.ts
- packages/amplify-schema-validator/src/helpers/resolve-field-type-name.ts
- packages/amplify-schema-validator/src/validators/relation-required-with-belongs-to.ts
- packages/graphql-relational-schema-transformer/src/RelationalDBMappingTemplate.ts
- packages/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts
- packages/graphql-relational-schema-transformer/src/__tests__/__snapshots__/RelationalDBResolverGenerator.test.ts.snap
- https://github.com/aws-amplify/amplify-category-api/pull/1208
- https://github.com/aws-amplify/amplify-category-api/pull/1201
- https://github.com/aws-amplify/amplify-category-api/pull/1238
Full e2e pipeline is green except couple of tests which are diagnosed to be related to the mock plugin, and are already known inconsistencies.
> Release API plugin 

- packages/graphql-relational-schema-transformer/src/RelationalDBMappingTemplate.ts
- packages/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts
- packages/graphql-relational-schema-transformer/src/__tests__/__snapshots__/RelationalDBResolverGenerator.test.ts.snap
Moving the RDS changes from this PR to be based on top off `4.1.5` instead of latest.
This is needed to get a tag release with GraphQL 14. 
> feat: tag release legacy rds fix

- .circleci/config.base.yml
- .circleci/config.yml
- client-test-apps/js/api-model-relationship-app/README.md
- client-test-apps/js/api-model-relationship-app/package.json
Modify client e2e tests package to use yarn so that 'joi' dependency is resolved as expected using `resolutions`.
> fix(test): change client e2e to use yarn

- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.ts
- packages/amplify-util-mock/package.json
- packages/amplify-util-mock/src/__tests__/utils/lambda/populate-lambda-mock-env-vars.test.ts
- packages/amplify-util-mock/src/utils/lambda/populate-lambda-mock-env-vars.ts
- yarn.lock
Remove all references to GraphQL 14.x in dependencies.
> fix(test): remove references to graphql 14 module

- .circleci/config.base.yml
- .circleci/config.yml
- package.json
Change CLI version to use the latest RC version.
> fix(test): change cli to use rc 10.8.0 b80571744

- yarn.lock
Update `yarn.lock` w/ latest changes from `package.json`.
Generated this change by running `yarn clean && yarn && yarn build && yarn test` to verify things are working w/ the update.
N/A
N/A
Builds/tests
> chore: updating yarn.lock

- .circleci/config.base.yml
- CONTRIBUTING.md
- package.json
- scripts/verify-yarn-lock.sh
- yarn.lock
Duplicate `verify-yarn-lock` CI check from CLI. This will fail the build if we are found to have an inconsistent `yarn.lock` file.
N/A
N/A
Running this CI flow!
Example failing flow: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/4658/workflows/46c12a49-93b1-4bc0-9bf7-8954e5957076/jobs/91035
Example passing flow: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/4659/workflows/3c6a0290-e60a-4d13-83e0-b348d1bfb560
> verify yarn lock

- .circleci/config.base.yml
- .circleci/config.yml
- package.json
- packages/amplify-category-api/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json
- packages/amplify-dynamodb-simulator/package.json
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-tests/package.json
- packages/amplify-e2e-tests/src/__tests__/graphql-v2/api_lambda_auth.test.ts
- packages/amplify-graphql-auth-transformer/package.json
- packages/amplify-graphql-index-transformer/package.json
- packages/amplify-graphql-migration-tests/package.json
- packages/amplify-graphql-searchable-transformer/package.json
- packages/amplify-graphql-transformer-core/package.json
- packages/amplify-graphql-transformer-migrator/package.json
- packages/amplify-migration-tests/package.json
- packages/amplify-util-mock/package.json
- packages/amplify-util-mock/src/func/index.ts
- packages/graphql-transformer-core/package.json
- packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthV2Transformer.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthV2TransformerWithFF.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2WithFF.e2e.test.ts
- yarn.lock
> chore: use latest beta (aka zzz-beta)

- packages/amplify-e2e-tests/schemas/simple_model.graphql
This change removes the changes to `simple_schema.graphql` resource in `amplify-e2e-tests` that were added in [this commit](https://github.com/aws-amplify/amplify-category-api/pull/1291).
Since this test schema is used in several places including the `amplify-migration-tests`, where we've seen [failures like this](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/4985/workflows/3d4106da-8314-420a-9ea3-9100c41e8097/jobs/99006/steps) using older CLI version without the fix in above commit. 
> chore: keep the simple model simple

- package.json
- yarn.lock
Add appropriate version resolutions and refresh the `yarn.lock` file to fix the below dependabot alerts:
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/40
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/39
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/38
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/37
- https://github.com/aws-amplify/amplify-category-api/security/dependabot/29
> chore: fix dependabot alerts

- packages/amplify-schema-validator/package.json
> chore: ensure clean target works on windows

- packages/amplify-graphql-model-transformer/rds-lambda/clients/mysql/MySQLClient.ts
- packages/amplify-graphql-model-transformer/rds-lambda/utils/rds_utils.ts
- packages/amplify-graphql-model-transformer/src/__tests__/test-utils/rds_utils.test.ts
Uses added logic for converting a filter to knex where clause, enables parameterization on the generated sql for filtering
> Feat: allow filtering on RDS list queries

- .circleci/config.base.yml
- package.json
- packages/amplify-category-api/package.json
- packages/amplify-dynamodb-simulator/package.json
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-tests/package.json
- packages/amplify-graphql-index-transformer/package.json
- packages/amplify-graphql-searchable-transformer/package.json
- packages/amplify-graphql-transformer-migrator/package.json
- packages/amplify-migration-tests/package.json
- packages/amplify-util-mock/package.json
- packages/graphql-transformer-core/package.json
- yarn.lock
Use the CLI `11.0.3` for testing our changes locally and in CI.
This avoids the problem where CLI prompts for 2 available versions of API plugin - `ownerpkfix...` tag i.e (consumed in CLI `11.0.4+`) and `5.2.0` i.e current.
Full e2e running, status is reported in the github checks.
> chore: use 11.0.3 CLI for testing

- .circleci/config.base.yml
- .circleci/config.yml
- package.json
- packages/amplify-category-api/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json
- packages/amplify-dynamodb-simulator/package.json
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-tests/package.json
- packages/amplify-graphql-auth-transformer/package.json
- packages/amplify-graphql-index-transformer/package.json
- packages/amplify-graphql-migration-tests/package.json
- packages/amplify-graphql-schema-generator/package.json
- packages/amplify-graphql-searchable-transformer/package.json
- packages/amplify-graphql-transformer-core/package.json
- packages/amplify-graphql-transformer-migrator/package.json
- packages/amplify-migration-tests/package.json
- packages/amplify-util-mock/package.json
- packages/graphql-transformer-core/package.json
- yarn.lock
Test API repo pipeline with CLI RC@12.0.0-rc.0d6bca41ff.0.
- Bump up amplify-cli-core resolution to the latest.
> chore(api): test with cli rc version

- packages/amplify-category-api/src/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-secrets/database-secrets.ts
- packages/amplify-e2e-core/src/configure/index.ts
- packages/amplify-e2e-core/src/init/deleteProject.ts
> chore(test): fix tests with cli 12.0.0 rc

- .eslintrc.js
Fix commit verify script.
When attempting to commit I would get the following error:
`Error: Error while loading rule '@typescript-eslint/no-floating-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.`
Adding the tsconfig to `parserOptions` fixes this issue.
N/A
N/A
Make a change to a TypeScript file and commit the changes.
> style: fix commit verify script

- packages/amplify-category-api/API.md
- packages/amplify-category-api/src/__tests__/index.test.ts
- packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cfn-api-artifact-handler.test.ts
- packages/amplify-category-api/src/commands/api/add.ts
- packages/amplify-category-api/src/commands/api/override.ts
- packages/amplify-category-api/src/graphql-transformer/api-utils.ts
- packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
- packages/amplify-category-api/src/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/apigw-input-state.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/convert-deprecated-apigw-paths.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/legacy-add-resource.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthrough-types/apigw-types.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/containers-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/amplify-meta-utils.ts
- packages/amplify-e2e-tests/src/import-helpers/types.ts
- packages/amplify-e2e-tests/src/import-helpers/utilities.ts
- packages/amplify-graphql-transformer-interfaces/API.md
- packages/amplify-graphql-transformer-interfaces/src/index.ts
- packages/amplify-graphql-transformer-interfaces/src/types.ts
- packages/amplify-graphql-transformer-migrator/src/utils.ts
- packages/amplify-util-mock/src/utils/lambda/load-lambda-config.ts
replace `TSObject` with `Record<string, any>`
N/A
N/A
Unit tests
> refactor: replace $TSObject with Record<string, any>

- packages/amplify-category-api/src/commands/api/gql-compile.ts
- packages/amplify-category-api/src/force-updates/api-resource-paths.ts
- packages/amplify-category-api/src/force-updates/auth-notifications.ts
- packages/amplify-category-api/src/force-updates/force-refresh-schema.ts
Adding support for the `--force` parameter to `gql-compile` which will ensure that the `schema.graphql` file has whitespace appended, updating the hash, and forcing a rebuild/push to backend. This is useful for adopting changes in generated resolvers/schema from the library, without requiring any codechange on the customer end.
N/A
N/A - internal ticket
Manually tested using `amplify-dev api gql-compile --force && amplify push`, and also validated that if make a destructive change (e.g. remove a model) it still blocks the push.
```
➜  testUpdate amplify-dev api gql-compile --force && amplify push
✅ GraphQL schema compiled successfully.
Edit your schema at /Users/alharris/apps/testUpdate/amplify/backend/api/testupdate/schema.graphql or place .graphql files in a directory at …
```
> feat: add force-api-refresh option to the api push command in order to support refreshing an API (for example, on resolver code changes)

- CONTRIBUTING.md
Updates to `CONTRIBUTING.md` to improve docs on iterative builds while developing.
N/A
N/A
N/A
> chore: improve docs on iterative builds while developing

- .github/CODEOWNERS
> Update CODEOWNERS to require admin approval on api surface area change

- packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/import-rds-utils/globalAmplifyInputs.test.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/import-appsync-api-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/graphql-schema-utils.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-input-utils.ts
- packages/amplify-graphql-transformer-core/API.md
- packages/amplify-graphql-transformer-core/src/index.ts
- packages/amplify-graphql-transformer-core/src/transformation/transform.ts
- packages/amplify-graphql-transformer-core/src/utils/index.ts
Final cleanup for cli core refactor
* move rds input utils to amplify-category-api
N/A
* Unit tests
* e2e tests
> amplify-cli-core refactor cleanup

- packages/amplify-category-api/amplify-plugin.json
- packages/amplify-category-api/src/commands/api.ts
- packages/amplify-category-api/src/commands/api/generate-schema.ts
- packages/amplify-category-api/src/commands/api/import.ts
- packages/amplify-category-api/src/commands/api/update-secrets.ts
Treat RDS commands as any normal unsupported command.
After this change it'll show as:
> chore: remove rds related commands

- codebuild_specs/e2e_workflow.yml
- package.json
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-core/src/utils/index.ts
- packages/amplify-e2e-core/src/utils/refresh-credentials.ts
- packages/amplify-e2e-tests/refresh-credentials.sh
- packages/amplify-e2e-tests/src/__tests__/graphql-v2/searchable-datastore.test.ts
- packages/amplify-e2e-tests/src/__tests__/schema-searchable.test.ts
- packages/amplify-e2e-tests/src/__tests__/transformer-migrations/searchable-migration.test.ts
- scripts/split-e2e-tests-codebuild.ts
- shared-scripts.sh
- yarn.lock
- Add refresh credentials for some Searchable tests that could take more than an hour to run. This eliminates the token expiry due to role chaining.
- Use `amplify-integ-test-user` profile to collect flaky test metrics. This step used to fail if job runs for more than an hour.
- Updates to codebuild split-e2e script to use parent account for searchable tests.
Verified that `searchable-migration` test runs beyond an hour and passes.
> Add credential refresh logic for long running tests

- packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2Transformer.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/RelationalTransformers.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/SearchableWithAuthV2.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/SearchableWithAuthV2WithFF.e2e.test.ts
- scripts/split-e2e-tests.ts
The modified tests were failing on `main` because of the wrong FF configs for these tests post refactor.
It might be easier to verify with the pre-FF refactor state of these tests that can be found in [this other PR diff](https://github.com/aws-amplify/amplify-category-api/commit/c20c06d797c02f7ea2c9c9861461a091506863a7#diff-2411f52ac4b54229ddf4684d8bff963628a7ffa3adf3ce121303ab9b2bcc3ed3).
> Fix the failing e2e tests due to Feature Flag misconfigurations

- packages/amplify-graphql-api-construct/package.json
- packages/amplify-graphql-api-construct/tsconfig.json
Use PeerDeps for CDK and Constructs lib.
N/A
N/A
Validating in npm deploy lib/sample app.
> chore: use peer deps for proposed cdk construct

- packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/database-url.test.ts
- packages/amplify-category-api/src/commands/api/update-secrets.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/import-appsync-api-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/database-url.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/graphql-schema-utils.ts
- packages/amplify-e2e-core/src/categories/api.ts
- packages/amplify-e2e-tests/src/__tests__/rds-import-vpc.test.ts
- packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
- packages/amplify-graphql-model-transformer/publish-notification-lambda/tsconfig.json
- packages/amplify-graphql-model-transformer/rds-patching-lambda/tsconfig.json
- packages/amplify-graphql-model-transformer/src/resolvers/rds/mutation.ts
- packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
- packages/amplify-graphql-model-transformer/src/resources/rds-model-resource-generator.ts
- Adds support for database url in import api cli workflow.
- Adds support for condition argument in update and delete mutation.
- Modifies resources to use prod account.
- Address some of the minor review comments from prior PRs.
NA
NA
- Manual test
- E2E test
> fix(api): improve cli workflow to support database url

- codebuild_specs/mock_e2e_tests.yml
- codebuild_specs/release_workflow.yml
- codebuild_specs/test.yml
The memory of the currently used `MEDIUM` sized container for the release workflow is 3GB and I've seen few runs of `test` and `mock-e2e-test` jobs failing due to breaching this limit. This bumps it to next available size.
Add artifacts to test jobs which is required by CB.
Successfully able to trigger and publish a tag release. Refer [this release commit created from beta account]([chore(release): Publish tagged release $NPM_TAG [ci skip]](https://github.com/aws-amplify/amplify-category-api/commit/da8e22a26d3f5db3d4944094b82e473a786bec81)).
> fix: increase container size for release workflow

- package.json
- yarn.lock
Bump `fast-xml-parser` to `^4.2.4`
https://github.com/aws-amplify/amplify-category-api/security/dependabot/60
https://github.com/aws-amplify/amplify-category-api/security/dependabot/59
> fix: dependent alert for fast-xml-parser

- packages/amplify-category-api/src/commands/api/add-graphql-datasource.ts
- packages/amplify-category-api/src/commands/api/override.ts
- packages/amplify-category-api/src/force-updates/force-refresh-schema.ts
- packages/amplify-category-api/src/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/apigw-input-state.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
- packages/amplify-graphql-model-transformer/rds-lambda/clients/mysql/MySQLPasswordClient.ts
- packages/amplify-util-mock/src/api/api.ts
- packages/amplify-util-mock/src/api/index.ts
- packages/amplify-util-mock/src/commands/mock/mock.ts
- packages/amplify-util-mock/src/storage/index.ts
- packages/amplify-util-mock/src/utils/dynamo-db/helpers.ts
- packages/graphql-transformers-e2e-tests/src/CloudFormationClient.ts
hanlding of all floating promises
N/A
N/A
> fix: handling of all floating promises

- .circleci/config.base.yml
- packages/amplify-e2e-core/src/init/cdkDestroy.ts
- packages/amplify-e2e-core/src/init/index.ts
- packages/amplify-e2e-core/src/init/initProjectHelper.ts
- packages/amplify-e2e-tests/src/__tests__/cdk/__snapshots__/base-cdk.test.ts.snap
- packages/amplify-e2e-tests/src/__tests__/cdk/backends/base-cdk/app.ts
- packages/amplify-e2e-tests/src/__tests__/cdk/backends/base-cdk/stacks/backend-stack.ts
- packages/amplify-e2e-tests/src/__tests__/cdk/base-cdk.test.ts
Add e2e test for construct.
Add E2D tests for constructs
N/A
N/A
Run the tests: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/7585/workflows/07a86d30-6a86-406d-b35b-40e270e90658
> test: add e2e test for construct

- packages/amplify-graphql-api-construct/API.md
- packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
- packages/amplify-graphql-api-construct/src/index.ts
- packages/amplify-graphql-api-construct/src/internal/default-parameters.ts
- packages/amplify-graphql-api-construct/src/types.ts
rename graphql behavior prop
N/A
N/A
Unit tests
> chore: rename graphql behavior prop

- codebuild_specs/scripts/publish.sh
This PR updates the branch naming convention to publish a tagged release so as to not interfere with the CircleCI setup we have now.
These changes will be reverted post the codebuild DX bake time.
> chore: separate invocation of cb tag release

- .github/CODEOWNERS
- package.json
- scripts/view-test-artifacts.sh
- Script to support viewing the e2e test artifacts locally. Check the detailed instructions to use it [here](https://quip-amazon.com/OfHHAKwHaeZW/Amplify-API-Category-operations-Runbook-Codebuild#temp:C:MLR83105d95f7644a8b9941a255f).
- Update the code owners file to require admin approval for modifying the ci/cd related files as per AppSec requirement to enable web-hooks.
Successfully able to download and play an e2e test artifact from beta account.
> feat: add command to locally play e2e artifacts

- packages/amplify-e2e-tests/src/__tests__/cdk/base-cdk.test.ts
> fix: fixing bad quotes in e2e te st

- packages/amplify-graphql-maps-to-transformer/package.json
- packages/amplify-graphql-maps-to-transformer/src/__tests__/graphql-maps-to-transformer.test.ts
Adding unit tests
N/A
N/A
Unit tests
> chore: increase unit test coverage on mapsToTransformer

- packages/amplify-graphql-default-value-transformer/package.json
- packages/amplify-graphql-default-value-transformer/src/__tests__/validators.test.ts
- packages/amplify-graphql-default-value-transformer/src/validators.ts
Adding unit tests
N/A
N/A
Unit tests
> chore: add unit tests, fix bug for date marshalling

- packages/amplify-graphql-searchable-transformer/package.json
- packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/generate-resolver-vtl.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/definitions.test.ts
- packages/amplify-graphql-searchable-transformer/src/__tests__/generate-resolver-vtl.test.ts
Adding unit tests.
N/A
N/A
Unit tests
> chore: add unit tests for searchable transformer

- packages/amplify-graphql-transformer-core/src/cdk-compat/template-asset.ts
- packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
Address straightforward lint issues, and apply some ignores for the ones that'll likely be addressed by a downstream refactor.
* Fix repeated typo in `substitue` to `substitute`.
* Add ignores for max classes and no-this-reference since those are pretty core in the class today, larger refactor may address them.
* Add return types, etc.
* Ignore no-consistent returns for some of the find* methods.
* semicolons, whitespace, parens around anonymous functions.
N/A
N/A
Unit tests + e2e tests will verify behavior.
> chore: get lint rules all passing on resolvers.ts

- .circleci/config.base.yml
- .eslintrc.js
- codebuild_specs/cleanup_workflow.yml
- package.json
- packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
- packages/amplify-graphql-api-construct/package.json
- packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
- packages/amplify-graphql-default-value-transformer/package.json
- packages/amplify-graphql-default-value-transformer/src/__tests__/validators.test.ts
- packages/amplify-graphql-default-value-transformer/src/validators.ts
- packages/amplify-graphql-maps-to-transformer/package.json
- packages/amplify-graphql-maps-to-transformer/src/__tests__/graphql-maps-to-transformer.test.ts
- packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
- packages/amplify-graphql-searchable-transformer/package.json
- packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/generate-resolver-vtl.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/definitions.test.ts
- packages/amplify-graphql-searchable-transformer/src/__tests__/generate-resolver-vtl.test.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnOutput.ts
- packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
- packages/amplify-graphql-transformer-core/src/__tests__/transformation/transform.test.ts
- packages/amplify-graphql-transformer-core/src/__tests__/transformation/utils.test.ts
- packages/amplify-graphql-transformer-core/src/cdk-compat/template-asset.ts
- packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
- packages/amplify-graphql-transformer-core/src/transformation/transform.ts
- packages/amplify-graphql-transformer-core/src/transformation/utils.ts
- packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
- scripts/cloud-utils.sh
> Release API Category Packages

- .circleci/config.base.yml
- .circleci/config.yml
- package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json
- packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json
- packages/amplify-category-api/src/__tests__/category-utils/show-auth-acm.test.ts
- packages/amplify-e2e-core/src/categories/lambda-function.ts
- packages/amplify-graphql-api-construct/package.json
- packages/amplify-graphql-auth-transformer/package.json
- packages/amplify-graphql-function-transformer/package.json
- packages/amplify-graphql-http-transformer/package.json
- packages/amplify-graphql-index-transformer/package.json
- packages/amplify-graphql-maps-to-transformer/package.json
- packages/amplify-graphql-model-transformer/package.json
- packages/amplify-graphql-predictions-transformer/package.json
- packages/amplify-graphql-relational-transformer/package.json
- packages/amplify-graphql-searchable-transformer/package.json
- packages/amplify-graphql-transformer-core/package.json
- packages/amplify-graphql-transformer-interfaces/package.json
- packages/amplify-migration-tests/package.json
- packages/amplify-util-mock/package.json
- packages/graphql-transformer-core/package.json
- yarn.lock
> chore(api): upgrade cdk version to 2.80

- package.json
- packages/amplify-e2e-core/package.json
- packages/amplify-migration-tests/package.json
- packages/amplify-util-mock/package.json
- yarn.lock
Update semver deps, and set resolutions.
N/A
N/A
Unit Tests
> chore: update semver deps for dependabot

- packages/graphql-transformers-e2e-tests/resources/jsonServer/yarn.lock
Refresh yarn.lock file for transformer tests package jsonServer in order to mitigate dependabot issues w/ semver.
N/A
N/A
Tests
> chore: refresh test package lockfile to mitigate dependabot

- codebuild_specs/lint.yml
- package.json
use prettier and depcheck in CB lint step
N/A
N/A
Run CB
> ci: use prettier and depcheck in CB lint step

- codebuild_specs/scripts/lint_pr.sh
- codebuild_specs/scripts/publish.sh
Correctly resolve the branch name in case of a webhook trigger event
Will be tested in next merge to release branch.
> chore: fix branch name resolution for release via webhook

- shared-scripts.sh
Extended the timeout for NPM fetch to avoid the following error observed in code build installing CLI from local registry job
```
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```
Refer https://stackoverflow.com/questions/67657599/npm-err-code-err-socket-timeout-on-creating-new-project-using-ng-new-appname
> fix: longer timeout for npm fetch

- codebuild_specs/e2e_workflow.yml
- packages/amplify-category-api/package.json
- packages/amplify-category-api/src/graphql-transformer/override.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
- packages/amplify-e2e-tests/src/__tests__/api_7.test.ts
- yarn.lock
Removes the `vm2` dependency from the plugin.
The CLI core and cloudformation provider deps from CLI still fetch it, so not fully removed from `yarn.lock` yet.
The following E2E tests cover positive and negative tests for applying overrides:
- GraphQL API -> https://github.com/aws-amplify/amplify-category-api/blob/main/packages/amplify-e2e-tests/src/__tests__/api_7.test.ts
- Rest API -> https://github.com/aws-amplify/amplify-category-api/blob/main/packages/amplify-e2e-tests/src/__tests__/apigw.test.ts 
> Remove vm2 for Plugin on main

- codebuild_specs/scripts/publish.sh
- shared-scripts.sh
Encountering error below in deploy job
```
lerna ERR! Error: Command failed with exit code 128: git diff --name-only  -- packages/amplify-category-api
lerna ERR! fatal: bad revision 'undefined
```
Trying to fetch all tags in this PR.
Was able to successfully publish a tag release with the changes. The red check on release flow is due to the `lint` job failing.
> fix: fetch all tags in release workflow

- codebuild_specs/scripts/publish.sh
- packages/amplify-category-api/package.json
- shared-scripts.sh
Fixes the issue with latest release of API plugin that's missing the `index.js` file on NPM.
> fix: add build packages before release

- packages/amplify-e2e-tests/src/__tests__/rds-v2.test.ts
- packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
Update the RDS layer version to the latest.
> chore(api): update rds layer to version 8

- codebuild_specs/scripts/publish.sh
- packages/amplify-category-api/CHANGELOG.md
- packages/amplify-category-api/package.json
- packages/amplify-category-api/src/provider-utils/supported-datasources.ts
- shared-scripts.sh
Merge main into feature branch to unblock e2e's and local verdaccio publish.
> merge main into no synth aug 1

- packages/amplify-graphql-api-construct/src/__tests__/__functional__/resources.test.ts
- packages/amplify-graphql-transformer-core/src/appsync-function.ts
- packages/amplify-graphql-transformer-core/src/transform-host.ts
Decorate and add unit tests for appsync indexed resources.
N/A - metadata updates for resource returns.
N/A
Unit tests
> resources returned in construct

- packages/amplify-graphql-api-construct/API.md
- packages/amplify-graphql-api-construct/src/__tests__/__functional__/resources.test.ts
- packages/amplify-graphql-api-construct/src/index.ts
- packages/amplify-graphql-api-construct/src/internal/construct-exports.ts
- packages/amplify-graphql-api-construct/src/types.ts
- packages/amplify-graphql-maps-to-transformer/src/field-mapping-lambda.ts
- packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
- packages/amplify-graphql-model-transformer/src/resources/dynamo-model-resource-generator.ts
- packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
- packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
- packages/amplify-graphql-transformer-core/src/graphql-api.ts
- packages/amplify-graphql-transformer-core/src/transform-host.ts
- packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
Return L1 and L2 CFN Resources, tweaking shape slightly, and adding L2 GraphqlApi, Tables, Roles, and Functions.
N/A
N/A
Unit Tests
> Add remaining L1 resources, as well as limited L2 resources.

- packages/amplify-graphql-model-transformer/rds-lambda/handler.ts
Add `DEBUG_MODE` boolean as an optional environment variable that decides the verbosity of SQL errors if any.
> Add optional debug mode

- packages/amplify-graphql-api-construct/API.md
- packages/amplify-graphql-api-construct/src/__tests__/internal/user-defined-slots.test.ts
- packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
- packages/amplify-graphql-api-construct/src/internal/user-defined-slots.ts
- packages/amplify-graphql-api-construct/src/types.ts
Removing unsupported function slot params, and validation around them (to clean up the interface a bit).
N/A
N/A
Unit tests pass.
> chore: remove unsupported function slot params

- packages/amplify-category-api/CHANGELOG.md
- packages/amplify-category-api/package.json
- packages/amplify-e2e-core/CHANGELOG.md
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-tests/CHANGELOG.md
- packages/amplify-e2e-tests/package.json
- packages/amplify-migration-tests/CHANGELOG.md
- packages/amplify-migration-tests/package.json
Merge main into feature branch
> Merge main into feature branch

- packages/amplify-e2e-core/src/index.ts
- packages/graphql-transformer-core/src/index.ts
fix eslint rule import/export
N/A
N/A
Unit tests
> style: fix eslint rule import/export

- client-test-apps/js/api-model-relationship-app/src/components/AuthModePicker.tsx
Fixed the compile error in canary app. 
Error seen in the CodeBuild
Run the canary test locally and succeed
> fix: compile error in canary

- packages/amplify-e2e-core/src/utils/nexpect.ts
- packages/amplify-e2e-tests/src/init-special-cases/index.ts
- packages/amplify-e2e-tests/src/schema-api-directives/tests/function-differentRegion.ts
- packages/amplify-graphql-transformer-core/src/transformer-context/model-field-map.ts
- packages/graphql-auth-transformer/src/__tests__/PerFieldAuthArgument.test.ts
* [fix eslint rule no-lonely-if](https://github.com/aws-amplify/amplify-category-api/commit/97f802478b11cf2fa8471e4a06142d4dffef6323)
* [fix eslint rule no-useless-catch](https://github.com/aws-amplify/amplify-category-api/commit/12e8fb2252794d8df987ef4527a5cfbfbc9b91a4)
N/A
N/a
Unit test
> Fix several eslint rules

- packages/amplify-category-api/src/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/ecs-apigw-stack.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/index.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/containers-artifacts.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/resolver-config-to-conflict-resolution-bi-di-mapper.ts
- packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
- packages/amplify-graphql-transformer-core/src/transformer-context/output.ts
- packages/amplify-graphql-transformer-core/src/utils/authType.ts
- packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts
- packages/graphql-http-transformer/src/HttpTransformer.ts
- packages/graphql-transformer-core/src/TransformerContext.ts
- packages/graphql-transformer-core/src/util/amplifyUtils.ts
fix eslint rule no-case-declarations
N/A
N/A
Unit tests
> style: fix eslint rule no-case-declarations

- packages/amplify-category-api/src/provider-utils/awscloudformation/docker-compose/converter.ts
- packages/amplify-e2e-core/src/utils/nexpect.ts
- packages/amplify-e2e-core/src/utils/sdk-calls.ts
- packages/amplify-e2e-tests/src/__tests__/custom_policies_container.test.ts
- packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
- packages/amplify-util-mock/src/CFNParser/stack/index.ts
- packages/graphql-mapping-template/src/print.ts
- packages/graphql-transformer-core/src/polyfills/Object.assign.ts
- packages/graphql-transformer-core/src/util/amplifyUtils.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/CustomRoots.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/NestedStacksTest.e2e.test.ts
> style: fix no-var eslint rule

- packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
- packages/amplify-graphql-api-construct/src/internal/codegen-assets.ts
- packages/amplify-graphql-default-value-transformer/.npmignore
- packages/amplify-graphql-model-transformer/.npmignore
- packages/amplify-graphql-searchable-transformer/.npmignore
> Release API Category and CDK Construct

- codebuild_specs/e2e_workflow.yml
- packages/amplify-e2e-tests/src/__tests__/cdk/add-resources.test.ts
- packages/amplify-e2e-tests/src/__tests__/cdk/backends/add-resources/app.ts
Add an e2e test for the basic add*DataSource, addResolver, and addFunction methods in the CDK construct.
N/A - only test updates.
N/A
E2E Tests
> chore: add e2e test for add utilities in cdk

- codebuild_specs/e2e_workflow.yml
- packages/amplify-e2e-tests/src/__tests__/rds-model-v2.test.ts
- packages/amplify-e2e-tests/src/__tests__/rds-v2-generate-schema.test.ts
- packages/amplify-e2e-tests/src/__tests__/rds-v2.test.ts
- packages/amplify-graphql-name-mapping-transformer/src/__tests__/__integ__/common.ts
- packages/amplify-graphql-name-mapping-transformer/src/__tests__/field-mapping-resolvers.test.ts
- packages/amplify-graphql-name-mapping-transformer/src/__tests__/graphql-refers-to-transformer.test.ts
- packages/amplify-graphql-name-mapping-transformer/src/field-mapping-resolvers.ts
- packages/amplify-graphql-relational-transformer/src/__tests__/relational-auth.test.ts
- packages/amplify-graphql-relational-transformer/src/graphql-belongs-to-transformer.ts
- packages/amplify-graphql-schema-generator/API.md
- packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate-schema.test.ts.snap
- packages/amplify-graphql-schema-generator/src/__tests__/generate-schema.test.ts
- packages/amplify-graphql-schema-generator/src/__tests__/schema-overrides.test.ts
- packages/amplify-graphql-schema-generator/src/schema-generator/generate-schema.ts
- packages/amplify-graphql-schema-generator/src/schema-generator/schema-overrides.ts
- packages/amplify-graphql-transformer/src/graphql-transformer.ts
- packages/graphql-transformer-common/API.md
- packages/graphql-transformer-common/package.json
- packages/graphql-transformer-common/src/__tests__/defnition.test.ts
- packages/graphql-transformer-common/src/__tests__/util.test.ts
- packages/graphql-transformer-common/src/definition.ts
- packages/graphql-transformer-common/src/util.ts
- Infer and add field name mappings based on the column names of a table in MySQL. This happens when customers import RDS schema.
- Retain any edits to the schema with respect to field name mappings when customers re-generate their RDS schema.
- Throw error during re-generation when multiple models map to same tableName in the edited schema.
Added unit and E2E tests. [E2E link](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow%3Ac44d815c-2032-40c7-85ca-770a82520698?region=us-east-1)
> Field mapping schema edits

- packages/amplify-graphql-api-construct/.jsii
- packages/amplify-graphql-api-construct/API.md
- packages/amplify-graphql-api-construct/src/types.ts
- packages/amplify-graphql-index-transformer/src/resolvers/resolvers.ts
- packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/amplify-table-manager-lambda.test.ts.snap
- packages/amplify-graphql-model-transformer/src/__tests__/amplify-dynamodb-table-construct.test.ts
- packages/amplify-graphql-model-transformer/src/__tests__/amplify-dynamodb-table-generator.test.ts
- packages/amplify-graphql-model-transformer/src/__tests__/amplify-table-manager-lambda.test.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamo-model-resource-generator.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamodb-table-construct/index.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-managed-table/index.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda-types.d.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-types.d.ts
- packages/amplify-graphql-relational-transformer/src/resolvers.ts
- Added internal construct `AmplifyDynamoDBTable`
- Added type definition for `CustomDDB.Input`, which now refers to the partially forked version of `CfnTableProps`
- Unit tests (new construct base usage and add GSIs)
- Changes for `@primaryKey`, `@index` & `@hasMany` so that the key schema/GSI changes are respected
- Util functions in amplify table lambda to convert input to PascalCase
Changes not included in the PR
- Replace feature flag with top level property `tableManagementStrategy`
- Use API root stack for custom resource provider related resources
- Unit tests
- Local CDK app to provision tables using `AmplifyGraphqlApi` construct
> feat: amplify table construct & key schema related transformer changes

- packages/amplify-graphql-api-construct/src/internal/codegen-assets.ts
From profiling of S3 bucket upload it turns out that default 128MB limit is not enough.
This speeds up codegen upload from 30+ seconds to <10s.
From isolated repro:
From lambda logs after change:
```
REPORT RequestId: 24aad2f5-61b2-407b-9f7e-fb1302b29f85 Duration: 8998.55 ms Billed Duration: 8999 ms Memory Size: 512 MB Max Memory Used: 136 MB
```
Before:
After:
> fix: speed up codegen asset deployment

- packages/amplify-category-api/src/commands/api/generate-schema.ts
- packages/amplify-category-api/src/commands/api/update-secrets.ts
- packages/amplify-category-api/src/graphql-transformer/transform-graphql-schema-v2.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-db-config.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/import-appsync-api-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rds-resources/database-resources.ts
- packages/amplify-graphql-schema-generator/src/utils/__tests__/vpc-helper.test.ts
- packages/amplify-graphql-schema-generator/src/utils/vpc-helper.ts
- Added RDS Proxy to list of supported sources for schema imports
- Added test to confirm order of inspection is:
1. Proxy
2. Cluster
3. Instance
- Added warning if provided hostname is a) an RDS database; and b) not a proxy
- Refactored walkthrough & database utilities to eliminate a dependency cycle
- Multiple linting fixes
- Unit tests to validate order of operations
> feat: Support RDS Proxy schema imports

- packages/amplify-category-api/src/commands/api/generate-schema.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-db-config.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/import-appsync-api-walkthrough.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/graphql-schema-utils.ts
- packages/amplify-e2e-core/package.json
- packages/amplify-e2e-core/src/categories/api.ts
- packages/amplify-e2e-core/src/utils/rds.ts
- packages/amplify-e2e-tests/src/__tests__/rds-postgres-import.test.ts
- packages/amplify-graphql-schema-generator/API.md
- packages/amplify-graphql-schema-generator/package.json
- packages/amplify-graphql-schema-generator/src/__tests__/pg-datasource-adapter.test.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/index.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/pg-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/schema-representation/engine.ts
- packages/amplify-graphql-schema-generator/src/utils/vpc-helper.ts
- packages/amplify-graphql-schema-generator/vpc-db-lambda/package.json
- packages/amplify-graphql-schema-generator/vpc-db-lambda/src/connection.ts
- packages/amplify-graphql-schema-generator/vpc-db-lambda/src/index.ts
- packages/amplify-graphql-transformer-core/API.md
- packages/amplify-graphql-transformer-core/src/types/import-appsync-api-types.ts
- yarn.lock
- Modify `amplify import api` flow to prompt for the database engine type.
- Modify E2E tests to setup postgres databases.
- Add unit tests for Postgres import adapter layer.
- Grant logs access to schema inspector lambda.
NA
NA
- New E2E tests added
> feat(api): cli prompt changes to support postgres import

- codebuild_specs/e2e_workflow.yml
- packages/amplify-e2e-tests/src/__tests__/auth-test-schemas/userpool-apikey.ts
- packages/amplify-e2e-tests/src/__tests__/rds-mysql-multi-auth-1.test.ts
- packages/amplify-e2e-tests/src/rds-v2-test-utils/index.ts
- packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
- packages/amplify-graphql-schema-generator/API.md
- packages/amplify-graphql-schema-generator/src/__tests__/schema-overrides.test.ts
- packages/amplify-graphql-schema-generator/src/schema-generator/schema-overrides.ts
- Add feature to preserve Auth rule edits on a model during schema re-generation.
- Fix issue with `delete` mutation not setting the `allowedFields` correctly.
- Fix issue with `create/update` mutations including non-existent auto-generator foreign key field in `allowedFields`.
- Add E2E tests for relational auth with multiple auth providers i.e userpool and apiKey.
Added E2E and unit tests.
> fix: relational auth cases; preserve auth rule schema edits, added multi-auth e2e tests

- packages/amplify-graphql-model-transformer/package.json
- packages/amplify-graphql-model-transformer/src/__tests__/amplify-table-manager-lambda.test.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-dynamo-model-resource-generator.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.ts
- yarn.lock
Update custom resource code to use aws sdk v3, and update lambda definitions to use NODEJS_18.
Yes, generated lambda has been changed.
N/A
Unit tests + manual verification.
> chore: bump custom resource to sdk v3

- packages/amplify-e2e-tests/src/__tests__/transformer-migrations/predictions-migration.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerTests.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerV2Tests.e2e.test.ts
Update predictions E2E test inline regex strings, which extends https://github.com/aws-amplify/amplify-category-api/pull/1985
> test: fix prediction e2e test

- packages/amplify-e2e-tests/src/__tests__/rds-pg-array-objects.test.ts
- packages/amplify-e2e-tests/src/__tests__/rds-pg-relational-directives.test.ts
Add E2E tests for the below cases.
- Support for array and object types.
- Relational directives - hasOne, hasMany and belongsTo.
- Support for SQL directive - statement and reference options.
> test(api): postgres relational, sql and complex types

- packages/amplify-graphql-api-construct-tests/package.json
- packages/amplify-graphql-api-construct/.jsii
- yarn.lock
> chore: Sync main managed table

- codebuild_specs/e2e_workflow.yml
- packages/amplify-graphql-api-construct/.jsii
- packages/amplify-graphql-api-construct/src/amplify-graphql-definition.ts
- Updated the code build spec to include new test suites
- Added `@experimental` in the `AmplifyGraphqlDefinition` methods
> chore: update spec & add experimental tag

- packages/amplify-category-api/src/commands/api/import.ts
- packages/amplify-category-api/src/provider-utils/awscloudformation/utils/graphql-schema-utils.ts
- packages/amplify-graphql-schema-generator/API.md
- packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate.test.ts.snap
- packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/pg-datasource-adapter.test.ts.snap
- packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/pg-string-datasource-adapter.test.ts.snap
- packages/amplify-graphql-schema-generator/src/__tests__/__utils__/schemas.ts
- packages/amplify-graphql-schema-generator/src/__tests__/mysql-datasource-adapter.test.ts
- packages/amplify-graphql-schema-generator/src/__tests__/pg-datasource-adapter.test.ts
- packages/amplify-graphql-schema-generator/src/__tests__/pg-string-datasource-adapter.test.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/index.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/mysql-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/pg-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/pg-string-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/string-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/generate.ts
add postgres support to graphqlSchemaFromRDSSchema
N/A
N/A
* Unit tests
* Manual testing
* E2E test will be added in followup pr.
> feat: add postgres support to graphqlSchemaFromRDSSchema

- packages/amplify-graphql-schema-generator/API.md
- packages/amplify-graphql-schema-generator/src/__tests__/mysql-string-datasource-adapter.test.ts
- packages/amplify-graphql-schema-generator/src/__tests__/pg-string-datasource-adapter.test.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/mysql-string-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/pg-string-datasource-adapter.ts
- packages/amplify-graphql-schema-generator/src/datasource-adapter/string-datasource-adapter.ts
Validate imported schema by checking for all expected columns to be present.
N/A
N/A
* Unit testing
* Manual testing
> feat: validate imported schema

- packages/amplify-e2e-tests/src/__tests__/rds-v2.test.ts
- packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
- update the SQL layer versions post re-naming
E2E to be run on `main`.
> chore: update sql layer versions

- packages/amplify-data-construct/.jsii
- packages/amplify-data-construct/package.json
- packages/amplify-graphql-api-construct/.jsii
- packages/amplify-graphql-api-construct/package.json
- packages/amplify-graphql-api-construct/src/__tests__/__functional__/outputs.test.ts
- yarn.lock
Update versions for `backend-output-storage`, `backend-output-schemas`, `platform-core` and `plugin-types`.
Also added a test around the behavior of the updated package.
> fix: update backend-output-storage dependencies

- packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/pg-datasource-adapter.test.ts.snap
- packages/amplify-graphql-schema-generator/src/datasource-adapter/pg-datasource-adapter.ts
Fix typo in PG schema query.
N/A
N/A
E2E tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:f41dfe05-0d69-4a36-80cf-f3ffaa486c0d?region=us-east-1
> fix: typo in PG schema query

- packages/amplify-graphql-api-construct/.jsii
- packages/amplify-graphql-api-construct/src/__tests__/__functional__/outputs.test.ts
- packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
- packages/amplify-graphql-api-construct/src/amplify-graphql-definition.ts
Adds `dataSources` metadata to CDK stack BI.
**Note** This can't be merged to `main` until #2115 is merged. Leaving it as Draft until then.
- Unit tests
> chore: Update metadata with data sources

- Readme.md
Update min node version to align with CLI docs
---
> docs: update min node version to align with CLI docs

- packages/amplify-graphql-transformer-core/FixJestEnvironment.js
- packages/amplify-graphql-transformer-core/package.json
This change to unblock an external contribution: https://github.com/aws-amplify/amplify-category-api/pull/2158
`sturcturedClone` is missing in the jest node environment. https://github.com/jestjs/jest/issues/12628 Newer versions of jest have fixed this, but it is not possible to upgrade at this time. Newer versions of jest have a performance issue when not used with Node ^20.11.0. https://github.com/jestjs/jest/issues/11956 Our minimum supported version is Node 18.
I tried upgrading here: https://github.com/aws-amplify/amplify-category-api/pull/2183
N/A
N/A
Run unit tests on https://github.com/aws-amplify/amplify-category-api/pull/2158
> test: fix jest environment missing structuredClone

- packages/amplify-data-construct/.jsii
- packages/amplify-graphql-api-construct/.jsii
- packages/amplify-graphql-api-construct/src/internal/codegen-assets.ts
- packages/amplify-graphql-transformer-core/src/__tests__/utils/directive-wrapper-test.ts
- packages/amplify-graphql-transformer-core/src/utils/directive-wrapper.ts
- [fix: Use deployment rather than bucket for model schema URI](https://github.com/aws-amplify/amplify-category-api/pull/2202)
- [fix: deep merge default behavior](https://github.com/aws-amplify/amplify-category-api/pull/2212)
Running full E2E suite.
> Release API Plugin

- dependency_licenses.txt
- package.json
- packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/package.json
- scripts/package.json
- yarn.lock
> chore(api): upgrade axios to ^1.6.0

- client-test-apps/js/api-model-relationship-app/cypress.config.ts
Set cypress response timeout to 3 minutes.
> chore(api): increase cypress response timeout to 3 min

- packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
Add cdk amplify table roles to clean up script.
> fix(api): clean stale cdk amplify table roles

- packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2TransformerWithFF.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/FunctionTransformerTestsV2.e2e.test.ts
- packages/graphql-transformers-e2e-tests/src/__tests__/HttpTransformerV2.e2e.test.ts
Adds missing non-model E2E tests for selective directives that are supported as per this [document](https://quip-amazon.com/nnY9AnrywzTV/Non-model-types-support).
Test suites that are added/updated run successfully in CI.
> test: add non model e2e for supported cases

- packages/amplify-e2e-core/src/utils/rds.ts
- packages/amplify-graphql-api-construct-tests/src/__tests__/backends/sql-models/app.ts
- packages/amplify-graphql-api-construct-tests/src/__tests__/sql-models.test.ts
* fix issue with exist sql model e2e tests
* Add a E2E to test using an RDS managed master user password.
N/A
N/A
* E2E tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:28513a38-a284-4833-b68f-31db28fae744?region=us-east-1
> test: add e2e for RDS managed secret

- packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-references-transformer.test.ts
- packages/amplify-graphql-relational-transformer/src/belongs-to/belongs-to-directive-transformer-factory.ts
- packages/amplify-graphql-relational-transformer/src/resolvers.ts
ran `yarn prettier --write .`
None
N/A
> chore(graphql-relational-transformer): lint

- packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
- packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
- packages/amplify-graphql-index-transformer/src/resolvers/resolvers.ts
- packages/amplify-graphql-index-transformer/src/schema.ts
- packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/generate-resolver-vtl.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts
- packages/amplify-graphql-searchable-transformer/src/__tests__/generate-resolver-vtl.test.ts
- packages/amplify-graphql-searchable-transformer/src/generate-resolver-vtl.ts
- packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
- packages/amplify-graphql-sql-transformer/src/__tests__/__snapshots__/amplify-graphql-sql-transformer.test.ts.snap
- packages/amplify-graphql-sql-transformer/src/__tests__/amplify-graphql-sql-transformer.test.ts
- packages/amplify-graphql-sql-transformer/src/graphql-sql-transformer.ts
- packages/amplify-graphql-transformer-interfaces/API.md
- packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
This is a follow up on https://github.com/aws-amplify/amplify-category-api/pull/2385 .
It turns out that sandbox logic present in `@aws-amplify/graphql-model-transformer` is also present in `@searchable` `@index` and `@sql` transformers and also requires amendments to allow iam access for types annotated with these directives (that are NOT annotated with `@auth`).
1. for `@searchable` service directive logic and sandbox resolver is amended.
2. for `@index` service directive logic and sandbox resolver is amended.
3. for `@sql` only resolver is amended, there's no logic to add service directives present.
This PR amends `@searchable` `@index` and `@sql` transformers by pattern matching changes from `graphql-model-transformer`.
Note: This PR does not attempt to remove this existing code …
> feat: iam access support for searchable, index and sql directives

- packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/auth-operations.test.ts.snap
- packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/iam-access.test.ts.snap
- packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-mutation-auth.test.ts.snap
- packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-query-auth.test.ts.snap
- packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/rds-subscription-auth.test.ts.snap
- packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
- packages/amplify-graphql-auth-transformer/src/vtl-generator/ddb/ddb-vtl-generator.ts
- packages/amplify-graphql-auth-transformer/src/vtl-generator/ddb/resolvers/field.ts
- packages/amplify-graphql-auth-transformer/src/vtl-generator/ddb/resolvers/index.ts
- packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/rds-vtl-generator.ts
- packages/amplify-graphql-auth-transformer/src/vtl-generator/rds/resolvers/common.ts
- packages/amplify-graphql-auth-transformer/src/vtl-generator/vtl-generator.ts
- packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
- packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
- packages/amplify-graphql-index-transformer/src/resolvers/resolvers.ts
- packages/amplify-graphql-model-transformer/API.md
- packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
- packages/amplify-graphql-model-transformer/src/resolvers/common.ts
- packages/amplify-graphql-model-transformer/src/resources/model-resource-generator.ts
- packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
- packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/generate-resolver-vtl.test.ts.snap
- packages/amplify-graphql-searchable-transformer/src/__tests__/generate-resolver-vtl.test.ts
- packages/amplify-graphql-searchable-transformer/src/generate-resolver-vtl.ts
- packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
- packages/amplify-graphql-sql-transformer/src/__tests__/__snapshots__/amplify-graphql-sql-transformer.test.ts.snap
- packages/amplify-graphql-sql-transformer/src/graphql-sql-transformer.ts
This is a follow up on https://github.com/aws-amplify/amplify-category-api/pull/2398#discussion_r1543128255 and https://github.com/aws-amplify/amplify-category-api/pull/2398#discussion_r1543461978 .
Changes:
1. Rename methods that generate `postAuth` resolver to drop sandbox naming (since it now handles both sandbox and iam auth)
2. Change preamble of resolvers to print both sandbox and iam status.
> chore: rename sandbox expressions to post auth expressions

- .github/workflows/closed-issue-message.yml
Adds a message when issues are closed.
---
> ci: add closed issue message

- packages/amplify-graphql-schema-test-library/src/index.ts
* Add a test schema using references to the test schema library
AFAIK these schemas are only used in codegen so the package should probably be moved there in the future.
N/A
N/A
N/A
> test: add references test schema

- codebuild_specs/amplify_ddb_canary.yml
- codebuild_specs/default_ddb_canary.yml
- codebuild_specs/e2e_workflow.yml
- codebuild_specs/run_cdk_canary_e2e_tests.yml
- codebuild_specs/sql_mysql_canary.yml
- codebuild_specs/sql_pg_canary.yml
- packages/amplify-graphql-api-construct-tests/src/__tests__/amplify-ddb-canary.test.ts
- packages/amplify-graphql-api-construct-tests/src/__tests__/backends/amplify-table/canary/app.ts
- packages/amplify-graphql-api-construct-tests/src/__tests__/default-ddb-canary.test.ts
- packages/amplify-graphql-api-construct-tests/src/__tests__/sql-mysql-canary.test.ts
- packages/amplify-graphql-api-construct-tests/src/__tests__/sql-pg-canary.test.ts
- packages/amplify-graphql-api-construct-tests/src/canary-tests-common.ts
- scripts/split-e2e-tests.ts
- shared-scripts.sh
This PR covers the tests and CI updates necessary to add new canaries that monitor the deployment success rate of Amplify GraphQL CDK construct for different supported model datasource strategies.
**Prior relevant PRs:**
- [Adds new Cloudwatch metrics and alarms for the canaries](https://code.amazon.com/reviews/CR-120424205/revisions/1#/details)
- [Adds new Codebuild projects for the canaries](https://code.amazon.com/reviews/CR-120940167/revisions/1#/details)
**In this PR:**
- Add specification files for newly added CDK canary codebuild projects.
- Add CI utility method that updates the canary metrics with the deployment status.
- Add CDK construct deployment test canary E2Es for supported strategies.
[Newly added E2Es pass in CI](https://tiny.amazon.com/1eug50vqv/IsenLink)
By submitting …
> feat: add canaries to monitor deployments using Amplify GraphQL CDK construct

- packages/amplify-graphql-api-construct/src/__tests__/__functional__/auth-modes.test.ts
- packages/amplify-graphql-api-construct/src/__tests__/__functional__/combine-synthesis.test.ts
- packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
- packages/amplify-graphql-transformer-test-utils/API.md
- packages/amplify-graphql-transformer-test-utils/src/__tests__/mock-sql-data-source-strategy.test.ts
- packages/amplify-graphql-transformer-test-utils/src/datasource-utils/mock-schemas.ts
Updates combine unit & synthesis tests to validate gen2-style relationships (using `references`)
> test: Update combine tests to support gen2 style relationships

- packages/amplify-graphql-schema-generator/vpc-db-lambda/package.json
Bumped `mysql2` dependency to `3.9.4` in the vpc lambda. This is a followup PR to the dependent bot alert one. 
Unit and E2E tests
Manual testing for `amplify api generate-schema` by using either directly from local machine or from vpc
> chore: bump mysql2 to 3.9.4

- packages/amplify-graphql-api-construct-tests/src/__tests__/restricted-field-auth/restricted-field-auth-gen1.test.ts
- packages/amplify-graphql-api-construct-tests/src/__tests__/restricted-field-auth/restricted-field-auth-gen2.test.ts
- packages/amplify-graphql-api-construct/.jsii
> chore: fix e2e test paths

- packages/amplify-e2e-core/package.json
- packages/amplify-graphql-schema-generator/package.json
- packages/amplify-graphql-schema-generator/vpc-db-lambda/package.json
- yarn.lock
Upgrade the `mysql2` dependency to `3.9.7` that is the latest available. It includes fix to [this dependabot issue](https://github.com/aws-amplify/amplify-category-api/security/dependabot/120)
PR and E2E checks.
> chore: upgrade mysql2 dependency to `3.9.7`

- package.json
- scripts/postinstall.sh
* move postinstall to bash script
---
> build: move postinstall to bash script

- .github/ISSUE_TEMPLATE/1.gen2_bug_report.yaml
- package.json
- scripts/create-private-package-manifest.sh
- shared-scripts.sh
Move the `postinstall` script to be run as part of deprecate workflow where it is needed.
This was causing issues in windows environments where the script is not being executed as part of `postinstall` action.
Verified that the contents of the script or execute permissions aren't the issue.
> chore: fix postinstall failure for windows

- dependency_licenses.txt
- package.json
- yarn.lock
Upgrade the dependency on `braces` to consume patch for a security vulnerability.
CI checks
> chore: resolve dependabot alert for braces package

- .github/ISSUE_TEMPLATE/1.gen2_bug_report.yaml
> docs: fix gen 2 issue template

- packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts
Set allowGen1Patterns to true in gen 1. 🤦 
N/A
N/A
* Run canary on this branch: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-canary-workflow/batch/amplify-category-api-canary-workflow%3Aeffa4039-cc7b-408a-8848-b93fcc29bb20?region=us-east-1
> fix: set allowGen1Patterns to true in gen 1

- packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/__snapshots__/ecs-apigw-stack.test.ts.snap
- packages/amplify-category-api/src/provider-utils/awscloudformation/base-api-stack.ts
- packages/amplify-data-construct/.jsii
- packages/amplify-graphql-api-construct/.jsii
- yarn.lock
* Dep security update https://github.com/aws-amplify/amplify-category-api/pull/2729
* Update awaiter s3 key https://github.com/aws-amplify/amplify-category-api/pull/2732
[E2E Tests](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:e7ef3ddf-d541-478d-8955-aad66f3697f4?region=us-east-1) (with beta layer and tagged release from CLI)
---
> Prep release

- packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/amplify-table-manager-lambda.test.ts.snap
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.ts
Adjust default table properties for `ProvisionedThroughput`, `SSEDescription`, `DeletionProtectionEnabled`.
N/A
* Manual testing. To be further validated with E2E tests in later PR
---
> fix: adjust default table properties

- packages/amplify-graphql-api-construct/.jsii
- packages/amplify-graphql-api-construct/API.md
- packages/amplify-graphql-api-construct/src/amplify-graphql-api.ts
- packages/amplify-graphql-api-construct/src/types.ts
- packages/amplify-graphql-model-transformer/src/__tests__/provide-hotswap-friendly-resources.test.ts
- packages/amplify-graphql-model-transformer/src/__tests__/provision-hotswap-friendly-resources.test.ts
- packages/amplify-graphql-model-transformer/src/resolvers/rds/resolver.ts
- packages/amplify-graphql-model-transformer/src/resources/rds-model-resource-generator.ts
- packages/amplify-graphql-transformer-interfaces/API.md
- packages/amplify-graphql-transformer-interfaces/src/transformer-context/synth-parameters.ts
added provisionHotswapFriendlyResources prop in `translationBehavior` and `synthParameters`. use the boolean flag to decide if we want to use a fixed physical resource ID for custom resources.
Unit test added.
> add: provisionHotswapFriendlyResources prop

- package.json
- yarn.lock
Update the `axios` dependency resolution to recommended version i.e `1.7.4`. This does not impact our customers since we only use this dependency in our private packages used for internal testing.
CI checks
> chore: update axios dependency

- packages/amplify-data-construct/CHANGELOG.md
- packages/amplify-data-construct/package.json
- packages/amplify-graphql-api-construct-tests/CHANGELOG.md
- packages/amplify-graphql-api-construct-tests/package.json
- packages/amplify-graphql-api-construct/CHANGELOG.md
- packages/amplify-graphql-api-construct/package.json
- @aws-amplify/data-construct@1.9.8
- amplify-graphql-api-construct-tests@1.8.2
- @aws-amplify/graphql-api-construct@1.11.8
> chore(release): Publish [ci skip]

- packages/amplify-data-construct/.jsii
- packages/amplify-graphql-api-construct/.jsii
> chore: update jsii files

- packages/amplify-data-construct/.jsii
- packages/amplify-graphql-api-construct/.jsii
Updates the JSII files to reflect the latest released version of API and Data CDK constructs
> chore: update jsii files for CDK constructs

- package.json
- yarn.lock
Set resolution for fast-xml-parser under aws-amplify. It is ok to use resolutions when scoped to `aws-amplify` here because the packages that use aws-amplify are used for tests and are not published to NPM.
```
amplify-category-api@0.1.0 /Users/dppilche/amplify/amplify-category-api
├─┬ amplify-category-api-e2e-tests@4.0.1 -> ./packages/amplify-e2e-tests
│ └── aws-amplify@4.3.46
├─┬ amplify-category-api-graphql-transformers-e2e-tests@9.0.1 -> ./packages/graphql-transformers-e2e-tests
│ └── aws-amplify@4.3.46 deduped
└─┬ amplify-graphql-api-construct-tests@1.9.0 -> ./packages/amplify-graphql-api-construct-tests
└── aws-amplify@4.3.46 deduped
```
`aws-amplify@4.x.x` does not contain the upgrade for `fast-xml-parser`. We need to update our tests to use the newest version of aws-amplify.
N/A …
> chore: set aws-amplify resolutions for fast-xml-parser

- packages/amplify-graphql-api-construct/src/__tests__/__functional__/resources.test.ts
- packages/amplify-graphql-api-construct/src/internal/construct-exports.ts
Copies the attributes of the L1 GraphQL API construct into the `resources.graphqlApi` L2 construct convenience property so customers can access them. This is especially important for use cases that use attributes of an AppSync GraphQL API construct like an Event Bridge integration (see #2644).
https://github.com/aws-amplify/amplify-category-api/issues/2644
Added unit test.
> feat: Add L1 construct properties to resources.graphqlApi

- dependency_licenses.txt
- yarn.lock
Refresh lockfile. This resolves several dependabot alerts.
N/A
N/A
Unit tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-pr-workflow/batch/amplify-category-api-pr-workflow%3A9901ec59-655a-48dd-8a59-89845d08bf53?region=us-east-1
> chore: refresh lockfile

- packages/graphql-transformers-e2e-tests/resources/jsonServer/src-server/package.json
- packages/graphql-transformers-e2e-tests/resources/jsonServer/src-server/yarn.lock
Set resolution on path-to-regexp in src-server
---
> chore: set resolution on path-to-regexp in src-server

- packages/amplify-data-construct/.jsii
- packages/amplify-graphql-api-construct/.jsii
Update .jsii. This was missed in some previous PR.
---
> chore: update .jsii

- .github/PULL_REQUEST_TEMPLATE.md
Add e2e test run to PR checklist.
---
> docs: add e2e test run to pr checklist

- client-test-apps/js/api-model-relationship-app/src/__tests__/utils/amplifyCLI.ts
- packages/amplify-e2e-core/src/init/initProjectHelper.ts
- packages/amplify-e2e-tests/src/init-special-cases/index.ts
test: fix gen 1 init api-plugin-stable
E2E tests: https://us-east-1.console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/build-batch/amplify-category-api-e2e-workflow:a86a9040-28bc-4e95-a4c7-413759294472/view/new
---
> test: fix gen 1 init api-plugin-stable

- shared-scripts.sh
Adds a node setup step to the deployment script. Also replaces the hardcoded Node version with a constant.
> chore: Fix deployment by setting up node version

- package.json
- yarn.lock
Verified that this is only a test dependency pulled in transitively by both `amplify-category-api-e2e-tests`, `amplify-category-api-graphql-transformers-e2e-tests` and safe to add an override to take care of the dep alert.
> chore: upgrade cookie version

- codebuild_specs/e2e_workflow.yml
- scripts/e2e-test-regions.json
This PR adds ap-northeast-3 to supported E2E regions selection/rotation, which will sync the E2E regions list with the Amplify Data Lambda Layer regions to ensure the coverage and correctness of test results.
> chore: sync region configuration with data lambda layer 

- .github/workflows/issue-pending-response.yml
Remove pending-community-response label and add pending-maintainer-response label to github issue when the community post a reply
> chore: update github issue label workflow

- scripts/yarn.lock
To fix [this dependabot alert](https://github.com/aws-amplify/amplify-category-api/security/dependabot/147), bumping `cross-spawn` version in `scripts/yarn.lock` to patched version. 
> bump cross-spawn version in scripts/yarn.lock to patched version

- scripts/verify-construct-dependencies.ts
Changed the construct dependency verification scripts search mechanism from BFS to DFS, to support transitive dependencies skip for construct dependencies bundling.
To be more specific, now the script will take a list of paths of dependencies, where the path's last package's transitive dependencies will be skipped in the verification.
The path is defined as an array of strings: `[repoPackage], [dependency],..., [dependency]`.
> feat: deps tree search improv

- codebuild_specs/pr_workflow.yml
- codebuild_specs/verify_construct_dependencies.yml
- shared-scripts.sh
Add construct dependency verification to PR workflow, instead of only running script in husky commit hooks. With the change dependency verification will be automatic for all PRs.
> chore: add construct dependencies verification to pr workflow

- .github/codeql/codeql-config.yml
Remove unused codeql config. This file is not on main anymore.
---
> ci: remove unused codeql config

- Readme.md
Update readme for gen 2. Copy most of the information from the amplify-backend repo.
---
> docs: update readme for gen 2

- packages/amplify-graphql-validate-transformer/src/__tests__/test-utils.ts
- packages/amplify-graphql-validate-transformer/src/validators.ts
Small refactoring to ~make Ian happy~ improve code quality. 
Addressed Ian's comments in:
- https://github.com/aws-amplify/amplify-category-api/pull/3130#discussion_r1934453626
- https://github.com/aws-amplify/amplify-category-api/pull/3130#discussion_r1934469272
> refactor: `test-utils` and `validateOrderingWithDefaultDirective`

- packages/amplify-graphql-api-construct-tests/src/__tests__/migration/migration-validation.test.ts
- packages/amplify-graphql-model-transformer/src/__tests__/import-table.test.ts
- packages/amplify-graphql-model-transformer/src/resources/amplify-dynamodb-table/amplify-table-manager-lambda/import-table.ts
Improve migration import error message. Change `Expected` to `Imported Value`.
N/A
N/A
Unit tests
> fix: improve migration import error message

- packages/amplify-graphql-api-construct-tests/src/__tests__/migration/migration-validation.test.ts
Update expected error message on non-matching gsi migration test. https://github.com/aws-amplify/amplify-category-api/pull/3144 changes the order of some items and should have update this test.
N/A
N/A
Run the E2E test. https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-category-api-e2e-workflow/batch/amplify-category-api-e2e-workflow:a4fe789e-5005-406c-a605-875aea16d26e?region=us-east-1
> test: update expected error message on non-matching gsi migration test

- package.json
- scripts/cloud-pr.sh
> chore: add script to run PR workflow from command line

- .vscode/settings.json
- package.json
- packages/amplify-data-construct/.jsii
- packages/amplify-graphql-api-construct/.jsii
- packages/amplify-graphql-model-transformer/rds-lambda/package.json
- packages/amplify-graphql-model-transformer/rds-lambda/tsconfig.json
- packages/graphql-transformers-e2e-tests/resources/jsonServer/yarn.lock
- scripts/cloud-pr.sh
- shared-scripts.sh
- yarn.lock
Merge latest changes to `release` to make canaries passing.
Nothing really to release in this PR.
> Merge main to release
